FILM
 
                            ============
                            Interface...
                            ============

Also, ich sollte eigentlich BWL lernen und habe CONTRA 6 (Name ge„ndert) einge-
stellt. Dort l„uft ein angeblicher  SF-Film: "Interface" (Name nicht ge„ndert).
Also - Technik, Backgroundstory  und  Ausstattung (Computer der 60er, brennende
Telefone, explodierende  Fernseher u.„.) sind natrlich lachhaft. Aber immerhin
entspannen  sich zwischen  einem lebensunf„higen  Informatikprofessor und einem
nicht weniger tolpatschigen weiblichen Rache-Rambo-Verschnitt mit Hang zu gros-
sen Kalibern  und rasantem  Fahrstil total  witzige  Dialoge. Aus  irgend einem
Grund wird auch st„ndig behauptet, es g„be keinen Computerclub...

Zur Story: Beide werden wegen dem Besitz einer (5.25-Zoll)-Diskette ( die Fr„u-
lein  Rambo einf„ltigerweise  auch mal  faltet ) von Computeranarchisten gejagt
und begeben sich leicht ver„rgert auf die Suche nach ihren J„gern.
Dabei gehen  eine Menge  Kulissen und  auch ein paar Polizisten drauf, die aber
noch viel  dusseliger sind als  ihre deutschen  Kollegen in den Witzen. Am Ende
gibt es ein Bonbon  fr Hardware-Freaks: einmal einen Saal voller Terminals ab-
rauchen sehen... ( krach, polter, bl|itz )

Ergo: bis  jetzt  habe ich mich  k”stlich amsiert, auch  wenn sich die "B”sen"
( 'ne Art TNB mit Gesichtsmasken ) noch ca. 1000% mehr zum Klops machen als al-
le anderen  Teilnehmer ( z.B. f„llt am Ende der Satz "Meine Mutter schl„gt mich
tot!" ).

Ist zwar kein Monthy Python, hat aber unfreiwillig das Zeug dazu. Also,durchaus
sehenswert und unterhaltend!

                                                     Apache of tnb / 26.03.1994
