 
               Was tun wir, wenn wir nicht am Computer sitzen
                     oder: Outing einiger kranken Hirne
               ----------------------------------------------

Wenn ich bedenke, daá einige  Menschen in  diesem unserem Lande noch immer ohne
das fundamentale QFT- Einheitensystem auskommen mssen,und daá noch immer nicht
dieses geniale  Teil allen unseren Mitbrgern zug„nglich gemacht wurde, muá ich
dieses sofort nachholen. Zu erw„hnen  w„re noch, daá  dieses System  maágeblich
mitgestaltet wurde von LOT of TNB und mir (Protz). Alle anderen die sich dieses
System unter  Mitwirkung einiger Biere  aus den Fingern gesogen haben, nochmals
herzlichen Dank. (s.u.)

Hier nun die ungeschnittene Erstversion, zum geneigten Schmunzeln geeignet.

-------------------------------------------------------------------------------

Ausgabe 1.0                              19.6.1993
Festgestellt 13.6.1993 vom internationalen
Ger„te- und Maáeinheitenkonzil fr
Quantit„tsFestlegungsTheoreme (QFT)
anl„álich des 1.allgemeinen Romanikkongresses
zu Querfurt 1993


Grndungsmitglieder des G & M-K QFT:
Dr. Mad M.; Dr. A.T. inc.;  Dr. Jesus
Dr. Corny;               Dr. Punx not dead
Dr. Axel;   Dr. Hannes;   Dr. R. jun.
Dr. Cornelius;             Dr. Fictum
Dr. Schlangenbeschw”rerin; Dr. andere



AUFBAU:         1. Titel
		2. Einheit, evtl. veraltete Einheit, Definitionsbereich
		3. Definition
		4. Umrechnungen
_________________________________________________________________


-       Der Nervigkeitswert
		1 Markgraf [Mg] (0-100)
		Die  durchschnittliche  Nervigkeit  einer ( pubertierenden ) Frau im Juni
		zwischen 22.00 und 24.00 Uhr betr„gt bei einer Endorpinauslastung von we-
		niger als 50% genau 100 Mg.

-       Der Langweiligkeitswert
		1 Nebra [NEB] (1-666)
		Die durchschnittliche Geschwindigkeit eines kriechenden KFZ aus Nebra vor
		dem mit 20 km/h fahrenden  Meáfahrzeug ist direkt proportional zu der Zu-
		lassungsnummer des zu messenden Fahrzeuges, besonders auf Landstraáen und
		Autobahnen. Desweiteren  ist der Langweiligkeitswert  direkt proportional
		zu dem Grad der  Alkoholisierung des  Fahrers des zu messenden Fahrzeugs.
		Betr„gt der  Langweiligkeitswert 666, steht  das KFZ, oder der Fahrer ist
		tot.

-        Der Neugierigkeitsfaktor
		1 Sprotte [Sp] (0-2)
		Ein Sprotte ist die Menge geballter Neugier,die eine (pubertierende) Frau
		nach einer durchschnittlichen Disco-Nacht der sie heimfahrenden Person an
		den Kopf wirft.

-       Der Nadine-Wert
		1 Grad Fr”hlich [øFr”] (0-100)
		Der Nadine- Wert ist die genau definierte W„rmemenge von drei Decken, ei-
		nem Mann  und einem  Zelt, die notwendig  sind, daá  eine (pubertierende)
		Frau eine Freiluftnacht ohne Frostbeulen bersteht. Diese Bedingungen be-
		stimmen die Meágr”áe 20øFr”.

-       Der Lbke-Wert
		1 Lindner [Li] (1-10)
		Ein Lindner ist  die Strecke von einer alkoholtechnisch bedingten Pinkel-
		pause zur n„chsten. Bei einem  durchschnittlichen  Blasendruck von 105 Pa
		und einer  Leereinwage des Magens eines  durchschnittlichen (pubertieren-
		den) Mannes betr„gt diese 3 Bier, unabh„ngig von der Maáeinheit der Menge
		"Bier".
		1 Li = 3 Bier
		7 Li = 21 Bier = 1 Scott [Sc](ungesetzlich)
		3 Li = 9 Bier; entsprechen 12,5 Hz Bildwiederholfrequenz.

-       Der Esmumalsein-Faktor
		n [100g*m-2] (0-2)
		Der Esmumalsein-Faktor ist  die integrale, hormonelle  Gr”áe  des ganzen
		K”rpers des subjektiven  Bedrfnisses eines durchschnittlichen (pubertie-
		renden) Mannes, eine vernichtende Sauftour zu veranstalten. Die Situation
		nach einem verpatzten Auftritt  resultiert im Esmusmalsein-Faktor 1. Per-
		sonen mit dem Esmusmalsein-Faktor 2 sind hochgradig suizidgef„hrdet.
		1 n = -5 Li

-       Die Jana-Intensit„t
		1 Hoffmann-Lux [Hx] (1-1,75)
		Ein Hx ist die integrale Differenz der Leuchtst„rke der blondierten Haar-
		farbe vom Haaransatz bis zur Haarspitze. An einem durchschnittlichen mit-
		teleurop„ischen Sonnentag betr„gt die Jana-Intensit„t einer durchschnitt-
		lich schnell  gewachsenen Haartracht  einer durchschnittlichen (pubertie-
		renden) Disco-Queen genau 1 Hx.

-       Der Wohlbrecht-Faktor
		1 Wohlbrecht [Wo] (1-30)
		Die durchschnittliche  L„nge der Haartracht  eines durchschnittlichen De-
		peche Mode-Fans betr„gt  im Mittelmaá zwischen zwei Friseurterminen genau
		1 Wo. Die durchschnittliche L„nge der Haartracht eines durchschnittlichen
		(pubertierenden) Bassisten  einer durchschnittlichen Band betr„gt z. Vgl.
		15 Wo.

-       Die Axel-Kennziffer
		1 K„stner [Kt] (10-3600)
		Die Axel-Kennziffer  bezeichnet  die Zeitspanne, die  ben”tigt wird, eine
		durchschnittlich  hbsche ( pubertierende ) Frau  von  der  ersten durch-
		schnittlichen Anmache bis zum durchschnittlichen Abschiebetermin zu bewe-
		gen. Im  Normalfall ( 25øC, 1,013 MPa, 75% rel. Luftfeuchte, 0,5 Promille
		beiderseits ) betr„gt diese genau 30 Kt.
		1 Kt entspricht 1 Sekunde [s].

-       Der Pidun-Grad
		1 Grad Pidun [øPi] (1-20)
		Der  Pidun-Grad ist  die  L„nge der  durchschnittlichen  Barttracht eines
		durchschnittlichen  mitteleurop„ischen ( pubertierenden ) Mannes im unra-
		sierten Zustand. Die Gr”áe 5øPi ist nach einem durchschnittlich aufregen-
		dem Wochenende mit durchschnittlich 5 h Schlaf definiert. Ab einem Pidun-
		Grad von 21 spricht man von einem Bart.
		1 øPi entspricht 10 hoch -3 Metern [m]

-       Die Mittel-Loderslebener Geipel-Zeit (MLGZ)
		1 Geipelstunde [Gh] (0-24)
		Die MLGZ ist  ein Ph„nomen, das nur  in und in der unmittelbaren Umgebung
		von Lodersleben  beobachtet werden kann. Sie gibt die exponentielle Zeit-
		verschiebungskompression  eines  durchschnittlichen  (pubertierenden) Lo-
		derslebeners zu der in Realzeit(RZ) verstreichenden Zeitspanne an. An ei-
		nem durchschnittlich  regenarmen, Mittelloderslebener Standardtag betr„gt
		die Verschiebung genau 1h 20 min exponentiell je 10 min; d.h. 10 min MLGZ
		entsprechen 1 h 30 min  Echtzeit. Der Extremwert  24 h MLGZ entsprechen 3
		Wochen Realzeit.
		1 Gh = 3e(0,4*RZ)k [h]; k: Naturkonstante: 8,15

_       Der BK-und ST-Wert
		1 [n] (-18 - 18)
		Der BK-Wert gibt  an, wieviele  durchschnittliche  Bierk„sten ein  durch-
		schnittlicher (pubertierender) Mann seinem besten Freund dafr geben wr-
		de, damit er ihm  seine durchschnittlich h„áliche Errungenschaft abnimmt.
		Damit ist  der BK-Wert ein  direktes Maá fr die optisch-akustisch-senso-
		libidoide  Qualit„t der  Begleitung. Da dieser  Wert einen  tats„chlichen
		Verlust fr das System darstellt, wird dieser negativ bezeichnet. Ist der
		BK-Wert jedoch positiv,stellt dies ein Maá fr die tats„chliche Bindungs-
		energie zwischen Mann und Begleitung dar: Sein Freund wrde ihm die Bier-
		k„sten zwecks Partnertausch bergeben. (Gewinn fr das System).
		Analog, mit  weiblicher  Ausgangsperson  und  Freundin, gilt  der ST-Wert
		(Schminkt”pfe)

-       Der BKB-Quotient
		1 Groth [Gr] (0-26)
		Der Braunkohle-Bagger-Quotient drckt den Intentions-(Absichts-) bzw. den
		Suxessions- (Erfolgs-)wert einer  Baggert„tigkeit aus. Dazu wird der BKB-
		in den BKBI- und  den BKBS-Wert  unterteilt. Dabei  ist 1 Gr(BKBI) gleich
		dem durchschnittlichen  Augenzwinkern  eines duchschnittlichen (pubertie-
		renden) Disco-Kings, 1 Gr(BKBS) dem  Wortlaut "Verpiá dich!" einer durch-
		schnittlichen ( pubertierenden ) Disco-Queen definiert. Den BKB(I/S)-Quo-
		tienten 27/0 bezeichnet  man  auch  als Mega-Groth [MGr]; den  Quotienten
		0/26 als Jamesbond [Jb]
		27 Gr = 1MGr

-Der bH- Wert
		1 Deutsches Greif [dG] (0-10), veraltet: 1 Baumann [Bm]
		Der bH- Wert  ist das indirekte  Maá fr das Volumen	der Oberweite einer
		durchschnittlichen ( pubertierenden )	Frau. Das definierte Maá 1 dG ent-
		spricht bei  einem durchschnittlichen ™strogen-Mittelwert  der Testperson
		exakt einer Handvoll eines durchschnittlichen (pubertierenden) Mannes mit
		durchschnittlichem Androgen-Mittelwert. Dabei ist  der bH- Wert nicht mit
		der strikt  weiblicherseits definierten Oberweite zu verwechseln. Der bH-
		Wert ist  nicht nur auf (pubertierende) Frauen beschr„nkt; ferner ist der
		bH-Wert nicht verwandt oder verschw„gert mit dem Brustumfang.
		1 dG entprechen 10 Baumann [Bm]


-------------------------------------------------------------------------------

Das Copyright dieses Systemes liegt ausschlieálich bei der G & M-K QFT.

Dieser Text  ist FAIR-WARE, d.h. zitieren ist erlaubt, sogar erwnscht; mit den
Frzen anderer zu stinken allerdings nicht. Wenn jemand wissen m”chte,wer alles
an diesen Quatsch beteiligt war,m”ge er bitte die einschl„gigen Kontaktm”glich-
keiten benutzten.
(C) G & M-K QFT 1993
(P) FXL of TNB 1994

Dennoch, bitte nicht verkrampfen, und nicht vergessen:
Steht im Sommer noch das Korn, ist wohl was vergessen wor'n.
(Mit freundlicher  Genehmigung  des Kasernen-Klo's  der  Heinrich-Hartz-Kaserne
Daun/ Eifel)

                                                        FXL of TNB / 22.03.1994









