 
                                  SKINHEADS
                                  ---------
           (... oder: Warum sollen wir uns Gedanken darber machen,
                      Hier gibt es sowieso kaum welche...)
 
DENKSTE! Neulich kam es selbst in unserem sonst so beschaulichen ruhigen St„dt-
chen zu einem Zwischenfall, der auch unsere Familie betraf! Dies ist umso ber-
raschender, wo Naumburg in unserer Region doch immer als Hochburg der Autonomen
und linksgerichteten  Gruppen galt und  eigentlich auch ist. šberhaupt  hat die
Punk- und Alternative Szene in  Naumburg unheimlich viele Anh„nger und zu šber-
griffen rechter  Schl„ger kam es relativ  selten, wenn man von der Massenschl„-
gerei Silvester '93/94 absieht.
Meist wurden die  rechten Heini's  schnell  wieder in Richtung  Bahnhof gejagt,
wenn sie eine Veranstaltung st”ren wollten oder  mal auf dem Rummel randalieren
wollten...
Doch inzwischen  hat sich unsere  Meinung gefestigt, da man  Abends nicht mehr
durch die Innenstadt von NMB wandeln sollte...
Mein Bruder, mein Cousin und dessen  Freundin waren am  vergangenen Freitag un-
terwegs auf dem  Boulevard, als sie 3 stinkbesoffene  Typen etwa  hundert Meter
von ihnen entfernt bemerkten, 2 lange Glatzen  und einen kleinen Hooligan.
Urpl”tzlich kamen  diese 3 Typen auf  meine Leute zugerannt, ihre  leeren Bier-
flaschen schwingend uns brllend: "Wir schlagen euch die Fresse ein!"...
W„hrend mein Bruder und die  Freundin meines Cousin's  versuchten zu entkommen,
gelang dies meinem Cousin nicht, da er durch  einen schweren Verkehrsunfall vor
einigen Jahren nicht mehr dazu in der Lage ist, zu rennen... Eine Glatze rannte
meinem Bruder hinterher, w„hrend die anderen beiden  ber meinen Cousin herfie-
len und ihn m„chtig  eins in die  Fresse  schlugen. Meinem  Bruder gelang es zu
seinem Auto zu entkommen und er versuchte durch diverse Gassen an meinen Cousin
heranzukommen, um ihn dort rauszuholen.
Dieser hatte sich inzwischen bis zur Kreuzung am Theaterplatz geschleppt, wobei
er immernoch von den zwei Schl„gern traktiert wurde...
Einige Passanten, die  mein Bruder  anhielt, doch mit  zu helfen, verwiesen ihn
an die Polizei und machten sich schleunigst aus dem Staub... Erst auf dem Markt
fand sich ein Mann, der helfen wollte  und sich mit den Glatzen prgeln wollte.
W„hrenddessen. Hatten am Theaterplatz einige Auto's angehalten, ohne da jemand
ausstieg und das makabere Schauspiel  beendete... Zum Glck kamen zuf„llig zwei
Bekannte meines Cousin's vorbei, von denen  der eine die Glatze mit seinem Por-
sche ber den Haufen fuhr (dies ist nicht ersponnen! Die Abdrcke von dem Typen
sind jetzt noch auf der Motorhaube zu sehen...)...
Dann traf die  Polizei mit zwei  Streifenwagen  ein. Die eine Glatze  flchtete
ber den Boulevard in Richtung Markt und wurde dort durch  die Polizei und mei-
nen Bruder gestellt. W„hrend der Festnahme  kam der abgebrochene Riese von Hoo-
ligan dazu und traktierte  in seinem Suff  sogar den  Polizisten mit  Schl„gen!
Da die Beamten aber zu viert  waren, konnten sie  den auch gleich ohne weiteres
einkassieren. Den anderen Skin fanden  sie schlielich am  Stadtpark auf  einer
Bank... Auch er wurde in Gewahrsam genommen...
Die Freundin meines Cousin's fand mein Bruder auf  der Vogelwiese, einem Treff-
punkt junger Leute in Naumburg.
Mein Cousin wurde  mit Verdacht auf  Sch„delbasisbruch, der sich zu Glck nicht
best„tigte, ins Naumburger  Krankenhaus gebracht. Er  ist mit Prellungen im Ge-
sicht, an Beinen und Armen sowie einer geplatzten Wange nochmal  glimpflich da-
vongekommen, wobei es auch angesicht  seiner Unfallverletzungen, mit deren Fol-
gen er heute noch  zu k„mpfen hat, h„tte schlimmer  ausgehen k”nnen (ist damals
in einer sechsstndigen  Notoperation dem Tod  von der Schippe gesprungen nach-
dem man ihn mit seinem Auto von einem Baum gekratzt hatte...)...
Jedenfalls sind die Schl„ger nach der Protokoll-Aufnahme (sie waren der Polizei
in Zusammenhang mit  „hnlichen Taten schon  bekannt) wieder  auf freien Fu ge-
setzt worden, was ebenso  eine groe  Schande ist, wie  die Tatsache, da  sich
kaum dazu bereit erkl„rt hat, zu helfen... Das  idiotischste war  wohl die Mei-
nung des Arztes in der Unfallaufnahme im KH: "Es bringe sowieso nix, diese Leu-
te anzuzeigen, da die Verfahren wegen "Geringfgigkeit" eingestellt werden wr-
den..." - Na das werden wir sehen...
Dieser Fall  zeigt einmal mehr, da diese  Typen ein  v”llig unsicherer  Faktor
sind, den man  nicht in  geringster Weise  kontrollieren kann, bzw. deren Taten
man nicht voraussehen kann, denn in diesem Fall haben die Opfer weder irgendwie
ausl„ndisch ausgesehen  noch haben  sie sich auff„llig  benommen, sondern  hier
sind einfach mir nichts dir nichts die erst besten Passanten berfallen worden!
Zur Zeit „rgert sich mein Bruder ber sich selbst, da er zuerst weggerannt war
(auch wenn mein Cousin dies so wollte...), und sich nicht direkt in die Schl„-
gerei eingemischt hatte, auch wenn  er dabei mit die Fresse vollgekriegt h„tte.
Da die Schl„ger inzwischen  bekannt sind, wird diese  Angelegenheit mit Sicher-
heit noch einige Aktionen nach sich ziehen...
šbrigens war dies nicht die  erste Konfrontation der  beiden  mit Skin's... Vor
geraumer Zeit konnten sie sich in einer  Nachbarstadt nur aufgrund des PS-star-
ken fahrbaren  Untersatzes  meines Cousin's einer  Aufmischung durch eine Golf-
Ladung Glatzen entziehen...

Was um Gottes Willen ist nur los in diesem Land?!

-------------------------------------------------------------------------------
                                                Moondog of tnb / 1. Advent 1994
-------------------------------------------------------------------------------

