-------------------------------------------------------------------------------
                         Vom Tod eines Gef„hrten
                        Mit Commodore ins Nirvana
-------------------------------------------------------------------------------

So, eine letzte  Meldung an alle, die es noch nicht wissen : Commodore ist tot.
Tot und begraben.
Ich meine  jetzt nicht den  alten Hut mit dem Verkauf an Samsung, sondern: Alle
Einzelstcke ( Produktionsrechte  an Hardware usw. ) wurden von Samsung einfach
weiterverkauft.

Die  Vorkaufsrechte  am CD 32 ( genau: an dessen  Produktionsrechten ) hat  nun
Phillips ( CDi ! Da soll  wohl ein Konkurrent  gecancelt werden ... ), ASI ver-
treibt den  1200er usw. Wie schon  gesagt ging es  bis jetzt  dabei aber nur um
Vorkaufsrechte. Was nun ganz  genau passiert kann ich nun  berichten. H”rt Euch
mal in einer kompetenten Mailbox um.

Aber wie  auch immer - es wird jedenfalls  kaum neue  Amigas geben. Die Entwik-
klerteams sind  schon lange aufgel”st  und fr die fast fertigen  Amigas findet
sich  wohl keiner, der Serienger„te aus den  Prototypen bastelt  und vertreibt.
Die alten Amigas werden dann wohl weiter gebaut und verkauft, solange sie einer
haben will - und  wer wei, wie lange  das ist, so schnell, wie die Entwicklung
geht,der A 1200 ist ja auch heute schon nicht mehr der Weisheit letzter Schlu.

PersOp: Vor so ca. 2 Jahren  h„tte mir eine Nachricht wie diese sicher noch ein
so richtig h„misches  Grinsen entlockt, aber  jede Menge Kumpels  in der Amiga-
Szene, mit denen sich echt gut zusammenarbeiten l„t, lieen mich auch die Vor-
zge jenes Computers und jener Welt sch„tzen lernen.
Und nicht zuletzt ist es einfach schade um einen der letzten Pioniere des gros-
sen Aufbruchs der Computer, um eines jener Unternehmen, mit dem die Technik er-
wachsen und massentauglich wurde, das wie  kaum ein anderes seinen Beitrag dazu
geleistet hat, da heute  Computer wie selbsverst„ndlich in fast jedem Haushalt
stehen.

Ruhe sanft. Wer wei, wer der n„chste ist ...

------------------------------------------------------------------------------
                                              Lot / TNB / QFT - SC / 20.07.1994
------------------------------------------------------------------------------

