                               COLOR CLASH
                               -----------
 
Hersteller       : Animal Soft
Art              : Jump'n'Run
Steuerung        : Joystick
Spieler          : 1
System           : ST/STE, Farbmonitor/TV, 512 KB RAM
Status           : Shareware
Preis            : 5 Gulden (Registriergebhr)

Bei diesem  Vertreter der  Jump'n'Run's handelt es  sich um eine Art berleg'n'
Jump'n'shot oder sowas.

Jedenfalls habt  ihr ein Chameleon  als Helden  durch diverse, auf Dauer  immer
verzwickter  werdende, H”hlen zu fhren, aus welchen ihr  erst raus kommt, wenn
ihr alle in der H”hle enthaltenen Fliegen eingefangen habt.

Dies ist  leichter  gesagt als  getan, denn euer  Vieh kann  von Natur  aus nur
spingen, und das nicht sonderlich hoch und auch nicht gerade weit. Dafr stehen
dann aber hin und wieder diverse  Getr„nke in der Gegend rum, die eueren Helden
zum Super-Chameleon mutieren lassen. Wenn es einen  blauen Trunk zu sich nimmt,
kann es sich mit seiner Zunge,die ber den ganzen Screen reichen kann, an Stei-
nen festsaugen  und diese  dann ber  den Screen ziehen, um nachher  vielleicht
drber zu gehen.
Desweiteren bl„st es sich nach dem  Genu einer roten Ration auf  und kann ber
alle Gefahrenstellen hinwegschweben.
Zu guter  letzt  gibt es noch  ein grnes Getr„nk, welches eure  Schwanzmuskeln
(Aaaaahh! Ihr habt wohl schonewidder  Hintergedanken?!?! Alte Ferkels!) st„rkt,
mit dem ihr dann  Steine zerbr”seln k”nnt, die euch im  Wege sind oder aber den
einen oder anderen unliebsamen Gegner die Ohren wund schlagt.

So,diese ganzen Sachen lassen euch die Level schaffen,allerdings ist viel Kopf-
arbeit gefragt,denn der Weg durch die H”hlen ist nicht immer gleich offensicht-
lich. Wenn man einmal  einen Fehler gemacht hat ist man gleich weg vom Fenster.
Dann hilft nur noch die  Selbstmordoption. Dabei  bl„st sich  unser Genosse auf
und kawoum... schon fliegen seine Fetzen ber den Screen.

So, von der Spielidee her  also ziemlich gut. Allerdings haperte es bei der Um-
setzung  der selben ganz  sch”n. Die Grafiken  liegen noch im  Durchschnitt und
die Animationen  sind  gerade noch  als solche  anzusehen, aber warum dem Spiel
nicht eine  kleine Musik  geg”nnt wurde, frage ich  mich echt. Die FX sind mehr
sp„rlich ges„et und klingen teilweise  nach unqualifiziertem PC-Speaker-Gequie-
ke. H„tte man  diese Sachen noch  mehr aufgebohrt, w„re wirklich  mehr drin ge-
wesen,denn so versinkt das Spiel trotz  des hohen Spielspaes  nur noch im Mit-
telma und in  der Flut anderer  Programme, die vielleicht  l„ngst nicht so gut
ausgetftelt sind, aber eben grafisch  und soundm„ig  mehr zu bieten  haben...
Auch die eingebaute  Pawort-Option  kann daran nix  mehr „ndern... Einfach nur
schade drum...


Bewertung
---------

Allgemein:
----------
Positiv : tolle Spielidee, Pawortabfrage

Negativ : grafisch und insbesondere soundm„ig gerade mal durchschnittlich

Gesamt:
-------

Grafik         :  55 %
Sound          :  40 %
Steuerung      :  70 %
Motivation     :  85 %
Preis/Leistung :  75 %
----------------------
Gesamt         :  65 %

-------------------------------------------------------------------------------
                                                                 Moondog of tnb
-------------------------------------------------------------------------------
