                            HALLO ALLE ZUSAMMEN!!!
                            ----------------------
 
Nach ber 8 Monaten sind wir zurck!
Jetzt, wo alle m”glichen  Gerchte in tnb ber das Weiterbestehen des Mags kur-
sierten, wurde es echt Zeit es auf den Tisch zu klatschen und alle Unklarheiten
zu beseitigen! Zwar sind wir 4 Monate zu sp„t,aber das warten hat sich fr euch
gelohnt. Warum? Hah!
Das Mag  ist endlich  Falcon-wrdig! Es gibt  ST- und Falcon-Version  und dabei
wird es auch bleiben. Hinzu kommt, da es so  viele Texte wie noch nie enth„lt,
die euch eine Weile besch„ftigen werden.
šbrigens werden wir auch  dieses Jahr ein  Weihnachts-Mag herausbringen und wir
hoffen auf eure Untersttzung mit Texten!
So,in der letzten Zeit hat sich viel getan.
Commodore ist tot (siehe auch  entsprechenden Artikel) und Atari  geht es allem
Anschein nach auch nicht mehr ganz so gut, wie erhofft. Die  Aktien sind in den
Keller  gerutscht (wenn  man der  ASM glauben darf). Die  Falcon-Computer-Serie
gammelt vor sich hin und findet immer weniger neue Anh„nger.
Die ST-Szene befindet sich in der Aufl”sung. Der Spielemarkt und die Demo-Szene
auf dem ST  ist total  zusammengebrochen. Die sporadisch  erscheinenden  Sachen
sind meistens die letzten Releases der Gruppen, bevor sie  sich dem  Falcon zu-
wenden.
Der  Falcon hat  die letzten  M”glichkeiten verpat  auch nur eine  ganz kleine
Nische auf  dem Spiele-Markt  zu finden. Bei noch  nicht einmal  10 Spielen  im
Laufe von anderthalb Jahren ist das extrem ”de... Dafr  hat sich die Demoszene
auf dem 030er  relativ  gefestigt (auch  wenn sie damit  den ST kaputt  gemacht
haben (die meisten waren vorher auf dem ST aktiv).
Lediglich auf dem Musik-Sektor scheint er die Stellung des ST halten zu k”nnen.
Der ST verliert dadurch die letzten Einsatzgebiete...
Ja und nun kommt der Jaguar! Er ist auf  jeden Fall keine Totgeburt! Er ist die
einzige Maschine, die Atari noch am Leben erh„lt, denn mit dem Falcon hat Atari
den gr”ten Flop in seiner Geschichte abgeliefert (verkaufsm„ig).
Die Spiele sehen vielversprechend aus und es werden immer mehr doch fest steht,
da Atari  mit dieser  Maschine den Konsolen-Markt, der inzwischen schon aufge-
teilt ist, nicht im geringsten  neu aufteilen kann. Der Grund: die massive Wer-
bung, die Atari angekndigt hat,scheint wieder eine leere Versprechung zu sein.
Zumindest  ich habe  noch nicht einen  Spot gesehen. In Atari-Mags ntzt solche
Werbung sehr wenig. Denken wir an den Falcon! Auch mit vielen Vorschulorbeeren
bedacht  ist er ohne  Werbung ziemlich  schnell abgestrzt! Wenn  das selbe dem
Jaguar wiederf„hrt,ist Atari endgltig am Ende!
In meinen Augen  steht sowieso fest, da Atari sich  vom Computer-Markt  verab-
schiedet hat! Falcon 040? Kein Geld! Jaguar-Computer? Schwachsinn hoch 80!
Die versuchen  jetzt nach Jahren auf  den Konsolen-Markt zurckzukehren, da der
im Moment doch eintr„glicher scheint als der Computer-Markt, auf dem die Konku-
renz erheblich zu stark ist,was die Hardware angeht.
Was bleibt sind eine Menge entt„uschter User, die lange Atari die Stange gehal-
ten haben,trotz aller Krisen und Dummheiten, die Atari im Laufe der Zeit durch-
stehen mute. Diese User  sind es aber, die Atari im  Gespr„ch halten! Ohne die
Szene w„re Atari schon l„ngst den Bach runter! Und nun?
Alles, was wir  machen k”nnen, ist die Szene  am Leben zu erhalten! Aus eigener
Kraft,denn von oben her ist  nix mehr zu erwarten! Ein Schritt  in die richtige
Richtung ist der Bau von TOS-kompatiblen Rechnern (Medusa040), der gleichzeitig
ein Schritt in  die Unabh„ngigkeit  von Atari ist. Auch wenn  alles noch in den
Kinderschuhen steckt, so gibt es doch noch Enthusiasten, die auch den Computer,
den TOS-Computer, noch nicht vergessen haben!
Doch ich  bin der Meinung, da wir auch den  ST nicht vergessen sollten! Er hat
es nicht verdient, einfach abgeschoben zu werden. Trotz seiner vielen Ecken und
Kanten ist er ein Rechner,den man lieb haben mu!
Deshalb steht es auch fest, da dieses Mag auch weiterhin fr den ST erscheinen
wird, ein only-Falcon-Mag wird es, zumindest so lange ich hier die Redax halte,
nicht geben! Dann  gar keines!!! Fest steht  inzwischen auch, da ich die Redax
auch weiterhin  vertreten  werde und nicht, wie erst geplant  an Apache abgeben
werde. Es w„re sinnlos dies zu tun,da dann alles von neuem reorganisiert werden
mte. Es bleibt alles so wie es ist!
Also dann!

                            Long lives the ATARI ST!!!
 
                                              Moondog of tnb / Undercover Redax
