                                 MONOCHROME
                                 ~~~~~~~~~~

Hi Mono-Freax....

Diese Screens wurden fÅr die Swiss-Alp-Convention  Megademo gecodet. Diese Demo
sollte die erste sein, die auschlieûlich fÅr den  Mono-Moni geschrieben  wurde.
Leider wurde diese Demo nie beendet.....

Die Screens sind nun Åber ein Jahr alt und die Demo  wird sicher nicht mehr re-
leased. Also habe ich mich entschlossen,meine Parts von diesem Demo Åber dieses
Mag zu verîffentlichen (nur zur Info: ich habe mein Pseudo geÑndert).

Ich hoffe, euch gefÑllt unsere  Arbeit  fÅr den Monochrom-Monitor, insbesondere
weil wir so etwas hîchstwahrscheinlich nicht noch mal machen werden.

Nun gut! Habt Spaû  mit unserer Production..... und kauft einen Farb-Monitor!!!

                                             Lig Lury of New Trend / 03.02.1994

Bye..........


Addresse:  Andreas Pataki
           Rappenwîrtstr. 49
           76189 Karlsruhe / Germany
           Tel.: + 0721 501720
 
 
