                                STE-DEMO-NEWS
                                -------------
 
ADRENALINE        - White Spirit            3 Disx  Multipart  1 MB
ETERNITY          - Nought & Mad Crosses    1 Disc  Multipart  1 MB
EXCELLENCE IN ART - Musique                 1 Disc  Musicdemo  1 MB
EXCELLENCE IN ART - Talk Talk               1 Disc  Musicdemo  2 MB !!!
ZEAL              - Birdie                  1 Disc  Multipart  1 MB

Quelle: ST Magazine 86

                                                    Moondog of tnb / 20.08.1994
