                             DANGEROUS FANTASY
                            -------------------

Crew           : Impact / Frankreich
Guestparts     : -
Art            : Multipart
Disx           : 1
System         : STE only, ber 1 MB RAM, RGB

Tja, dieses Demo hier ist nicht mehr allzu neu, wurde es doch  schon auf der im
Jahre '93  stattfindenden "Place 2 Be Party" released. Impact, die  bislang nur
mit Compils einige Achtungserfolge erzielen konnte, legten damit ihre erste STE
Demo aus, die sich nur mit  ber 1 MB RAM begutachten  l„t. Ob diese Systeman-
forderungen allerdings berechtigt sind, werdet ihr gleich lesen.
Zuallererst erscheint eine schon  so ziemlich als Standart  geltende Info-Page,
die von Chip-Mukke begleitet wird.
Daraufhin beginnt das Intro zur  Demo, welches mit  Trackermusik untermalt wird
und erstmal eine kleine Slideshow mit einer Weltraum/Alien/Fantasy-Story bringt
und nach  einer franz”sischen  Dots-Flagge  sowie einigen  Dots und einem recht
hbschen  Drachen-Bild geht es erst daran, das Demo zu pr„sentieren. Dabei wer-
den mehrere Grafiken und  Logo's eingebelendet  und der 1. Mainpart kann begin-
nen. Hier  gibt es  3D-Dots zu  sehen, die allerdings  allesamt nicht allzu um-
werfend sind. Es werden mehrere Objekte gezeigt und darauf gibt es einen "rich-
tigen" Vektor-Quader zu sehen, welcher allerdings nix besonderes darstellt.
Weiter geht  es mit einigen  simplen Line-Vektoren  und nach einem weiteren Pic
beginnt der zweite Mainpart.
Hier erklingt eine neue  Tracker-Musik, welche etwas  technom„ig angelegt ist,
aber nicht  unbedingt umwerfend  erscheint. Hier  gibt es Line-Vektoren in ver-
schiedenen Ausfhrungen zu sehen. Weiter geht es mit einigen hbschen Grafiken,
nach denen folgen sich verformende  Line-Vektoren vor einem  Starfield. Nachdem
man sich hier reichlich satt gesehen hat, geht es in den Endpart.
Hier gibt es ein hbsches, hin und her schwingendes Impact-Logo, ein Starfield,
kleine Vektoren und 'nen Textdisplayer mit den  blichen Sachen wie  Gren und
Credits und so weiter.
Tja, das war's schon. Der STE ist in dieser  Demo lediglich als MOD-Player ver-
wendet  worden. S„mtliche  Effekte h„tten auf  einem STF ebenfalls ohne gr”ere
Probleme und ebenfalls mit Tracker-Musik  gemacht werden k”nnen. Warum die Demo
allerdings soviel RAM braucht, ist mir ein R„tsel. Es gibt  nichts zu sehen und
da das  Demo von Disk  nachl„dt, kann ich  mir nicht  vorstellen, da das ganze
Demo im  Speicher behalten  wird... Tja, wat solls. Impact  haben auch  hiermit
nichts in  Richtung gr”ere Beachtung als  Demo-Crew zu finden, bewirken k”nnen
und ich halte das  Demo nur fr  Sammler leidlich  interessant... Da Impact eh'
tot sind, erbrigen sich jegliche Tips und Ratschl„ge sowieso...

Wertung, nach Schul-Noten-System (1 - sehr gut ... 6 - ungengend / SCHEISSE!)

Grafik       : 3
Sound        : 3
Code         : 4
Design       : 5
Originalit„t : 5
-----------------
Note         : 4
=================

-------------------------------------------------------------------------------
                                                                 Moondog of tnb
-------------------------------------------------------------------------------


Hy