                                DISK-MAG-REPORT
                               -----------------

Wie im  letzten Undercover  angekÅndigt, will ich in  diesem Artikel versuchen,
eine Art  Chronik/Geschichte der Atari-Diskmags  aufzuzeigen. Auf  die Idee kam
ich, als ich beim blÑttern in einer alten ASM einen Szene-Report fand, der dies
fÅr die Amiga/C64-Szene erledigte. Da auch auf unserem Rechner-System einstmals
eine relativ groûe Disk-Mag-Szene existierte, mîchte  ich versuchen, euch hier-
mit einen Einblick in diese goldenen Zeiten zu verschaffen...

Von Anfang an...
----------------

Tja, wer von  welchem Rechner-System  abgeschaut hat, kann ich heute nicht mehr
nachvollziehen. Es  muû so um  1988 gewesen sein, als die  Demo-Szene dabei war
sich zu  festigen und  bereits 1986 die  ersten Ausgaben der legendÑren ST-NEWS
das Licht der  Welt erblickten. Damals  war  noch viel Betrieb, war der ST doch
damals einer der aufstrebenden Rechner. Diese  ST-NEWS war ein sehr allgemeines
Magazin, daû sich um alles in  Sachen Atari kÅmmerte. Ansonsten  war noch rela-
tive Ruhe auf dem Markt, doch mit dem Aufwind der Demo-Szene  um 1990 herum be-
gann auch die Explosion des Mag-Marktes...
Ok, es gab  sporadisch ein paar  Magazine, die  jedoch alle keinen sonderlichen
Stellenwert hatten und meist schnell wieder in Vergessenheit gerieten...
Es war im Jahre 1990, als die wohl schon legendÑren LOST BOYS die erste Ausgabe
des MAGGIE  unter die Leute  brachten. Im Gegensatz zu den eher schlicht aufge-
machten ST-NEWS, prÑsentierte sich dieses Mag schon wesentlich farbenfroher und
legte quasi den Grundstein fÅr die Szene-Mags. Dieses Mag kÅmmerte sich anfangs
um nahezu alle Belange in Sachen Atari, wie Reviews von Spielen und Demos, Tips
und Tricks rund um  die Rechner, Programmieren etc. Damit  hatten die LOST BOYS
eine Lawine losgetreten. Die zu dieser Zeit bereits  unheimlich starke ST-Szene
brachte  innerhalb kÅrzester  Zeit diverse andere Mags auf den Markt und es kam
einem fast so vor, als wolle jede Crew ihr eigenes Mag heraus bringen.
Im Jahre 1991 gesellten  sich somit das  D.B.A.-Mag und das TOXIC-Mag hinzu und
die Mags spalteten sich in 2 Lager, die Szene-Mags und die "normalen" Diskmags.
Dieser Artikel soll sich natÅrlich um die Szene-Mags kÅmmern, da es sonst etwas
sehr arg unÅbersichtlich werden wÅrde. Einen Grenzfall gibt es Åbrigens mit dem
LEDGERS MAG, welches ein Szene-orientiertes Shareware-Magazin war...
Ganz schlimm wurde es im Jahre  1992. THE LOST BOYS gaben MAGGIE an DELTA FORCE
ab und diese  richteten das  Mag voll auf Scene  und Labern aus. Im selben Jahr
erschienen  die  ersten  Ausgaben  vom MASSIVE MAG, AMAZINE, DNT PAPER  und den
DISK TIMES. 1992 war  wohl auch  das Jahr, in dem die meisten Ausgaben der Mags
released wurden...
1993, mit dem Auftauchen  des Falcon und der Spaltung der Scene gab es wohl die
grîûten  Orientierungsschwierigkeiten. Einige  versuchten ihre  Mags auf beiden
Rechnern zum laufen zu bringen und auf beiden Schienen tÑtig zu bleiben, andere
wiederum gaben ihre Mags an  andere Crews ab oder  aber ihre Arbeit vîllig auf,
doch noch waren  die meisten groûen  Mags im GeschÑft, war  die Scene doch auch
nach der Spaltung auf beiden Rechner-Systemen membermÑûig recht zahlreich.
In dieser recht wirren Zeit  brachten wir, tnb, nach langem BrÅten (erste Ideen
zu einem Mag kreisten schon 1992 in den Kîpfen der Ur-tnb'ler) die erste Ausga-
be von Undercover, dem  ersten in deutsch verfaûten, scene-orientierten Mag auf
den Markt.
Inzwischen ist der Mag-Markt ziemlich ins Wanken geraten, was wohl vor allem an
der Aufspaltung der Szene liegt, die die Mags vorher zusammengeschustert hatte.
Obwohl viele ehemalige  Mag-Crews auf den Falcon  gegangen sind, haben sie ihre
Mags nicht mit rÅbergerettet. Der ST, als  Wiege der  Mags auf den Atari's, hat
mit dem Verlust der nahezu  kompletten Scene auch seine Mags eingebÅût. Es gibt
hauptsÑchlich  in England  noch eine  Reihe  Diskmags, die  aber allesamt nicht
Scene-stÑndig sind  und  fÅr diesen  Artikel daher von  keinem groûen Interesse
sind. Momentan gibt es nur ein  richtiges Scene-Mag auf dem ST, welches aus dem
fernen  Finnland kommt, EYE ON SCENE von  den  Admirables, allerdings  weiû ich
nicht, ob  dieses Mag  noch existiert, ist  mir Nirvana / ADM doch seit Monaten
eine Antwort schuldig...
Auf dem Falcon existiert ebenfalls  nur ein richtiges Scene-Mag, das D.B.A.-Mag
von der  gleichnamigen  hollÑndischen Crew, welche  die  ST-Version  ihres Mags
meines Wissens nach seit Ausgabe 10 nicht mehr releasen. Einige weitere interne
Scene-Mags soll es auf dem Falcon noch geben, von denen das wichtigste wohl das
Independent-Mag ist (war?), von dem  aber auch nur berichtet wurde -> habe noch
keins davon gesehen, da diese Independent-only sind.
Ok, ich werde euch jetzt mal die wichtigsten Mags genauer vorstellen...

-------------------------------------------------------------------------------

MAGGIE
------

Sprache : englisch
Inhalt  : Szene, Reviews (Demos, Games, Tools), Coding, Unterhaltung usw.
Stuff   : Demos, Spiele, Tools usw.
System  : bis Ausgabe 12 - ST only, ab 13 - ST & Falcon

1990 von den LOST BOYS und NEXT ins Leben gerufen (Issue 1 - 8)
     Das Mag prÑsentierte  sich mit einer grafisch  aufgemotzten GEM-OberflÑche
     und diversen  Chip-Musiken. Es wurde  Åber Maus  gesteuert und wurde stets
     mit einem oder mehreren Intro's eingeleitet.
1992 wurde die Redax an die DELTA FORCE abgegeben (Issue 8 - 10)
     Mit der öbernahme durch DF  wurde das  Mag einer  Schînheitskur unterzogen
     und prÑsentierte sich fortan mit einer grafischen OberflÑche. Es wurde na-
     tÅrlich ebenfalls Åber Maus gesteuert und  ebenso mit wirklich hochklassi-
     ken Intro's eingeleitet.
1993 wurde MAGGIE vom  MAGGIE TEAM  Åbernommen. Seitdem glitt dieses Mag leider
     immer mehr ins nichtsagende ab und lebte nur noch vom Namen und Glanz ver-
     gangener Zeiten... Die grafische OberflÑche der Delta-Force-Zeit war dabei
     erhalten geblieben, doch  die Grafiken  selbst hatten mÑchtig  an QualitÑt
     verloren, obwohl dem MAGGIE TEAM vornehmlich von der englischen Ex-Cracker
     Crew  THE LEMMINGS UnterstÅtzung  zu kam. Maussteuerung war obligatorisch.
     Es wurde auch Falcon-lauffÑhig gemacht, allerdings suchte man Intro's ver-
     gebens...
1995 die RESERVOIR GODS griffen dem  MAGGIE TEAM unter die Arme und renovierten
     das Menu von  Grund auf  und das fÅr  den Falcon. Seit  langem gab es auch
     wieder mal ein Intro, welches von DIGITAL CHAOS kam. Es scheint, als kînne
     MAGGIE seinen Stand wieder  festigen und vor allem wieder mehr in Richtung
     Scene zu  tendieren, auch wenn es sich dabei wohl um die Falcon-Scene han-
     deln wird. Maggie feierte seinen 5. Geburtstag.
1996 MAGGIE existiert noch (Ausgabe 19 ist aktuell -> im Februar released)
     MAGGIE gehîrt zur MAGNETIC INTERLUDE...

Fazit: Maggie war lange Zeit das fÅhrende Disk-Mag fÅr Scene  und Atari im all-
       gemeinen und prÑsentierte eine ausgewogene  Mischung an Lesestoff. Diese
       Mags  sollten in  keiner Sammlung  fehlen! Die  Ausgaben 11 bis 16, sind
       fÅr Freax  weniger  interessant, da  die Demo-Scene  kaum  noch beachtet
       wird. DafÅr sind die enthaltenen News rund um  den Atari stets recht in-
       teressant, da  die Macher  hinter dem  Mag einige  gute  Kontakte haben.
       Die  neuesten Ausgaben  lassen einen  neuen, offenbar  zum Positiven hin
       laufenden Schwenk vermuten, da  die RESERVOIR GODS nicht  nur Code-tech-
       nisch mitmischen, sondern auch mitschreiben...

-------------------------------------------------------------------------------

D.B.A. MAGAZINE
---------------

Sprache : englisch + hollÑndische Ecke
Inhalt  : Szene, Reviews (Demos, Games, Tools), Coding, Unterhaltung usw.
Stuff   : Demos, Games, Tools usw.
System  : bis Ausgabe 9 - STe only, 10 - Falcon & STe, ab 11 - Falcon only
 

1991 von D.B.A. (Disk Busters Association) aus Holland ins Leben gerufen.
     Das Mag  prÑsentierte  sich von  Anfang an in  einer grafischen OberflÑche
     und stellte diverse Chip-Musiken und Grafix zur VerfÅgung. Gesteuert wurde
     das ganze natÅrlich mit der Maus und Intro's gab es auch.
1992 wurde das Design erheblich  Åberarbeitet und  man kann ruhig sagen, daû es
     optisch das mit  Abstand beste Scene-Mag auf dem ST war. Bei der Maussteu-
     erung  ist  es natÅrlich  geblieben und die  Intro's kamen  inzwischen aus
     aller Herren LÑnder.
1994 wurde mit D.B.A.-Mag 10 die letzte  ST-Version released und  damit das ST-
     Kapitel dieses recht einfluûreichen Mags beendet.
1995 wurde die erste spezielle Falcon-Version mit viel VerspÑtung released (11)
     zwar nur als Preview  aber optisch  nochmals erheblich aufgebohrt. Das Mag
     dÅrfte den wohl besten Textviewer aller Zeiten haben! Issue 12  wurde nach
     der Fried Bits 3 released, mit dem Fried Bits 3 Realtime-Artikel! Mit Aus-
     gabe 13 ist letzten Sommer ein Zusammenfassung der letzten 3 Mags erschie-
     nen und im  Oktober letzten  Jahres wurde  die 14. Ausgabe herausgebracht,
     der LAZER & INTER ein bombastisches Intro verpaût haben....
1996 Das Mag wird natÅrlich  weiter supportet und eine 15. Ausgabe dÅrfte schon
     in KÅrze erscheinen... Das DBA-Mag gehîrt zur MAGNETIC INTERLUDE...

Fazit: Das D.B.A.-Mag zÑhlt nach wie vor ohne Zweifel zu den wichtigsten Scene-
       Mags, erst auf dem ST  und nun auf dem  Falcon, wobei es  teilweise sehr
       Holland-ausgerichtet war, was durch den Zusammenbruch der  hollÑndischen
       Scene inzwischen aber nicht mehr so ausgeprÑgt ist. FÅr  Falcon-Besitzer
       mit Hang zur Demo-Scene ist dieses Mag unverzichtbar, auch wenn es jetzt
       nicht mehr so oft released wird.

-------------------------------------------------------------------------------

AMAZINE
-------

Sprache : englisch
Inhalt  : Szene, Reviews (Demos), Unterhaltung, CHARTS!
Stuff   : Demos, Tools usw.
System  : STe only

1992 von MAD VISION in Frankreich ins Leben gerufen.
     Issue 1 prÑsentierte sich recht bescheiden in grafischer Simpel-OberflÑche
     und mit Tastatur-Bedienung sowie Chipsound-Untermalung.
     Ausgabe 2 wurde erheblich  renoviert  und fortan  ist das Mag  per Maus zu
     bedienen. Intro's waren bei AMAZINE stets in dabei!
1993 Åbernahmen THE HEMOROIDS das Mag, nachdem  MAD VISION als EKO komplett auf
     den Falcon  gewechselt war, und  releasten die  Ausgabe 4, welche bis dato
     auch die letzte Issue war, was wohl vor allem mit den Problemen in HMD zu-
     sammenhÑngt, wurde  doch die  Truppe inzwischen  schon mehrfach umstruktu-
     riert. Das letzte Intro war Åbrigens von ANIMAL MINE.
...  AMAZINE liegt momentan auf Eis und GerÅchten zu Folge soll keine neue Aus-
     gabe mehr das Licht der ST und Falcon-Welt erblicken.

Fazit: AMAZINE galt als DAS SCENE-Mag schlechthin. Es enthielt  die ultimativen
       Scene-Charts, die von hunderten Scene-Leuten  bestimmt wurden  und stets
       und  stÑndig die  aktuellsten und  umfassendsten News  rund um die Demo-
       Scene ansich. Mit der öbernahme durch HMD wurden die Charts  beibehalten
       und auch noch recht stark frequentiert, doch der Standart der Texte lieû
       extrem nach. AMAZINE war fÅr Scener und Freax ein  absolutes Muû! Andere
       Leute werden sich nicht so sehr mit dem Mag anfreunden kînnen.

-------------------------------------------------------------------------------

MASSIVE MAGAZINE
----------------

Sprache : englisch
Inhalt  : Szene, Reviews (Demos, Spiele, Tools), Coding, Unterhaltung
Stuff   : -
System  : STe only

1992 von THE ADMIRABLES in Finnland ins Leben gerufen.
     Ausgabe 1 prÑsentierte sich in grafischer OberflÑche, doch ohne Musik, und
     wurde Åber Tastatur gesteuert.
     Ab Ausgabe 2 wurde eine GEM-OberflÑche ohne  jegliche grafische auffrisch-
     ung eingefÅhrt, es gab Chip-Musik und wurde Åber Maus  gesteuert. Intro's,
     in recht bescheidener QualitÑt waren ab und an dabei.
...  MASSIVE MAG wurde bereits 1992 mit Ausgabe 4 wieder eingestellt.

Fazit: MASSIVE MAG ist das beste Beispiel fÅr das Fehlen von jeglichem Support.
       Von Anfang an  recht dÅnn  mit  Artikeln  ausgestattet  resignierten die
       Jungs von  ADM relativ schnell. Vielleicht  lag es  auch  daran, daû der
       Markt ohnehin mit Mags noch und nîcher Åberschwemmt  war und die Schrei-
       ber damit auch zu den bekanntesten und angesehensten Mags tendierten und
       solche doch eher bescheidenen Mags wie dieses links liegen lieûen.
       Vielleicht lag es auch  daran, daû  die ADMIRABLES  zu jener Zeit in der
       Scene noch nicht allzusehr gesetzt waren. Jedenfalls sind diese Mags nur
       fÅr Sammler interessant.

-------------------------------------------------------------------------------

DNT PAPER
---------

Sprache : franzîsisch & teilweise englisch
Inhalt  : Szene, Reviews (Demos, Spiele), Coding, Unterhaltung
Stuff   : Demos, Tools usw.
System  : STe only

1992 von der DNT-CREW begrÅndet.
     Das Mag bot  eine sehr  schîne OberflÑche  mit Chip-Musik, die von Ausgabe
     zu Ausgabe variierte, einen  recht  interessanten, ebenfalls îfter variie-
     renden Textviewer und natÅrlich Maussteuerung. Relativ gute Intros durften
     natÅrlich auch nicht fehlen.
...  DNT PAPER wurde Ende 1993  mit Ausgabe 6 eingestellt, nachdem die Crew auf
     den Falcon wechselte. Allerdings habe ich gerÅchteweise vernommen, daû das
     Mag weitergefÅhrt worden wÑre... Dann wÑre eine Ausgabe 7 (?!) aktuell...

Fazit: Dadurch, daû das Mag meistens in  franzîsisch gehalten  war, dÅrften nur
       die wenigsten etwas damit anfangen kînnen. Inhaltlich war es zum grîûten
       Teil scene-orientiert, wobei das Augenmerk verstÑndlicher Weise  auf der
       groûen  franzîsischen  Scene lag. Kurzzeitig  waren  auch  Charts mit im
       Spiel, die sich jedoch nicht halten  konnten. Dieses Mag ist wohl ledig-
       lich fÅr Freax von Interesse.

-------------------------------------------------------------------------------

TOXIC MAGAZINE
--------------

Sprache : englisch & teilweise franzîsisch
Inhalt  : Szene, Reviews (Demos, Spiele), Coding, Unterhaltung
Stuff   : diverses
System  : STe only

1991 von der EUROPEAN SWAP CREW ins Leben gerufen.
     Das Mag prÑsentierte sich in  einer GEM-OberflÑche mit  Chip-Musik und na-
     tÅrlich mit Maussteuerung. Es war mit mÑûigen Intro's ausgestattet.
1992 wurde das Mag mit Issue 3 von der I.C.S. Åbernommen.
     Damit wurde das  Mag einer  Schînheitskur unterzogen und  es erhielt  eine
     grafische OberflÑche mit Grafiken im  Text, ebenfalls  Chip-Musik-Unterma-
     lung und Maussteuerung.
1995 THE STORM BROTHERS sind nun fÅrs Toxic-Mag verantwortlich.
1996 TOXIC MAGAZINE exisistiert noch (Ausgabe 11 ist aktuell)

Fazit: Das TOXIC-Magazin stellt fÅr mich ein RÑtsel dar, da es sehr oft den Be-
       sitzer (?!) gewechselt hat  und somit stÑndig in anderem  Gewand und mit
       anders  ausgerichtetem  Inhalt  daher  kam. Unter der ESC  war es scene-
       orientiert und hielt sich eng  an das MAGGIE von TLB. Unter I.C.S. wurde
       es vornehmlich auf Labern  ausgerichtet und selbst  der Scene-Teil wurde
       arg eingeschrÑnkt. Welche  Sachen es nun  unter TSB beinhaltet, weiû ich
       leider nicht. Mir ist nur bekannt, daû es noch auf  ST ausgerichtet ist.
       Dieses Durcheinander  ist wohl vor  allem auf die recht undurchsichtigen
       Verbandelungen in der Scene zurÅckzufÅhren, die insbesondere die Cracker
       Scene betrifft, zu der I.C.S. und ESC gehîren, bzw. gehîrten.

-------------------------------------------------------------------------------

THE MEGA FOUR DISK MAGGIE
-------------------------

Sprache : Englisch
Inhalt  : Scene, Coding, Unterhaltung
Stuff   : diverses
System  : STe only

1993 1. Ausgabe auf der Fried Bits 1 unter  Mitwirkung von Lazer, Redlite, Digi
     Tallis und Chaos released. Das Mag ist  Tastatur-gesteuert und mit 2 recht
     netten Intro's versehen.
...  wahrscheinlich mehr als Party-Gag anzusehen, da  mir keine weiteren Ausga-
     ben bekannt sind.

Fazit: Durch die arg Scene-bezogene Laberei nur fÅr Insider interessant. Anson-
       sten auch fÅr Coder (Aura's & BSW's DSP-Docs...)

-------------------------------------------------------------------------------

EYE ON SCENE
------------

Sprache : Englisch
Inhalt  : Scene, Coding, Unterhaltung, Reviews (Spiele & Demos)
Stuff   : -
System  : STe & Falcon

1994 von den ADMIRABLES released. Maus/Tastatur-gesteuertes grafisches MenÅ mit
     Tracker-Musiken und animierter  OberflÑche. Recht  Funktions-umfangreicher
     Viewer.
...  EOS existiert noch. Ausgabe 2 wurde im August '95 released und die 3. Aus-
     gabe dÅrfte anstehen.

Fazit: Durch die starke ST-Scene-Orientierung  und die  doch recht groûe Unter-
       stÅtzung von seiten  der verbliebenen  ST-Scene kînnte  aus EOS eine Art
       Amazine werden  und ist somit fÅr Freax und Scener auf dem  ST ein unbe-
       dingtes Muss!

-------------------------------------------------------------------------------

DISKTIMES
---------

Sprache : Englisch
Inhalt  : Scene, Coding, Unterhaltung, Reviews (Demos)
Stuff   : Demos & Tools
System  : STe only

1992 von den UNIVERSAL CODERS aus  Finnland ins Leben gerufen und eher als Just
     for Fun Mag angepriesen stellte es jedoch technisch fÅr diese Zeit den ab-
     soluten Hîhepunkt dar. Es gab erstmalig in einem Disk-Mag auf dem ST Trak-
     kermusik  und  Hardwarescrolling gleichzeitig  (meines Wissens). Zudem gab
     es neben diversen Modulen noch diverse Digidrum  und PSG-Musiken. Das MenÅ
     selbst sah grafisch  ganz gut aus  und war nicht in die Maus-MenÅ's einzu-
     ordnen. Das Mag wurde Åber Tastatur gesteuert, was gegenÅber anderen Mags,
     die ohne Maus auskommen muûten allerdings wesentlich leichter ging.
     Das Mag lief noch im selben Jahr unter dem  Label ARMADA weiter. In dieser
     Allianz hatten sich die meisten finnischen Gruppen vereinigt.
...  die letzte  Ausgabe, die  ich habe, ist die 1.5 und  die ist von 1992. Ich
     nehme an, daû die DiskTimes tot sind, leider...

Fazit: FÅr Scener und Freax ist das  Mag wirklich  eine Bereicherung  und durch
       das fÅr  damalige  VerhÑltnisse doch  recht revolutionÑre  MenÅ auch fÅr
       alle anderen durchaus interessant...

-------------------------------------------------------------------------------

LEDGERS MAGAZINE
----------------

Sprache : Englisch
Inhalt  : Reviews (Demos & Spiele), Coding, Unterhaltung, Scene
Stuff   : diverse Software
System  : ST only

1991 Meines  Wissens kamen  die ersten Ausgaben zu dieser  Zeit raus. Da damals
     die Rumkletter-Spiel-MainmenÅs  der  letzte  Schrei waren, wurde einem die
     Textauswahl so prÑsentiert, was wohl fÅr ein Mag weniger angebracht ist.
     DafÅr waren die Mags von teilweise herrlichen  Intros diverser  englischer
     Gruppen begleitet und auch  die Macher hinter dem  Teil, THE UNTOUCHABLES,
     waren ja nicht die schlechtesten auf dem Gebiet.
1993 Auch hier bin ich mir nicht sicher... jedenfalls sind die letzten Ausgaben
     zu dieser  Zeit erschienen. Das  LEDGERS Mag hatte eine recht hohe Zahl an
     Releases geschafft und meiner Rechnung nach war Nummer 13 die letzte...

Fazit: Das LEDGERS-MAG war  vom Inhalt her nicht schlecht und glÑnzte mit teil-
       weise coolen Intro's, doch diese Jump'n'Run-MenÅ's waren nicht unbedingt
       zweckentsprechend. Ok, wer sich damit abfindet, kann sich die Teile noch
       ins Haus  holen. Wer sich seit JUST BUGGIN' nicht mehr an solchen MenÅ's
       ergîtzen kann sollte die Finger davon lassen, ihr verpaût nicht viel...
-------------------------------------------------------------------------------

SCRIBA COMMUNIS RESPONSI
------------------------

Sprache : Englisch
Inhalt  : Reviews (Demos & Spiele), Unterhaltung
Stuff   : Tools & Spiele
System  : ST only

1992 Die norwegische  Demo-Gruppe O.U.C.H., die vorher mit mehr oder minder um-
     werfenden Demo-Screens auf sich aufmerksam gemacht hat, released die erste
     Issue. Das Mag prÑsentiert sich im grafisch aufgepeppten GEM-Look und wird
     Åber Maus gesteuert. ZusÑtzlich gibt es Chip-Musik.
.... ich habe  keine Ahnung, ob  dieses Mag  noch existiert. Meines Wissens war
     die Issue 3 Volume 2 die letzte Ausgabe, die 1994 released wurde.

Fazit: SCRIBA COMMUNIS war ein durchschnittliches  Mag, was vor allem durch die
       doch etwas abgedrehten  Leute in O.U.C.H. etwas interessanter wurde, die
       einige ihrer beknackten Productions (das Game VASSVITTIG... abartig) mit
       dem Mag released haben... Nur fÅr Fans interessant.

-------------------------------------------------------------------------------

ST-NEWS
-------

Sprache : Englisch
Inhalt  : Reviews (Demos, Tools, Spiele), Unterhaltung... einfach alles
Stuff   : diverse Software aus nahezu allen Bereichen...
System  : lÑuft "dank" primitivster Shell auf ST und Falcon

1986 erblicken die ST-News bereits das Licht der Welt und  seit dieser Zeit ist
     der Mann  hinter diesem Mag  der selbe  geblieben, RICHARD KARSMAKERS. Das
     Mag prÑsentiert sich auch heute, in Zeiten der grafisch aufgemotzten MenÅs
     in extrem schlichtem Outfit.
1996 Die ST-NEWS existieren noch  und sind zusammen  mit dem DBA-Mag und Maggie
     ein "Info-BÅndniss" eingegangen, die MAGNETIC INTERLUDE... Damit haben die
     Macher der wohl  wichtigsten verbliebenen  Mags vor sich gegen das versik-
     kern der SchreiberkapazitÑten zu wehren.

Fazit: Aus Szene-Sicht ist das Mag  weniger zu gebrauchen, obwohl schon mal ein
       Blick auf Demos und Mags  geworfen wird. Als LektÅre neben einem richti-
       gen Scene-Mag ist  es allemal zu  empfehlen. Allerdings kînnte das spar-
       tanische Outfit eine Frischzellenkur gebrauchen!

-------------------------------------------------------------------------------

Tja, was soll ich sagen... Mit der  Zunahme der ganzen  Internet-Sache sind die
Diskmags als Medium  inzwischen  mehr als Åberholt. Was man  frÅher meist  erst
nach Wochen Åber irgendwelche Swapper in die HÑnde bekam, kann man heute in den
wichtigsten Homepages  der verbliebenen  Atari-Scene erfahren. Diese sind teil-
weise Diskmag-mÑûig aufgemacht (DHS-Homepage) und  werden relativ schnell aktu-
alisiert. Klar, so schnell kînnen Diskmags nicht erstellt und gespreaded werden
und darin  liegt das Problem... Tja, vielleicht halten  sich ja einige der Mags
noch ein Weilchen, denn sie gehîren zur Scene wie die Butter auf's Brot...

-------------------------------------------------------------------------------
                                                                 Moondog of tnb
-------------------------------------------------------------------------------
  