                                EDITORIAL...

Ein letztes Mal kommt nun euer Lieblingsmag, Undercover, um euch aus dem Alltag
in die Welt der Atari-Rechner zu saugen...
Wir sind im 3. Undercover-Jahr und es war schon eine sch”ne Zeit. Leider erleb-
te unser  Mag von Anfang an schon nur noch  den Untergang eines ganzen Rechner-
systems mit, dagegen tun konnten wir nix doch ich denke wir konnten euch wenig-
stens ab und an von der traurigen Realit„t ablenken...
Tja, der Grund fr  unsere finale Aufgabe ist  nicht der Untergang unseres doch
sehr ans Herz gewachsenen Atari's, nein vielmehr ist es  zum einen die Faulheit
unserer  doch recht  zahlreichen Leser, die von Anfang an nur wenig Mut zu auf-
bauendem Feedback und  zur Mitarbeit  zeigten und zum  anderen (auch  durch den
ersten Punkt bedingt) unsere Unlust, dieses Mag weiterzufhren.
-THE NAUGHTY BYTES- haben ihren Zenith l„ngst berschritten. Die aktiven Zeiten
sind vorbei, wir  sind nicht nur  geschrumpft sondern andere  Aktivit„ten haben
nach und nach die vorher durch den Rechner dominierte  Freizeit in Beschlag ge-
nommen. Damit  m”chte ich andeuten, da wir  einfach, selbst  wenn wir wollten,
nicht mehr dazu in der Lage sind, solche zeitraubenden und gro angelegten Pro-
jekte wie Undercover durchzuziehen.
Wir m”chten jetzt aufh”ren, bevor Undercover nur noch ein Name ohne Inhalt ist.
Wir haben  nun ein Jahr gebraucht, um  diese finale Ausgabe  qualitativ auf dem
Stand der „lteren  Ausgaben zu  halten, geschafft  haben wir es freilich nicht,
doch  bevor wir  das Mag  zu einem  Feld/Wald/Wiesen/Idioten-Mag mit 3 Artikeln
versumpfen lassen, machen wir den Deckel lieber selbst zu. Ich habe keine Lust,
den  Namen "Undercover" durch irgendwelche  Spinner mit durchgeknalltem Kritik-
Wahn durch schwache Ausgaben zu demolieren. Behaltet es lieber so in Erinnerung
wie es jetzt ist, von Outfit und Inhalt her...
Apropos Kritik, einige  Leute haben  sich immer wieder  am Outfit  gestoen (es
wurde als Ripp-Off des D.B.A.-Mags bezeichnet)... Diesen Dumpfbacken m”chte ich
natrlich noch entgegenhalten, da  wir uns bewut am DBA-Mag orientiert haben,
da uns das Konzept dieses Mags von je  her am besten gefallen hat. Andererseits
m”chte ich fragen, ob man denn berhaupt noch etwas von Grund auf neues bringen
kann, es war ja alles schon da und das ist der Punkt, an dem irgendwelche Idio-
ten immerwieder ansetzen mssen...
Klar, wir h„tten DBA nie schlagen  k”nnen, schon  allein aus dem  Grund unserer
Deutsch-Text-Orientiertheit, doch das  hatten  wir nie  vor, wir wollten unsere
Leser - die Atarianer-Gemeinde - unterhalten und dies ohne sie zu qu„len. Dabei
denke ich ganz besonders an die Interlace-Scheie einiger deutscher Mags und an
den Simpel-Look einiger anderer Leute. Ich denke, wir haben  unsere Aufgabe der
Unterhaltung  gut  gel”st und  nicht nur mit  inhaltlichen H”hepunkten, sondern
auch mit ansprechender  Gestaltung den  einen oder anderen Pluspunkt einheimsen
k”nnen...
Nun, im Jahre 1996, steht -tnb- da  und keiner  der letzten verbliebenen Recken
wei, wie es weitergeht. Klar ist nur, da es weitergehen wird...
Nicht nur  das die Atari-Rechner  aus unserer  eh' schon geschrumpften Gemeinde
anderen Rechenknechten  Platz machen muten, auch die  Faulheit der Noch-Atari-
tnb'ler ist momentan erdrckend...
Im Moment sieht es so  aus, da noch  ein paar ganz geringe Aktivit„ten zu ver-
zeichnen sind, doch wen  unserem letzten Mann, der Code-m„ig  noch was auf die
Beine zu stellen vermag, die Lust  und Puste ausgehen, ist mit einem wohl nicht
mehr zu behebenden Koma der -tnb-Gang zu rechnen...
Aus diesem  Grund m”chte  ich auf  keinerlei  m”gliche  Projekte verweisen, die
noch  auf irgendwelchen Plattenpartitionen  schlummern und  auf  einen  Release
warten. Ihr werdet dann sicherlich irgendwann mal im Internet ber unsere even-
tuellen Releases stolpern oder, falls doch noch irgendwann eine Support-Mehlbox
entstehen sollte (eigene oder aber von den (inzwischen auch schon in alle Winde
und Ecken zerstreuten) Bad Sectors) dort was von uns finden...
Wer Interesse hat, kann mich auch mal so kontakten, meine Addy ist  hinl„nglich
bekannt und ich habe  schon noch  ein kleines  Lstchen scene-bezogene Software
fr Atari-Rechner zu swappen oder einfach nur mal so zu labern...
Lobeshymnen und Feedback  sind wir keineswegs  abgeneigt doch verschont uns mit
irgendwelcher  Heuchelei die das  Fortfhren des  UC-Mags zur Folge haben soll,
mit Heul-Briefen k”nnen wir nix anfangen...

                           Ok, nach diesen Zeilen m”chte ich euch noch ein paar
                            unterhaltsame  Stunden  mit der  finalen UC-Ausgabe
                             wnschen... Entschuldigt  das Alter mancher Texte,
                              aber wenn man alleine schreibt, dauert halt alles
                               etwas l„nger...

                                 Eric / Moondog of tnb

                                   Ex-Redax und Quasi-Alleinverfasser von UC-6


gr