                                  TAKE DRECK
                                 ------------

Also, ich fange hier jetzt einfach an, einen von der Tischplatte zu labern. Der
Grund dafÅr: irgendeine Boulevard-Sendung auf Pro 7, bei der Åber Take That und
das  ausscheiden  von  Robby berichtet wird.  Das kann  jetzt  ziemlich  heftig
werden,  und Fans dieser "Gruppe" (ich hoffe Atari-Besitzer dieser Art gibt  es
nicht!)  sollten  jetzt  lieber einen anderen  Artikel  lesen,  weil  das  sehr
persînlich und beleidigend werden kann...

So,  jetzt aber los!  Ich kann es nicht fassen, daû Leute auf die Straûe gehen,
weil ein  schwuler Wichser  (was nicht als  Beleidigung gegen  Schwule gedeutet
werden  soll!)  aus aus irgendeiner verfickten Band (wobei ich  mit  dem  Titel
"Band"  echt nicht einverstanden bin!  So was ist keine Band!!!  Ich werde  den
Club wohl mit Schwuchtel e.V.  titulieren) aussteigt. Wenn in Norwegen Wale und
Robben (fast nur aus tradition) gejagt werden oder die Pharma-Industrie  10.000
an  Affen,  Katzen,  Hunden und anderen Viechern fÅr ein  Kosmetik(!!!)-Produkt
"verbraucht"  (wie es so schîn heiût) ist den Leuten das scheiûegal,  wenn  ihr
"toller Robby" aus dem Schwuchtel e.V.  aussteigt.  Das kotzt mich echt an. Wer
micht  kennt,  wird  sowieso  wissen,  daû  ich den  Menschen  als  die  grîûte
existierende Naturkatastrope ansehe, aber das geht jetzt echt zu weit. Man geht
auf  die Straûe,  um gegen Atombomben-Tests oder TierquÑlerei zu  protestieren,
aber  nicht wegen sowas (dachte ich bis jetzt zu mindest)!!!  Tut mir  ja  echt
leid,  Leute,  aber das kann ich nicht verstehen. Auûerdem stirbt das Arschloch
ja  nicht  gleich  (leider!),  sonder lebt weiter,  nur nicht  bei  TÑik  SÑtt!
Deswegen weiû ich echt nicht,  warum 13-jÑhrige MÑdchen heulend durch die Stadt
rennen!  Die sollten sich doch freuen!  Take That wird es immernoch geben,  und
"Robby" wird seine eigene Schwuchtel-Gang aufziehen!

Zum Abschluû: Ich wÅrde nicht trauern, wenn sich diese fanatischen TT-Fans sich
die Kugel geben;  denn Leute,  die so einen Schwachfug Åber das, was der Mensch
sich  selber und der Natur antut,  setzt,  kînnen sich von mir aus  einbuddeln.
Eine  sarkastische  Bemerkung  zum  Schluû:  Wenn  sich  alle  TT-Fanatiker  im
Gartenteich versenken, sinkt der Sauerstoffverbrauch, die Umweltbelastung...

Ich hîr jetzt auf (bei Pro 7 sind jetzt Play-Mates zu sehen ;-)

Wer das jetzt anders sieht,  kann mich jetzt gerne anpîbeln.  Okay,  ich geb ja
zu, daû das jetzt extrem hart war (ich kann noch hÑrter :-)), aber ich sehe das
echt so...

Ach, so! Noch was! (Bin immernoch am glotzen)  Mir gehen Kerle,  die ihre MÑnn-
lichkeit  beweisen mÅssen,  indem sie mit Speeren auf  Stiere  einstechen,  bis
diese verbluten, mÑchtig auf den Sack!!! Alle an die Wand!

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                     drizzt/tnb
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Haha! Gestern war Feiertag! Hîhî! Take That gibt's nicht mehr! Haha! Schîn! Die
Nasen schleifen vielleicht  noch abermillionen  von pubertierenden Schwachmati-
ker-MÑdels mit in den  Abgrund, doch was soll's, Hauptsache wir sind erlîst von
dieser Pseudo-Band, die  nur in irgendwelchen  Kulissen rumstand, sich wie eine
Horde von Epileptikern bewegt haben, ihr hÑûliches Grinsen  in die Kamera's ge-
hÑngt haben und irgendwelchen MÅll zusammengajault haben.

Ich mache  mir nachher 'ne  Flasche Sekt auf  und hoffe auf balgiges Nachfolgen
solcher Kulturbanausen wie East 17 (brech... bleurgh...), Just Friends (Huaa!),
Kelly Family (Hat jemand 'ne Schrotflinte dabei, damit ich  diesen blîden, fet-
ten Pumuckl-Imitaten ihr hÑûliches Grinsen aus den, mit rotem Schimmel, der aus
ihrer  Kopfhaut  wÑchst,  verhÑngten, Gesichtern  schieûen  kann?!), Backstreet
Boys (... HÅlfe!)... Caught In The Act... brrr... oh, ich muû aufhîren, mir ist
so schlecht...

                                                          Prost! Moondog of tnb
aEX