                       INTERNET HOMEPAGES DER ATARI-SCENE
                     --------------------------------------
 
Ein groûer Teil der auf den Atari-Rechnern noch aktiven Gruppen haben im Inter-
net Homepages  eingerichtet, Åber die man das  neueste Åber die Gruppe erfahren
kann und teilweise auch Software ziehen kann.
-------------------------------------------------------------------------------
ôsterreich
----------
LAZER
(Falcon only)   http://stud1.tuwien.ac.at/~e9327376/harald.htm
-------------------------------------------------------------------------------
Finnland
--------
THE BLUES BOYS
(ST & Falcon)   http://vkol.pspt.fi/webmedia/tbb
-------------------------------------------------------------------------------
Frankreich
----------
ADRENALINE (tot?! -> EXA)
(Falcon only)  http://www.ens.lifl.fr/~truttet/atari/adrenaline/adrenaline.html

RELAPSE (THE CYBERNETICS -> Homepage zur STE-Demo)
(ST & Falcon)   http://www.efrei.fr/~jaques/relapse/relapse.html
-------------------------------------------------------------------------------
Deutschland
-----------
ABSENCE
(Falcon only)   http://www.informatik.uni-bremen.de/~tin/

ACF DESIGN TEAM
(ST & Falcon)   http://rzserv2.fh-lueneburg.de:8080/

AURA
(Falcon only)   http://www.informatik.uni-freiburg.de/~knaus/aura.html

NEW TREND
(Falcon only)   http://www.fh-karlsruhe.de/%7epaan0011/
-------------------------------------------------------------------------------
Groûbritannien
--------------
RESERVOIR GODS
(Falcon only)   http://basil.acs.bolton.ac.uk/~kwdlmat/
-------------------------------------------------------------------------------
Niederlande
-----------
DISK BUSTERS ASSOCIATION
------------------------
(Falcon only)   http://www.pi.net/^slimer/home.html
-------------------------------------------------------------------------------
Schweden
--------
CRYSTALIC
(ST only (?))   http://www.hgs.se:80/~na95mgn/

DEAD HACKERS SOCIETY
(Falcon only)   http://www.kuai.se/~ae/gfx_main.html

IMPULSE
(Falcon only)   http://www.dtek.chalmers.se/~d4reine/imp_hp.html

NEW BEAT DEVELOPMENTS
(Falcon only)   http://www.kuai.se/~dhedberg/

NOCREW
(Falcon only)   http://www.dd.chalmers.se/~f93labr/nocrew.html/

WILDFIRE
(ST only)       http://ledung.roden.se/~robert/
-------------------------------------------------------------------------------
Ein Teil dieser Homepages ist  immer noch nicht ganz fertig gestellt, doch auch
diese kînnen angewÑhlt werden.
Es gibt noch eine ganze Ecke mehr Pages, doch leider habe ich versÑumt bei mei-
nem Ausflug in die Pages mir die Nummern zu notieren, die mir beim Linken ange-
zeigt wurden. Ebenfalls Homepages haben AGGRESSION, NPG (sogar 2 StÅck), ANIMAL
MINE, IMPONANCE, INTER sowie die Ex-Members von der DELTA FORCE und OFFBEAT...
Weitere (Ex-?) Scener, angefangen  von  Redzone / SYNDICATE  Åber  S.O.T.E. und
Steph / MJJ bis hin zu SYNC sind ebenfalls im Internet zu finden.
-------------------------------------------------------------------------------
                                                                 Moondog of tnb
-------------------------------------------------------------------------------
h
