                               WEITERE KINO-TIPS
                              -------------------

DER BEWEGTE MANN
----------------
Deutsche Komîdie mit Till Schweiger

WÑhrend  unseres Ostsee-Urlaubs  suchten wir  mehrfach das in  Gîhren ansÑssige
Kino auf  und da wir  schon einiges (vornehmlich  gutes) von diesem Film gehîrt
haben, gingen wir schlieûlich auch hin.
Worum geht's  in dem Streifen. Tja, der Kellner Axel arbeitet mit seiner Freun-
din zusammen in  einer Tanzbar. Da  er quasi auf jeden Rock anspringt (da kenne
ich noch einen :-) kann er  einer Frau nicht widerstehen und vîgelt sie auf dem
Damenklo. Leider  sitzt seine  Freundin im  Klo nebenan und das Schicksal nimmt
seinen Lauf.
Sie wirft ihn aus der gemeinsamen Wohnung und er findet vorerst keinen, bei dem
er unterkommen kann, da er scheinbar schon zu viele Leute vor den Kopf gestoûen
hat. Tja, schlieûlich  bleibt er  bei einem  Kumpel hÑngen, der sich mit frust-
rierten  MÑnnern zu  GesprÑchsrunden trifft. Dort  lernt er auch Walter kennen,
welcher in Schwulen/Tunten-Kreisen als Waltraud rumwuselt. öber die geschlecht-
lichen Neigungen dieses Herrn brauch' ich ja wohl nix zu sagen.
Walter bringt ihn dazu mit auf eine groûe Schwulen-Fete zu kommen und will, daû
Axel bei ihm  einzieht. Axel  trinkt sich dort  zu und zieht bei Walters Freund
ein und damit nimmt das Chaos seinen Lauf.

Kurz, dieser Film ist einfach genial! GUCKEN!


OUTBREAK
--------
Amerikanischer Thriller mit Paul Newman

Huh! Hier bricht  eine Ebola-Seuche  inmitten Amerika's aus und das MilitÑr hat
die Idee dem Gegner in Form des Ebola-Viruses mit brachialer Gewalt entgegenzu-
treten, egal ob ein paar tausend Menschen dabei sterben oder nicht...
Wie und was  genau passiert, erlebt ihr im Kino... Der Film ist wirklich zu gut
um ihn hier auszuwalzen, zudem  es eh' schon eine ganze Weile her  ist, daû ich
ihn gesehen habe.


NIGHTWATCH
----------
Thriller

In diesem  Psycho-Thriller  Åbernimmt ein  junger Mann die  Nachtwache an einem
pathologischen  Institut. WÑhrend  der NÑchte geschehen dann allerdings unheim-
liche  Dinge und als  er seine Freundin dann einmal im Leichen-KÅhlraum vîgelt,
und  die Polizei  spÑter sein Sperma  dort findet, werden RÅckschlÅûe auf even-
tuell sexuell  abartiges Verhalten  des jungen Mannes geschlossen und die Kacke
ist echt  am Dampfen. So  ganz neben bei gehen  noch ein paar Menschen Åber den
Jordan... Dieser  Thriller ist  nix fÅr zart  besaitete. kotz-TÅten solltet ihr
ruhig mit einpacken, da es doch hin und wieder arg Åbel zugeht...


DOLORES
-------
Amerikanischer Thriller mit Jeniffer Jason-Leigh

Aha, mal wieder ein Stephen-King-Streifen. Diesmal ist es  kein Horror-Schocker
oder sowas  in der Art sondern mehr ein Psycho-Teil. Auf einer kleinen Insel in
den Staaten liegt  ein kleines  Kaff. Dolores  ist HaushÑlterin bei einer alten
Dame und diese kommt auf bislang ungeklÑrte Weise ums  Leben. Irgendwie hat der
Dorfsheriff etwas gegen Dolores und will ihr diese Sache als Mord anhÑngen. Das
aus dem Grund, da es vor Jahren einen anderen mysteriîsen Todesfall gegeben hat
an dem Dolores ebenfalls nicht ganz unbeteiligt war. Ihre Tochter kehrt darauf-
hin zur Mutter zurÅck und nimmt zum Schluû den Kampf um  sie auf... WÑhrend des
Filmes tun sich  schlimme AbgrÅnde auf, was  das Leben von Dolores angeht. Dies
wird mit teilweise arg robusten Szenen untermalt... Ich sage nur: ANSCHAUEN!

-------------------------------------------------------------------------------
                                                                 Moondog of tnb
-------------------------------------------------------------------------------



   