                            NEVERMIND THE BOLLOCKS
                           ------------------------

Crew    : Scarface / Frankreich
Art     : Multipart
System  : F030, 4 MB RAM, RGB, 650 KB auf Platte
Credits : Coding - Joe K-mel
                 - Sherlock
          Grafix - Veckman
          Musix  - Furax of Equinox

Hier kommt ein weiteres ganz anstÑndiges Franzosen-Demo! Nachdem nach der Fried
Bits 3 die  Demo-Scene so ziemlich  zur Ruhe gekommen war, wurden nur noch sehr
vereinzelt Demos  fÅr den Raubvogel  released, die jedoch meist  einen gewissen
QualitÑtsstandart hatten, so  auch diese Produktion hier, deren Macher mir bis-
lang nicht bekannt waren.
NTB (Kurz fÅr  den Titel) beginnt mit  einem hÅbschen  Schlangenlogo und cooler
Mukke. Kurz nacheinander werden Logo's und SchriftzÅge ein  und Åberblendet und
der erste  Screen steht. Links  ein kleines  Scarface-Logo aus  WÅrfeln gibt es
nebenher einen  relativ groûen Texture-Mapping-Cube zu sehen. Nach  einer Weile
auf dem Screen wird  das Logo herangezoomt  und ausgeblendet  und die  Schlange
aus dem Intro-Screen ist wieder zu sehen. Diese wird nun  in diverse Richtungen
verzerrt  und distorted, nicht  schlecht. Auch  dieses Bild wird wieder gezoomt
und  dabei ausgeblendet  und dafÅr  erscheint ein  anderes cooles  Logo auf dem
Screen. Vor  diesem Logo turnt  eine Scarface-Vektor-Coladose  mit Mapping  und
teilweisem Shading herum, gefolgt von einem weiteren WÅrfel mit Texturen.
Das Bild wird  letztendlich  mittels Pixel-Zooming  ausgeblendet  und die Mukke
bekommt einen anderen Touch.
Zuerst sieht  man eine kleine "Sonne" um einen Planeten herumtanzen, wobei die-
ser je nach Stand der Beleuchtung zu sehen ist. Dazu werden ein paar Daten aus-
gegeben, die auf eine kleine Space-MÑr einstimmen sollen.
Alsdann sieht man einen geshadeten Vektor-Gleiter von einer Raumstation starten
und zu diesem Planeten fliegen. Dort  angekommen fliegt er erstmal Åber ein be-
wegtes Meer und danach durch eine Rîhre, wobei er immer schneller wird und zack
haben wir  das Ende der Demo erreicht. Hier  gibt es neben  einem hÅbschen Logo
noch einen Scroller mit diversen Info's zu lesen.
Tja, auch  wenn diese Demo keine richtig neuen Effekte bringt, so sind die auf-
gewÑrmten Sachen doch schîn  in Scene gesetzt. Die meisten Effekte werden durch
schîne öberblender miteinander  verbunden und wenn  man die Grîûe des Files be-
denkt ist  es alles in  allem schon  ganz beachtlich, wenn  man es mit  anderen
Demos vergleicht. Fazit: Man sollte dieses Demo schon  haben, wenn man sich fÅr
Falcon-Demos interessiert, insbesondere da momentan ziemliche Ebbe in der sonst
so aktiven Falcon-Demo-Scene herrscht.

Bewertung nach Schulnoten-System ( 1 - sehr gut ... 6 - ungenÅgend / SCHEISSE)

Grafik       : 2
Music        : 2
Code         : 2
Design       : 2
OriginalitÑt : 2
-----------------
Note         : 2

-------------------------------------------------------------------------------
                                                                 Moondog of tnb
-------------------------------------------------------------------------------
 um