                                      SCHLAFLOS
                                     -----------

Autor          : Stephen King
Original-Titel : Insomnia
Erschienen bei : Wilhelm Heyne Verlag / Bertelsmann Lizenz
Preis          : 50 DM

SCHLAFLOS habe ich irgendwann letztes Jahr mal geschenkt bekommen, ich weiû nun
leider nicht mehr genau, warum, wieso, weshalb...
Jedenfalls ist dieser WÑlzer laut Kurzinfo auf der RÅckseite eine Story aus dem
Reich des Bîsen und anderer Dimensionen.
Es handelt von einem  alten Herrn, welcher nach  dem Tod seiner Frau auf einmal
nicht mehr schlafen kann, erst wird er eher munter und spÑter kann er Åberhaupt
nicht mehr schlafen, auch nicht durch Åberlisten seines Kîrpers.
SpÑter kommen ihm nicht  erklÑrliche Erscheinungen  hinzu, welche sich im Laufe
des Romans immer mehr  verstÑrken und er  bekommt auch neue FÑhigkeiten und als
dann einer seiner Nachbarn ausrastet merkt er, daû sich irgendwas zusammenbraut
in der kleinen Stadt, in der er lebt.
Nachdem jemand versucht hat ihn zu ermorden, macht er sich auf, um dieser Kette
von unheimlichen Ereignissen und dem entsprechenden Hintergrund auf die Spur zu
kommen. Mit von der Partie ist eine Ñltere Frau, die er schon lange kennt, doch
jetzt, als Witwer, mit anderen Augen sieht.
Im Verlauf des Buches  werden er und die Frau zu KÑmpfern fÅr das Gute und sein
ausgeflippter Nachbar zum Werkzeug des Bîsen, bis es  dann irgendwann zum Show-
down zwischen den beiden MÑchten, verkîrpert durch die 3 Personen kommt...
Das Buch ist  extrem langatmig... King tobt sich  hier mehr oder  weniger stark
auf weit Åber 700 Seiten aus. Das Problem dabei ist, daû des îfteren auch nicht
sonderlich anspruchsvolle Passagen enthalten sind, die das weiterlesen zur Qual
machen. Zudem wird der Inhalt  von Mal zu Mal verworrener, da sich die Story in
mehreren Dimensionen abspielt und auf verschiedensten SchauplÑtzen spielt.
King hat natÅrlich  auch dieses Buch in seinem sehr detailierten Stil geschrie-
ben und so werden nebenher  die Leute und Situationen in  dem Buch so genau be-
schrieben, daû man sich die Story fast bildlich vorstellen kînnte.
NatÅrlich wurde auf  einige BrutalitÑten, eine gehîrige  Portion Sarkasmus, wie
von ihm gewohnt nicht verzichtet und  man findet stellenweise sogar einige Ver-
suche, dem  Roman auch einen  leicht erotischen  Touch zu geben, zumindest ein-
zelnen Szenen...
Ok, das Buch ist ein Brocken. Ich, der ich mich mehr mit kleineren  BÅchern und
vor allem seinen  Kurzgeschichten befaût  habe, war von  dem Lesestoff  doch zu
stark  Åberansprucht, und so habe ich das Buch bis heute noch nicht zu Ende ge-
lesen und werde dies wohl auch nie schaffen.
Freunden  von sehr  stark verwinkelten  Geschichten mit  einem kleinen Schauer-
Effekt und Schwenk ins öbersinnliche sind mit  diesem Buch sicherlich gut bera-
ten und es wird ihnen sicherlich  einige -schlaflose- NÑchte bereiten, aufgrund
der FÅlle des Stoffes... Andere, die es eher kurz und knackig mîgen sollten das
Buch nicht  unbedingt kaufen  und wenn dann  sicherheitshalber  ein paar Seiten
probelesen...

-------------------------------------------------------------------------------
                                                                 Moondog of tnb
-------------------------------------------------------------------------------


ele