                                 ST-SHAREWARE-GAMES
                                --------------------

Nachdem der Kommerz-Markt offenbar v”llig zusammengebrochen ist, zeigt sich der
Shareware-Markt erfreulicherweise noch weiterhin recht aktiv und die so releas-
ten Games werden qualitativ immer besser. Da inzwischen auch nahezu alle Genres
abgedeckt werden, finden Gelegenheits-Spieler sicher auf diesem Gebiet noch ein
paar Sachen, die ihnen die lange  Weile vertreiben. Was man sich zulegen sollte
oder lieber nicht, lest ihr hier...

-------------------------------------------------------------------------------

                                   CASTLE CAPERS!
                                  ----------------

Programmierer : P. Abraitis / Grobritannien
Genre         : Jump'n'Run
Spieler       : 1
System        : ST / STE, 512 KB RAM, RGB/TV, Joystick
Preis         : Registrierung - 5 Pfund (SW-Version enth„lt nur 10 R„ume)

"Castle Capers" ist eines der relativ dnn  ges„eten Hpfspiele, die es auf der
Shareware-Schiene fr die alten Atari's gibt.
In diesem Game habt  ihr einen kleinen Troll oder was auch immer das sein soll,
durch  die Verliese einer Burg zu  fhren. Dies gestaltet  sich natrlich etwas
schwerer als es klingt, stehen euch doch nicht wenige Hindernisse im Weg.
So gibt es Wassergruben, Pfeil-Fallen, Spinnen  und anderes Getier, an denen es
vorbei zu  kommen gilt. Dazu kann euer Held springen, rennen  und auch klettern
(vorzugsweise an  Spinnenf„den und  Seilen). Diese  Aufgabe ist  ehrlich gesagt
nicht  unbedingt leicht  und allein fr den ersten Raum  braucht man einiges an
Anl„ufen  um durchzukommen, da es auch auf das  richtige Timing ankommt, in dem
man die Fallen und Gefahrenstellen passiert.
Somit sind  die 5  Bildschirmleben  relativ schnell verpulvert  und man mu von
vorn beginnen. Leider beschr„nkt sich das Spiel auf diese Aufgabe. Es mu nicht
noch was eingesammelt werden  oder irgendeine  Aufgabe gel”st  werden, was dann
doch auf Dauer etwas eint”nig ist.
Technisch pr„sentiert sich das Game fr Shareware-Verh„ltnisse ganz ordentlich.
Die Grafik ist recht anst„ndig durchdesignt  und kann sich durchaus mit den GFX
eines "Rick Dangerous" messen. Die  Sprites sehen  ganz nett  aus und sind auch
ausreichend animiert, wobei angesichts unseres  Helden Erinnerungen an das Game
"Ozone", welches auch im Shareware-Bereich released wurde, wach werden.
Soundm„ig ist dafr allerdings nicht viel los. Hin  und wieder mal so eine Art
Sample und das war's auch leider schon.
Die Steuerung geht  ziemlich in  Ordnung, wobei  insbesondere das Springen erst
mal  ein wenig  gebt werden  mu. Hat man dies Intus  gibt es allerdings keine
weiteren Probleme.
Tja, alles in allem ein ganz anst„ndiges Game, welches  ich, w„re es soundm„ig
nicht so  schwach auf  der Brust, bei  dem billigen  Preis, uneingeschr„nkt em-
pfehlen wrde... Jump'n'Run-Fans sollten sich das Teil aber auf  alle F„lle mal
anschauen, es lohnt sich sicher!

Bewertung
---------

Grafik         :  75 %
Sound          :  45 %
Steuerung      :  80 %
Motivation     :  75 %
Preis/Leistung :  80 %
----------------------
Gesamt         :  71 %
======================

-------------------------------------------------------------------------------
                                                                 Moondog of tnb
-------------------------------------------------------------------------------

                                     NOSTRAM
                                    ---------

Hersteller     : Powerfist Productions / Grobritannien
Genre          : Jump'n'Shot
Spieler        : 1
System         : ST / STE, 512 KB RAM, RGB / TV, Joystick
Preis          : Registrierung - 5 Pfund

šbel, bel, bel. Dieses  Game ist nicht  mehr sonderlich  neu, aber da  ich es
erst vor kurzem in meine H„nde gekriegt habe, m”chte ich mir gleich mein "Maul"
darber zerreien.
Ok. NOSTRAM ist  ein Spring/Hpf/Ballergame, in dem  ihr 5 Kristalle einsammeln
mt, die  an diversen Orten versteckt  sind und von verschiedenen Monstern be-
schtzt werden. Das war's auch schon zur Spielgeschichte.
Zur Technik... Uiuiui... Da haben sich die  Powerfist-Leute aber einen ziemlich
miesen Haufen ins Nest gelegt. NOSTRAM ist ein  h„licher Ripp-off von diversen
Bitmap-Brothers Games. Die  Grafik wurde offensichtlich  aus Gods und teilweise
auch aus Magic Pockets geklaut und das nahezu komplett. Die Items, Hintergrnde
und  auch teilweise  die Gegner  und sogar der  Titelscreen sehen verdammt nach
Gods aus... Ok, damit  ist die Grafik natrlich auch  verh„ltnism„ig gut, egal
ob sie  nun original ist  oder nicht. Dafr  mangelt es allerdings dann auch an
der Technik. Die Sprites etc. m”gen zwar gut aussehen, aber deren Animation ist
l„cherlich und die Steuerung extrem mies. Der Sound beschr„nkt  sich auf einige
Chip-FX und mich wundert es, da dieser nicht auch noch geklaut wurde.
Dann kann NOSTRAM natrlich auch nicht ber Scrolling verfgen und, wie es sich
fr ein  STOS-Game  geh”rt (h„h„h„) ist es  auch reichlich langsam. Wie gesagt,
es ist  laaangsam und scrollt  nicht - was macht es also? Es schaltet die Bild-
schirme um  und man darf jedes  Mal etwa 5 Sekunden warten, bis der neue Screen
steht. Damit kann also keine Rede von Spielflu sein...
Alles in allem mu ich sagen, da  dieses Game mit m”glichst wenig Arbeit viele
Registrierungen  und damit Geld  hat einfahren  sollen und ich  rate euch allen
nur: wenn ihr  Masochisten seid, k”nnt  ihr das Game ruhig zocken doch wenn ihr
dann auch noch die Shareware-Gebhr zahlt, ist euch nicht mehr zu helfen...

Bewertung
---------

Grafik         :  75 %
Sound          :  10 %
Steuerung      :  25 %
Motivation     :  15 %
Preis/Leistung :  30 %
----------------------
Gesamt         :  31 %
======================

-------------------------------------------------------------------------------
                                                                 Moondog of tnb
-------------------------------------------------------------------------------
%