 
                             SYMPOSIUM '96 RELEASES
                            ========================

Hier sind  nun alle (wenigen, sniff) Falcon-Demos  und Screens  zusammengefaût,
die auf der Symposium '96 bei Hamburg released worden sind...

-------------------------------------------------------------------------------

                              SYMPOSIUM 96 DEMO
                             -------------------

Crew    : Hydroxid / Frankreich
Was?    : Competition-Demo (2. Platz)
System  : F030, 4 MB RAM, RGB, 1,1 MB auf Platte
Credits : Coding - Arto of Hydroxid
                 - Hawkmoon of Hydroxid
                 - Tat of Digital Chaos
          Grafix - Nytrik of Hydroxid
                 - Saya of Hydroxid
          Musix  -

Dies ist der zweite  Kandidat fÅr die  Falcon-Compos auf der Symposium gewesen.
Das Demo wurde live auf der Party von Arto mit Hilfe diverser anderer Leute zu-
sammengebaut...
Das Teil  beginnt mit einem hÅbschen HDX-Logo (neuerdings kÅrzen sich die Leute
OH- ab) und dazu schwabbeln linker Hand einige FlÑche herum, gleichzeitig setzt
die recht nette Mukke ein...
Als nÑchstes werden  im Takt der  Musik die Lettern  des Wortes Symposium 96 in
recht feueriger Form auf den Screen gestempelt, gefolgt von einigen Infos.
Richtig los geht es dann mit  einem Åblen Face-Distorter, bei dem wiedermal ein
Frauengesicht herhalten muû.
Darauf folgt  ein Dotspart mit diversen DSP-Dots-Objekten, die sÑmtlichst recht
groû sind. Einen hÅbschen  kleinen Nebeneffekt  gibt es bei den mit vorhandenen
Lightsourced Dots, deren Zahl oben in der rechten Ecke ebenfalls als rundlicher
Dotsscroller erscheint...
Als nÑchstes folgt eine recht merkwÅrdig anzuschauende Welle, incl. Kippe...
Es gibt dann nochmal ein groûes 3D-Dotsobjekt vor  einem leider fast gleichfar-
bigen Background, wodurch das nur sehr schlecht zu erkennen ist.
Danach springt eine groûe  Glaskugel Åber ein recht ansehnliches Bild einer Un-
terwasserlandschaft, welche  man durch die verzerrte Optik der Kugel betrachten
kann...
Nun kommen noch ein paar  nicht so berauschende Line-Vektor-Objekte nebst einem
netten Logo von Nytrik.
Jetzt folgen noch ein paar Beschwerden Åber nichtbeantwortete Briefe und Fuck's
an die PC-Freax.
Letzter Effekt ist ein weiterer groûer Face-Distorter.
Nun kommt  nur noch  der Abspann in Form  eines Scrollers mit sÑmtlichen Info's
zur Demo und im Hintergrund verbiegt sich ein  HDX-Logo als Fli-Animation?, was
sehr cool aussieht.
Alles in allem  kein schlechtes  Demo und da  ich das letzte Demo von HDX nicht
zum laufen  bringe (Realms Of Depth) kann ich  nicht sonderlich einschÑtzen, ob
sich die Jungs extrem verbessert haben. Jedenfalls ist das Demo recht anstÑndig
designt, und selbst wenn einige  Effekte doch etwas ausgelutscht  sind, weiû es
doch trotzdem zu gefallen...

Bewertung

Coding       :  2
Grafix       :  2
Musix        :  2
Design       :  2
OriginalitÑt :  3
-------------------
Gesamt       : 2-3
===================
 
-------------------------------------------------------------------------------

                                A RH POSITIV
                               --------------

Crew    : T.S.C.C. / Deutschland
Was?    : 4-Ktro -> COMPETITION (4. Platz)
System  : F030, 4 MB RAM, RGB, 3606 Bytes ohne Readme
Credits : Coding - Dynacore of TSCC

Dieses 4-Ktro  bringt sich  verformende, Delay-Linevektor-Objekte  und dazu  im
Hintergrund  ein  Plasma... Auf  der Symposium hat  man "Dank" der beschissenen
Projektor-Leinwand allerdings nichts von dem  Plasma gesehen... Ist fÅr 4K ganz
und gar nicht Åbel.

Wertung - Schulnoten-System

Coding       :  2
OriginalitÑt :  2
------------------
Note         :  2
==================

-------------------------------------------------------------------------------

                                BSE POSITIVE
                               --------------

Crew    : The Naughty Bytes / Deutschland
Was?    : 4-Ktro -> COMPETITION (3. Platz)
System  : F030, 4 MB RAM, RGB, 4096 Bytes ohne Readme
Credits : Coding - Drizzt of tnb
          Grafix - m.O.d. of tnb
                   Moondog of tnb

Hier hÑnge ich mich nicht rein... Das Teil ist  auf der Stuff-Disk und so kînnt
ihr euch eure eigene Meinung zur neuesten Hirntod-Production  bilden... FÅr die
Nicht-Falcon-Besitzer: Es gibt jede Menge Melto-Vision-Effekte zu sehen...

Es existiert auch eine Version mit Musik, die allerdings 12 KB groû ist und ein
Chip-Modul von GANDBOX / IVORY enthÑlt...

-------------------------------------------------------------------------------

                                    BUGS
                                   ------

Crew    : Trantor - Atari Dream Machines / Deutschland
Was     : 96-Ktro -> COMPETITION
System  : F030, 4 MB RAM, RGB
Credits : Coding : Trantor
          Grafix : Trantor
          Musix  : nhp / Anarchy & Hydra / Devils

Tja, das  Teil habe ich  mir inzwischen  zerschossen, als ich das Modul gerippt
habe... Sooo schlimm ist das aber nicht, da selbst ein ST ohne weiteres dazu in
der Lage gewesen wÑre (ok, ohne Trackermukke), diese  Effekte auf den Screen zu
bringen. Tja, was gibt es zu sehen?
Nicht viel, da wÑren ein paar distortete Logo's, ein Pseudo-Plasma und ein ganz
Åbler kleiner Bitmap-Zoomer, der zwar rotiert, die Pixel-Dame  dabei aber etwas
arg durcheinander bringt. Zum Abschluû gibt's noch 'nen kurzen Scroller und das
war's dann auch schon. Das Chip-Mod vom Amiga ist noch das beste an dem ganzen.
Also bei aller Liebe, sowas ist  nun wirklich  etwas fehl am  Platze. Ich hatte
ehrlich gesagt Probleme, Åberhaupt dafÅr zu voten, da man  halt von der letzten
Fried Bits etwas anderes gewohnt war. Zudem war es  auch etwas bitter sowas auf
einer Party zu releasen, auf der man endlich  mal die Mîglichkeit gehabt hÑtte,
den Amiga-Leute zu zeigen, was der Falcon drauf hat. Ok, hat  nicht geklappt...
Doch mit solchen  Screens hat sich  die Falcon-Scene  quasi selbst  ins Abseits
katapultiert...

Wertung - Schulnoten-System

Coding       :  4
Grafix       :  5
Musix        :  2
Design       :  3
OriginalitÑt :  6
------------------
Gesamt       :  4
==================

-------------------------------------------------------------------------------

                                CRUOR 96-KTRO
                               ---------------

Crew    : Cruor / Deutschland
Was?    : 96-Ktro -> NICHT in fÅr die Compo released
System  : F030, 4 MB RAM, RGB, 97580 Bytes auf Platte
Credits : Coding : Raving Mad of Cruor
          Grafix : Zweckform of Cruor
          Musix  : Radar

Dieses 96-Ktro ist leider nicht in die Compo gegangen, da die Jungs dachten, es
wÑre nicht gut  genug... NatÅrlich haben  sie sich nachdem die  paar Teile, die
abgegeben wurden, gezeigt wurden, mÑchtig in den A... gebissen, da es technisch
lÑssig mit jenen mitgehalten hÑtte...
Nun gut, neben zwei schmissigen Chip-Modulen gibt  es zu Beginn wiedermal einen
Feuereffekt, danach kommt ein kleines Cruor-Logo reingescrollt und  es geht mit
einem Texturen-Tunnel weiter, der optisch schon was  her macht. Dann folgt noch
eine kleine Grafik und man landet im Endpart, der einen Scroller vor Luftblasen
zum besten gibt... Im Vergleich zu den anderen Compo-Teilen schon ziemlich gut,
den zweiten Platz hÑtten sie mindestens gemacht...

Wertung - Schulnotensystem

Coding       :  2
Grafix       :  3
Musix        :  2
Design       :  3
OriginalitÑt :  3
-------------------
Gesamt       : 2-3
===================

-------------------------------------------------------------------------------

                                 DBA 4-KTRO
                                ------------

Crew    : Disk Busters Association / Holland
Was?    : 4-Ktro -> COMPETITION (5. Platz)
System  : F030, 4 MB RAM, RGB, 4275 Bytes ohne Readme (KEINE 4k!)
Credits : Coding : ?
          Grafix : ?

Tja, hier gibt es nicht viel  zu sehen. Der Screen  erinnert von der  Optik her
stark an den ST. Es ist zwar ein Fullscreen mit hÅbscher Mukke und Plasma-Bars,
aber das war's dann auch schon...
Amiga-Leute kînnen den Begriff GFA garantiert  nicht deuten und somit war damit
diesmal auch kein Eindruck zu schinden. Im groûen und ganzen  doch etwas arm im
Vergleich zur letzten FB... Wo geht die Falcon-Scene hin?!

Wertung - Schulnoten-System
---------------------------

Coding       :  4
Grafix       :  4
Musix        :  2
Design       :  3
OriginalitÑt :  5
-------------------
Gesamt       : 3-4
===================
 
-------------------------------------------------------------------------------

                                GURKENSALAT
                               -------------

Crew    : Inter / Deutschland & Lazer / ôsterreich
Was?    : 4-Ktro -> COMPETITION (2. Platz)
System  : F030, 4 MB RAM, RGB, 4096 Bytes ohne Readme
Credits : Coding : Lucky of ST of Inter
                   Energizer of Lazer
                   Photon of Lazer

Dies ist das wahrscheinlich Åbelste 4-Ktro  aller Zeiten, oder hat von euch mal
jemand eine Weltraum-Verfolgungsjagd mit Textur-Fightern  und jeder Menge Feuer
gesehen?! Wohl kaum...
Klar, technisch  ist das ganze  wirklich unheimlich  beeindruckend, doch leider
wird die Antwort auf den die Verfolgungsjagd in EKO's "Are You Experienced" mit
der Zeit etwas langatmig...
Dieses Demo zeigt allerdings auch, was man mit 4K alles anstellen  kann und ich
kann mir denken, daû so manchem  Amiga-Besitzer die Gusche offen stehen geblie-
ben ist, als das Zeug Åber die Leinwand flimmerte...

Wertung - Schulnoten-System
---------------------------

Coding       :  1
Design       :  2
OriginalitÑt :  1
-------------------
Gesamt       : 1-2
===================

-------------------------------------------------------------------------------

                                SEPTIC RAVE
                               -------------

Crew    : Spirits / Deutschland
Was?    : "Funtro"
System  : F030, 4 MB RAM, RGB, 7 KB auf Platte
Credits : Coding : Kyne of Spirits

Dieses "Demo" sollte  lediglich die  Abscheu der  Spirits gegenÅber  Techno zum
Ausdruck bringen. Es enthÑlt lediglich ein paar sinnlose Texte und kleine Logos
aus Delay-Line-Vektoren... Es waren mehr Parts geplant, aber letzendlich ist es
bei diesem  einen Screen  geblieben... Grafix und  Sound gibt es nicht... Einer
Bewertung enthalte ich mich...

-------------------------------------------------------------------------------

                                  EWIGKEIT
                                 ----------

Crew    : Spirits / Deutschland
Was?    : 4-Ktro -> Competition (1. Platz)
System  : F030, 4 MB RAM, RGB, 4056 bzw. 4060 Bytes auf Platte
Credits : Coding - Kyne of Spirits
                   Connor of Spirits

Dies war nun (entgegen A.-t-'s Aussage in der ST-Computer) das Gewinner-4-Kteil
auf der  Symposium... Technisch zu  Recht, mit  der Message  des Demos kann ich
allerdings, als gestandener Atheist, absolut gar  nichts anfangen... Die beiden
haben Bibel-Texte eingebaut und mit entsprechenden Effekten untermalt.
Zu Beginn seht ihr eine sich drehende Erdkugel als Line-Vektor, diese wird dann
abgefackelt  und eine  zweite Line-Vektorkugel  erscheint. Danach  gibt es noch
einen Feuereffekt und zum Schluû noch eine Simpel-Grafik... Wie gesagt, auf der
technischen Seite ist dieses Teil fast  schon ein Wunderwerk. Kyne  hat die mit
Abstand besten Fire-Routinen  auf dem Falcon  geschrieben, welche meines Erach-
tens erheblich  besser als die  von Lazer, Inter und  allen anderen sind... Ich
habe diverse Testscreens von ihm hier, die jedoch nicht  released werden dÅrfen
und somit habt ihr leider nur dieses kleine Demo hier zum Vergleich...
Wer dieses Demo nicht  hat, gehîrt erschossen. Ignoriert die Texte, solltet ihr
euch daran stoûen...
Obwohl dies das letzte Falcon-Demo der beiden werden sollte, haben sie die oben
aufgefÅhrte Demo in Angriff genommen, ob es zu einem Release der von Connor ge-
codeten Parts kommt, weiû ich nicht...

Wertung / Schulnotensystem
--------------------------

Coding       : 1
Design       : 1
OriginalitÑt : 1
-----------------
Gesamt       : 1
=================

-------------------------------------------------------------------------------
                                                                 Moondog of tnb
-------------------------------------------------------------------------------

o 