                     DAS GROSSE BUCH VOM KLEINEN ARSCHLOCH
                     -------------------------------------
 
Von Walter Moers
Erschienen im Eichborn Verlag
Preis: 2o DM

Hier kommt meine zweite Comic-Vorstellung in diesem Mag. In diesem "Sammelband"
sind die beiden  ersten "Kleines Arschloch"-Bcher  zusammengefat, mit sch”nem
Hartumschlag.
Wer das kleine Arschloch nicht kennt, ist selber eins... nee, bei dieser Comic-
Figur handelt es sich um  einen kleinen, versauten, anarchistisch angehauchten,
brutalen, sexistischen,  unh”flichen, vorlauten, altklugen, fremdenfeindlichen,
frechen aber dennoch ziemlich klugen Balg, der seine  Umwelt in meist unpassen-
den Momenten ungeheuerlich nervt und sich dabei einige Stcke heraus nimmt.
Anzuschauen ist das Ganze  nicht so hbsch wie  die Werner-Bcher, sondern eher
simpel, aber meist erfllen die kleinen  bunten Bildchen  ihren Zweck, denn der
Humor liegt eher in den Texten...
Was k”nnt  ihr in  diesem Buch erleben? Fr Leute, die  die beiden  B„nde nicht
kennen, erlaube ich mir eine kleine Aufz„hlung.

- Zuerst folgt natrlich die Geburt und Namensgebung...
- Das kleine Arschloch (KA) entdeckt seine Sexualit„t.
- Das KA berichtet von einer  selbstinszenierten  Theater-Auffhrung, welche in
  einen Porno mit Schlachtefest ausartet.
- Das KA besucht seinen sterbenskranken Opa und quatscht ihn zu Tode.
- Das KA geht ins Kino...
- Das KA bet„tigt sich als "Junger Samariter" und qu„lt einen Blinden.
- Das KA verwstet  bei einer  Geburtstagsparty  die Wohnung  seiner heimlichen
  Freundin... mit anschlieender Orgie...
- Das KA outet zwei Schwule.
- Das KA nervt einen Bademeister.
- Das KA verarscht einen Priester bei der Beichte.
- Das KA f„hrt in die DDR.
- Das KA spielt Batman, auf der falschen Seite des Gesetzes.
- Das KA hat Sprechverbot am Mittagstisch...
- Das KA sammelt fr die Bedrftigen (sich selbst...).
- Das KA besucht eine  Tropfsteinh”hle  und bringt  den Rundgangfhrer  aus dem
  Konzept...
- Frohe Weihnachten mit dem KA.
- Ende des ersten Bandes...
- Das KA singt kein Lied fr Greenpeace.
- Das KA als Telefonseelsorger.
- Das KA als Tierqu„ler... den kleinen Hund Peppi...
- Das KA im Flugzeug...
- Das KA qu„lt schon wieder den Peppi... will ihn letztendlich im Backofen ein-
  schl„fern.
- Das KA versucht sich als Rapper in einem Jugendbegegnungszentrum.
- Das KA und Peppi die 3.
- Das KA bet„tigt sich als Babysitter.
- Das KA ist mal wieder verliebt, in die Oma von nebenan.
- Das KA in seiner zweiten Liebesaff„re, mit Nachbar's Frau Renate.
- Das KA f„hrt Taxi.
- Das KA besucht einen katholischen Gottesdienst.
- Das KA verarscht einen Behinderten.
- Das KA bet„tigt sich als Radio-Ansager.
- Zueletzt gibt es noch einige "Kleinanzeigen" rund um das kleine Arschloch.

Wie ihr seht gibt es viel  zu lesen und auch  zu lachen. Allerdings  sind diese
Bcher nicht  ganz so mein Fall, da  ich mehr auf  sch”n ausgearbeitete  Comics
stehe, deren Bilder  auch etwas  aussagen, bzw. der Story  den ganz  besonderen
Touch geben, wie eben die Werner-Bcher.
Trotzdem kann ich diese Art von Comic allen  Leuten empfehlen, die mal abschal-
ten wollen oder  einen Lacher  zwischendurch brauchen (die  kleinen und  kurzen
Geschichten hat man in einigen Sekunden abgehakt...) und recht tolerant auch an
die h„rteren Sachen reagieren, denn teilweise schl„gt das kleine Arschloch ganz
sch”n unter die Grtellinie...

-------------------------------------------------------------------------------
                                                                 Moondog of tnb
-------------------------------------------------------------------------------

sc