                                 Begegnung
                                 =========

Das Raumschiff  schttelte sich. Mehrere Anzeigen blinkten rot. In den tosenden
L„rm hinein schrie der Pilot: "Such mir einen geeigneten Platz fr eine Notlan-
dung!"
Der so angesprochene  Computer  z”gerte kurz  und sagte dann: "5 Grad rechts in
etwa 12 Kilometern. Kurs setzen?"
"Hast du nichts n„heres?"
Wieder ein kurzes Z”gern: "Konkretisieren sie 'n„her' !?"
"Ich meine - jetzt..." Es  krachte. Nun wurden  alle Anzeigen  auf einmal  rot,
dann dunkel. Hoffentlich passiert  den Kindern nichts, dachte der  Pilot - dann
verlor er das Bewutsein.

Hoffentlich passiert  den Kindern nichts. Aus weiter Ferne kroch dieser Gedanke
in sein Gehirn. Etwas  anderes mischte  sich darunter. Es klang wie: "H”ren Sie
mich? Wachen Sie auf. He, Sie, ich wei ja nicht mal Ihren Namen."
Sein Gesicht wurde  kalt und na. Er  ”ffnete ein  Auge. Helligkeit  schlug ihm
entgegen. Schnell schlo er das Auge wieder und brummte er "Ja,Ja...". Er wute
nicht, wie es fr  die andere Person klang. Etwas stach ihn und sagte "Wenn das
jetzt nicht hilft...".
Ihm wurde abwechselnd hei und kalt. "Computer, d„mpfe das Licht etwas."
"Kleinen Moment", sagte die Stimme, "der Computer  ist schlimmer  dran als sie.
Ich erledige das."
Als der Pilot die  Augen ”ffnete, herrschte  ein angenehmes Halbdunkel, aber am
Sichfenster prangte der gleiend helle Begleiter des Planeten.

"Ist den Kindern etwas passiert?"
"Nein. Ein paar Schrammen und so. Die Grav-D„mpfer haben funktioniert. Aber ich
wei nicht, wie lange die kleinen Monster still halten werden."
"Nun, das werden wir bald wissen. Ich kmmere mich mal um den denkenden Schrott
hier. Sie haben noch kein Notsignal gesendet???"
"Nein." Der Lehrer err”tete.
"Nicht so  schlimm, unsere  Leute brauchen  eh noch  einen Tag  bis hierher, da
kommt es auf die fnf Minuten meines Blackouts nicht an."
"Wenn ich sie korrigieren darf - sie waren volle zwei Stunden bewutlos."
"Ooh..."

Der Lehrer  ging wieder  zu den Kindern, der  Pilot fing mit  der Reperatur an.

Eine Stunde  sp„ter. Die fremde  Sonne versank  langsam hinter  den Hgeln  und
sanfte Wellen  durchzogen das  Gras rund um  das Raumschiff. Es klopfte  an die
Cockpittr. "Herein!"
"Danke. hem - wie weit sind sie mit dem Schiff?"
"Fliegen wird es nicht mehr..."
"Und wann holt man uns ab?"
Schulterzucken.
"Dann denken sie  sich mal was  aus, um meine  Schtzlinge zu besch„ftigen. Die
zerlegen Ihnen sonst das ganze Schiff!"

Nachdenklich schaute der Pilot aus dem Fenster: "Tja, hier kann ich nichts mehr
machen - und ich glaube, ich hab' eine Idee."
Ein kurzer Klick und man h”rte die Kinder herumtoben. Der  Pilot r„usperte sich
zun„chst und sagte dann leise "Hallo."
Schlagartig  herrschte  Ruhe. "Tja, Kinder. Es dauert wohl noch eine Weile, bis
wir hier abgeholt werden. Aber ihr k”nntet mir ein bichen helfen damit man uns
schneller findet..."
Er begann seinen Plan zu erl„utern. Wenig sp„ter verlie  der Lehrer mit seinen
aufgeregt  schwatzenden  Schlern  das Schiff  in Richtung  Grasfeld. Der Pilot
schaltete l„chelnd den Peilstrahl ein.

Derweil kam der  Steinhauser ber die  nahegelegene Chausee geradelt. Er war in
der Kneipe gewesen und fuhr jetzt zu seinem Hof. Er hatte sich angew”hnt, dabei
nach seinem Acker zu schauen, der sich hier ber die Hgel schwang.
Was er aber heute sah, verschlug ihm die Sprache. "Saupreu' damische!!!"
schrie er, lie  sein Rad  fallen und rannte  auf die Gestalten zu, die fleiig
dabei waren Kornkreise in seinem  Getreide anzulegen. Leider stolperte  er ber
einen Feldstein und noch im  Fallen sah er, wie  die Gestalten in  einem blauen
Licht verschwanden.


EPILOG:
Am n„chsten Morgen  fand man den betrunkenen Steinhauser im Straengraben neben
seinem Acker. Man fragte sich allerdings, wie er es geschafft, vor seinem Sturz
noch zw”lf so akurate Kornkreise anzulegen.

-------------------------------------------------------------------------------
                                                                  Apache of tnb
-------------------------------------------------------------------------------
 al