                           Der moderne Bleistift
                           ---------------------
 
Es handelt sich dabei um eine Weiterentwicklung  von Systemen zur Textverarbei-
tung, wie wir sie bisher  kennen, in Richtung auf einen st„rker multifunktional
orientierten Ansatz. Zu den wichtigsten Vorteilen des sog."Bleistifts" geh”ren:
 
- Darstellung von Umlauten und internationalen Zeichens„tzen
 
- Problemlose Einbindung von Grafiken in Fliesstexte
 
- Tragbar und netzunabh„ngig
 
- Ohne Handbuch und Einarbeitungszeit  sofort anwendbar, der Aufdruck einer On-
  line-Hilfe ist jedoch denkbar.
 
- Ausgabe auf Normalpapier  und unebene Fl„chen - Bei entsprechender Handhabung
  automatische  Online-Verschlsselung (sog. Write-only-Code, z.B. in Arztrech-
  nungen)
 
- Farbf„hig in der Version "Buntstift"
 
- Vollkompatibel zur  Benutzeroberfl„che des  Industriestandards ("Kugelschrei-
  ber"-compliant gem. Std.-Dok. des "Faber-Edding-Pelikan"-Standards)
 
- Recycling-f„hig  durch Verwendung natrlicher Werkstoffe, Rcknahme durch den
  H„ndler nicht erforderlich
 
- Bereits als Quasi-Standard in vielen L„ndern etabliert
 
Einige Nachteile des Systems sollten ebenfalls nicht verschwiegen werden:
 
- Einbindung von  Animations- und  Multimedia-Komponenten in  Dokumente noch zu
  aufwendig
 
- Nicht Windows-kompatibel
 
- Zwar weitgehend virensicher, aber  einige F„lle der  šbertragung von [Schnup]
  (aka [Grippe], [Hatschi]) durch "Bleistift"-Austausch sind bekanntgeworden.
 
- Korrekturen sind nur mit einem gegen Aufpreis  erh„ltlichen Add-on (bzw. Add-
  in) m”glich - unter  dem Codenamen "Radiergummi" derzeit im  Betatest. Dieser
  Nachteil wird  allerdings durch die  vollst„ndige Integration  beider Systeme
  weitgehend vermieden.
 
- Aufgrund der  Verletzungsgefahr  am spitzen Ende sind bereits Vermutungen ge-
  „uert worden, es  k”nne sich beim "Bleistift" um das Abfallprodukt der mili-
  t„rischen Forschung handeln, so da sein Einsatz m”glicherweise ethische Pro-
  bleme aufwerfen k”nnte.
 
- Der umfassende Einsatz  von "Bleistiften" in Industrie  und Verwaltung k”nnte
  unz„hlige  Arbeitspl„tze in der Computerindustrie gef„hrden, wenn  der Struk-
  turwandel nicht  rechtzeitig vollzogen wird. Eine  Enquete-Komission des Bun-
  destags zur  Technikfolgenabschaetzung besch„ftigt sich zur Zeit mit entspre-
  chenden Vorlagen.
 
- Europaweite Normung ist derzeit noch nicht in Sicht.
 
Fazit: Es bleibt zu hoffen, das nach Beseitigung der noch verbleibenden Proble-
       me diese wirklich aussichtsreiche Technik vom Markt akzeptiert wird.
 
-------------------------------------------------------------------------------
                                                               aus 'ner Mehlbox
-------------------------------------------------------------------------------
hwe