                              Cybermorph - Nachlese
                              =====================

Bei "Cybermorph" handelt  es sich um das  Spiel, da dem Jaguar  beigelegt ist.
Als ich es das  erste Mal gesehen  habe, war ich etwas  entt„uscht. Doch inzwi-
schen betrachte ich "CM" etwas realistischer.

Kurz der Spielinhalt: Man sammelt mit dem "T-Griffon" die auf den Planeten ver-
streuten Pods ein, wobei man  von allen m”glichen  Gemeinheiten behindert wird.
Glcklicherweise kann man das Zeug abschieen.

Graphisch ist "CM" Mittelklasse, d.h. noch kein 64-Bit-Standart. Die Landschaft
besteht komplett  aus (verdammt! - ich will  meine PC-Tastatur wieder) gouraud-
schattierten Polygonen OHNE Texturen. Allerdings ist die Grafikausgabe flssig.
Das vielgeschworene  Morphen des "T-Griffon" findet  zwar ab und zu statt, doch
so richtig „ndert sich seine Form nicht.

Die zahlreichen Gegner  unterscheiden sich in Aussehen und Strategie. Wegen der
schwierigen  Steuerung kann man  sich ihrer allerdings nicht so recht erwehren.
Die Steuerung  erinnert ein bichen  an Mikado - es dauert  eine Weile, bis man
das Zielen beherrscht. Zum Glck kann man sich wenigstens die Ansicht frei ein-
stellen, ich habe  gute Erfahrungen mit der Ansicht von hinten + Fadenkreuz ge-
habt.

Beim Spielen kommt  nie so richtig  das Gefhl von Geschwindigkeit  auf, wie es
"Rescue-from-Fractulus"-Fans  auf dem XL kennen ( kannten ). Man kann zwar sehr
rasant herumfliegen - aber dann heit es: Zielen ade und schnell ist man in ei-
nen Pulk Gegner hineingeflogen.

Eine weitere  Einschr„nkung des  Spielspaes besteht  in der Waffenauswahl: man
schaltet mit einer  einzigen Taste ( "Option" ) zwischen  bis zu FšNF verschie-
denen Waffen um. Die  genaue Anzahl der Waffen und damit die Anzahl der n”tigen
"Option"-Drcke erbringt nur ein Blick auf das unten liegende Anzeigefeld. Hin-
gegen kann man mit  ganzen drei Tasten die h”chst seltenen Superwaffen aktivie-
ren, von denen man eh nur eine an Bord haben kann...

Insgesamt k”nnte "CM" eine bessere Steuerung vertragen und Texturemapping wrde
zusammen  mit  einem realistischeren  Geschwindigkeitsfeeling  ber  den  hohen
Schwierigkeitsgrad hinweg helfen.
Ich hoffe, da ATARI  bei "Battlemorph" diese Punkte bercksichtigt hat und dem
CD-ROM damit ein wirklich geniales Spiel beiliegt.

So long, im n„chsten Mag dann hoffentlich ein "BM"-Test...

-------------------------------------------------------------------------------
                                                                  Apache of tnb
-------------------------------------------------------------------------------
ien