                                   EDITORIAL
                                   ---------
 
Hallo Leute!

Habt ihr euch  also  wieder bei  uns eingefunden! Sehr gut! Ihr  werdet's nicht
bereuen :-)
Nachdem UNDERCOVER  m„chtig ins  Wanken geraten  war, nun die  Entwarnung: Auch
nach dieser Ausgabe werden wir nicht davon ablassen, euch weiterhin mit unserem
Mag zu strafen!
Was gibt's denn neues von  der UNDERCOVER-Front zu  berichten? Tja. Es gibt in-
zwischen  tats„chlich einen Amiga-Ableger  von UNDERCOVER, der  zudem unter dem
selben Namen aktiv ist und von den Bad Sectors verbrochen wird.
Wir haben es nach langen Diskussionen  und šberlegungen nun  doch seingelassen,
UNDERCOVER fr Amiga und Atari zusammen auf  eine Disk zu  pressen, da der Auf-
wand einfach nicht  vertretbar gewesen  w„re, obwohl mit viel  programmiertech-
nischen Hakenschl„gen dies durchaus realisierbar gewesen w„re.
Also werdet ihr auch in  Zukunft nur Atari-spezifische Sachen lesen. Wir werden
aber mit unserem Schwester-Mag einen regen Text-Austausch was allgemeine Themen
angeht, betreiben, denn Craptalk, News usw. drften wohl jeden User interessie-
ren, egal welche Maschine er hat.
Inzwischen gibt es brigens  noch einen  Grund, weiterzumachen. Wir  haben tat-
s„chlich Konkurrenz bekommen, deutschsprachige  natrlich! Dieses  Teil kmmert
sich ausschlielich um die Atari "Dreammachines" (030 und Jaguar) (so auch sein
Name) und ist daher in  meinen Augen  nicht  besonders  gut, denn  meine Traum-
maschine steht hier vor mir und ist ein simpler STFM.
Ich habe die erste Issue  dieses Mags  bereits unter  die Lupe genommen und war
doch etwas entt„uscht. Die Aufmachung ist  ziemlich trocken  und auch sonst ist
dieses Mag nicht  gerade als  High-End-L”sung  zu bezeichnen. Doch  jeder f„ngt
klein an und wenn ich an unser erstes Mag denke...
(Na, Zonk! Ich wute gar nicht, da Du so "seri”s" bist... :-).
Ich halte es pers”nlich  nicht unbedingt  fr eine gute  Idee v”llig auf Falcon
und Jaguar zu setzen, weil  diese beiden Ger„te  im deutschsprachigen Raum noch
l„ngst nicht dominierend  sind (Atari ST rulez forever!) und insbesondere finde
ich die Jaguar-Lastigkeit  doch  sehr berzogen. Scheinbar  haben die  Editoren
dieses Mags nicht daran  gedacht, da man zu  seinem Jaguar in diesem Fall auch
einen  Falcon  braucht, um was mit  dem Mag anfangen zu  k”nnen. Doch dies soll
nicht unser Problem sein :-)
W„hrend UNDERCOVER hingegen  gerade zum  Jahreswechsel  an seidenem Faden hing,
(Durch ein "internes" Unglck auf  das wir keines Falles mehr  eingehen werden,
h„tte es, wenn dieses  nicht doch noch  so glimpflich  ber  die Bhne gegangen
w„re, durchaus  zur  Einstellung des Mags  kommen  k”nnen. An dieser Stelle von
allen -tnb-Chappos, insbesondere von Apache, Lot und mir, die besten Genesungs-
Wnsche an Nadine!) hat sich sein Status in -tnb- wieder erstaunlich gefestigt!
Wir haben neue  Idee'n, mit denen  wir in  diesem Jahre  versuchen  werden, die
Initiative an uns zu reien und die  Lethargie vieler  unserer  Leser zu besei-
tigen und vielleicht l„t sich ja  tats„chlich der eine oder andere von uns zum
mitwirken  mobilisieren. Wie, erfahrt  ihr dann  in den  n„chsten  Ausgaben von
unserem Mag, die noch  dieses Jahr  auf die  schwindende Atarianer-Gemeinde ge-
hetzt werden.
Doch dazu  werde ich mich  nicht  weiter  auslassen, solange nix feststeht. Nun
erstmal wieder zur blichen Beleuchtung unseres Lebensraumes.
Zwischenzeitlich habe ich nach dem  Sichten diverser Software festgestellt, da
in Sachen ST und Falcon-PD/SW inzwischen wieder  mehr in Sachen Fun los ist und
viele Spiele erschienen sind, die nicht nur auf allen m”glichen Rechnern laufen
sondern diese auch noch in diversen  Beziehungen untersttzen. Insbesondere der
schon l„ngst totgeglaubte STE  erlebt einen 2. Frhling zu seinem 5. Geburtstag
und dies drfte wohl viele Leute  freuen, die sich  bislang nur mit STF-Spielen
zufrieden geben muten und den STE nicht im geringsten ausnutzen konnten.
Zwar nehmen die Aktivit„ten auf dem guten alten  ST weiterhin nach und nach ab,
aber da wir uns im  letzten Mag schon  ausfhrlich darber  ausgelassen  haben,
werden wir hier nicht weiter darauf eingehen. Wir  werden natrlich  versuchen,
euch nach wie  vor ein recht  umfassendes Bild von der Situation in Sachen Soft
fr die Rechner zu verschaffen.
Auch auf anderen  Gebieten nehmen  die Aktivit„ten  wieder zu. Die Falcon-Demo-
Szene z„hlt Gruppen-m„ig  inzwischen schon mit zu  den st„rkeren und produktiv
sind die ganzen Leutz sowieso unheimlich.
Die ST-Demoszene ist  immernoch  nicht ganz  down, soda  ihr auch diesmal noch
die eine oder  andere Meldung  im entsprechenden  Ordner  finden werdet und fr
dieses Jahr denke ich doch, da  sie sich noch  solange ber Wasser h„lt, bevor
sie ganz in den Underground abgleitet.
In Sachen Jaguar tut sich ja inzwischen was in deutschen Landen  und wir werden
dank eigener  Jaguars in tnb diesem  Treiben in unserem Mag  gebhrend Rechnung
tragen. šbertreiben  werden wir es aber  nicht, da unser Mag mehr  fr die TOS-
Rechner gedacht ist.
 
Zum runden Abschlu dieses Editorials m”chte ich mich  noch bei Neuromancer von
der Subway BBS fr den Support in Sachen neuer PD/SW-Software fr ST und Falcon
bedanken, denn ohne ihn k”nnten wir euch, insbesondere in Sachen Games nicht so
viel zum Lesen bieten. Ein weiteres Dankesch”n geht diesbezglich auch an PP's,
der durch das Ausrotten seines gesamten Sparschweine-Stalls 3 neue Falcon-Games
fr unser  Mag beleuchten  konnte, wodurch  wir noch  einen Kick  aktueller als
sonst geworden sind... Ein zus„tzliches Dankesch”n  wollen wir hier noch an die
Jungs von Delirium Arts und Rebelsoft senden, die uns mit  Demo-Versionen ihrer
neuesten Soft versorgt und damit  ebenfalls aktueller  gemacht haben. Natrlich
bedanken wir uns hiermit auch bei allen anderen, die uns mit Artikeln und Soft-
ware versorgt haben. Durch euer  zu tun haben wir  uns entschlossen  Undercover
fortzusetzen. Meine  Drohung  in Mag 4 ist also doch nicht fruchtlos geblieben?
Wir hatten  noch nie so viele  Mitschreiber wie dieses Mal und  von  daher w„re
es nicht recht, Undercover nun  trotzdem einzustellen. Zudem  hat die Aktion in
der ST-Computer gezeigt, da schon Interesse an einem derartigen Medium besteht
auch wenn die Resonanz nicht sooo berw„ltigend war.
Quasi als Dankesch”n  werden  wir unser bestes tun, um Undercover an der Spitze
zu halten, indem wir es  technisch weiterhin  verbessern und mit noch mehr Fea-
tures ausstatten  und noch  besser  durchdesignen. Lat  euch also berraschen!
Im September ist wieder Undercover-Time!

                                 Bis denn...

Uups, bevor ich es vergesse. Ich gebe euch hiermit noch  schnell einen Ausblick
auf Undercover 6...
Hm. Wir werden sicherlich viel Software fr den Falcon  vorstellen k”nnen, ins-
besondere die Competition-Demos von der Fried Bits 3.
Desweiteren  werden wir  schauen, ob die 12 angekndigten  Games fr den Falcon
nicht nur leere Versprechungen waren  und mit etwas  Glck k”nnt ihr die ersten
Reviews im n„chsten Mag finden.
Ebenso werden wir uns um den  ST und STE kmmern. Zuerst schauen  wir natrlich
ob die  angekndigten Demos schon zur Hand sind und  die werden  natrlich hier
vorgestellt. Desweiteren  gucken wir uns  auf dem Games-Sektor um, denn  einige
Sachen sind ja angekndigt, die wir uns auf keinen Fall entgehen lassen werden.
Zu guter letzt  werde ich, angestachelt durch einen Bericht in  einer alten ASM
einen Exkurs in die Geschichte der Disk-Mags auf dem ST und Falcon starten...
Natrlich k”nnt ihr  wieder jede Menge anderen Stuff in  unserem Mag finden und
wir garantieren  euch wieder  viele unterhaltsame  Stunden... Doch  nun kmmert
euch erstmal um dieses hier...
                                     Viel Spa beim lesen!
 
                   šbrigens, diesmal verbuchen wir einen neuen Rekord!
 
                            Ihr k”nnt etwa 1 MB Texte durchforsten!

Auch wenn wir es diesmal wieder nicht geschafft  haben, das Mag zum angegebenen
Zeitpunkt (Fried Bits 3 - Ostermontag) raus zubringen (Mag war fertig, aber wir
hatten kein Intro zur Hand), hoffen wir, da ihr es trotzdem gut findet...
 
-------------------------------------------------------------------------------
                                                      Moondog of tnb / UC-Redax
-------------------------------------------------------------------------------

PS. Naja, eigentlich geh”rt das nicht  hierher, aber  ich wute  halt nicht, wo
    ich das noch h„tte einfgen k”nnen... Eine kleine schnelle Bedienungsanlei-
    tung fr UC-Neulinge:
 
    Die beiden Buttons  unten im Bild  stehen fr Musix (MSX) und Grafix (GFX),
    die ihr zum einen als Backgroundbeschallung nutzen k”nnt, oder aber schnell
    mal anschauen k”nnt.
    Durch das Anklicken  der šberschrift  einer aufgeklappten  Rubrik k”nnt ihr
    eine Rubriken-Info abfragen, die einige wissenswerte Dinge enth„lt.
    Im Textviewer gibt es diesmal einige Neuerungen.
    Wir haben die Druckoption wieder drin (natrlich ber Interrupt...).
    Ihr k”nnt, falls ihr  einen Text am  Wickel habt und euch die Mukke auf den
    Geist geht, direkt im Viewer eine andere Musik ausw„hlen.
    Solltet ihr weie  Schrift auf schwarzem  Grund bevorzugen, so mt ihr nur
    den Color-Button drcken und siehe da...
 
    Alles klar? Na denn mal los!
 
                                        Greetz, Moondog of tnb
 
ges