 
                                   Crap-Mix
                                 ============
                      ...a bunch of unnecessary nonsense.

 
                          Abteilung: FRAUENFEINDLICH!
                          ---------------------------
                      (EPK aufgepasst - wacht mal auf!!!)
 
===============================================================================
Der Richter zum Angeklagten  : "Was dachten Sie sich als Sie der Kl„gerin unter
                               den Rock faten?"

Angeklagter                  : "Ich dachte, mir frit ein Pferd aus der Hand".
===============================================================================
Was kann eine Frau, die die Treppe 'runterf„llt?
-Ein Bier mitbringen.
===============================================================================
Was schreibt man auf auf den Grabstein einer alten Jungfer?
-Unge”ffnet zurck.
===============================================================================
Was ist das Beste an der Muttermilch?
-Die Verpackung.
===============================================================================
Warum klopfen rzte den Neugeborenen auf den Arsch?
-Den dummen f„llt der Schwanz ab.
===============================================================================
Was ist die Steigerung von Frauenpower?
-Rinderwahnsinn.
===============================================================================
Warum ist ein Bier besser als 'ne Frau?
-Ein Bier schmeckt den ganzen Monat gleich.
===============================================================================
Warum haben Frauen unten 2 L”cher?
-Damit man sie wie ein Sixpack tragen kann.
===============================================================================
Was ist der Unterschied zwischen Uncle Ben's Reis (TM) und einem weiblichen Or-
gasmus?
-Uncle Ben's Reis (TM) gelingt immer.
===============================================================================
Wie findet man bei einer Frau im Dunkeln den Nabel?
-Mit dem Zeigefinger das Rckrat herabfahren, beim dritten Einrasten...
===============================================================================
Warum tragen viele Frauen Leggins?
-Damit man ihnen jeden Wunsch von den Lippen ablesen kann.
===============================================================================
Was haben Frauen und Schrotflinten gemeinsam?
-Man kann beide in der Mitte knicken und von hinten durchladen.
===============================================================================
Zum Schlu noch einen M„nnerfeindlichen als Ausgleich:
Warum haben manche Frauen blaue Flecken am Bauchnabel?
Auch blonde M„nner sind dumm.
===============================================================================
Was haben Frauen und Kettensaegen gemeinsam ?
Wenn man abrutscht, ist man im Arsch.
===============================================================================
Sitzt ein Mann  und eine Frau in der Sauna. Sagt er zu ihr:" Man, wat haben Sie
fr  einen  breiten Arsch." Die Frau daraufhin: " Sie Flegel!" und verl„sst wut
entbrannt die Sauna. N„chsten  Mittwoch, gleiche Situation. Er denkt sich, viel
leicht warst du  ja doch ein  bichen zu direkt- will  die Situation bereinigen
und sagt: "Also Sie haben ja doch eine hbsche Figur." Sie  entgegnet, sich die
Haare nach hinten  streichend. "Ja, das sagen viele - aber ich  meine ich h„tte
eine  zu kleine Brust." Er erwidert: "Wissen, was Sie da  machen mssen? Nehmen
Sie etwas Klopapier und streichen sich damit zwischen den Brsten."
Sie: ".. und das hilft?".
Darauf er: " Ja, sicher gucken Sie sich doch mal Ihren Hintern an."
===============================================================================


                               Abteilung: Versaut!
                               -------------------

===============================================================================
Kommt ein Mann in die Synagoge und sieht einen Teller mit Calamarisringen.Nach-
dem er angefangen hat die K”stlichkeiten in sich hineinzustopfen,fragt der Rab-
bi, was er denn da machen wrde: -"mhhh...ich esse diese leckeren Calamarisrin-
ge hier". Darauf der Rabbi: "Ha,das sind aber keine Calamarisringe, gestern war
Beschneidung!"
===============================================================================
Drei Freunde gehen im Wald spazieren. Einer hat eine geile Idee und sagt: "Hey,
wir machen jetzt was, was ich hier schon ”fters gemacht habe".
Er zieht sich nackt aus, gr„bt sich im Laub ein, und l„sst nur seinen Schniedel
herausragen. Die  Anderen nehmen hinter einem Baum Deckung und beobachten. Kurz
darauf kommt fr”hlich eine Nonne pilzesammelnd vorbei:
"Hier ein Pilzchen, da ein Pilzchen, tralala, dort ein Pilzchen, tralala, hier,
hier...ach nein, DAS geht nicht".
Sie geht weiter ihres Weges.Er geht zu seinen Freunden und schw„rmt,wie toll es
war, er berredet einen der Freunde, es auch mal zu probieren.Gesagt, getan, er
zieht sich aus, gr„bt sich im Laub ein und Schw„nzchen in die H”h. Nach einiger
Zeit kommt fr”hlich singend eine weitere Nonne pilzesammelnd vorbei:
Hier ein Pilzchen, tralala, da ein Pilzchen, tralala, hier...hier...ach nein...
DAS geht nicht".
Sie zieht ebenfalls weiter. Auch dieser Freund ist begeistert  und nun soll der
dritte berzeugt werden, der sich noch ziert, aber doch  nachgibt. Selbe Proze-
dur. Ausziehen, eingraben, Nudel guckt 'raus. Kurz  darauf kommt wiederum fr”h-
lich singend (allerdings mit tiefer Stimme) eine Nonne pilzesammelnd vorbei:
"Hier ein Pilzchen, tralala, da ein Pilzchen, tralala, hier....hier....HIER EIN
PILZCHEN...tralalaaa".
===============================================================================
Was hat ein Gyn„kologe und ein Hund gemeinsam??
Eine feuchte Nase!!
===============================================================================
Eines Tages kndigt die K”chin, die jahrelang im Haus war  und fast zur Familie
geh”rte. Die Hausfrau fragt sie, weshalb. Die K”chin sagt:
"Weil ich heiraten will!"
"So?" fragt die Hausfrau, "glauben Sie denn, dass Sie es dann sch”ner haben als
 bei uns?"
"Das nicht, aber - ”fter!"
===============================================================================
Zwei Leute bei der Arbeit:
Der eine   : "Meine Frau ist in der Liebe genauso langweilig wie meine Sekret„-
             rin."
Der andere : "Ja, das stimmt..."
===============================================================================
Gemeinsamkeiten eines Bungee-Sprungs und eines Puffbesuchs?

Kostet ungef„hr  gleich viel, der  H”hepunkt dauert  nur ein paar  Sekunden und
wenn das Gummi reit, geht man in beiden F„llen drauf.
===============================================================================
Hugo geht  zu einer Zeitung um eine Kontaktanzeige aufzugeben. Als er Am Schal-
ter steht, fragt in die junge Dame wie sie ihm helfen k”nne.
'Ich will eine  Frau, sch”n soll sie sein, eine tolle Figur,  eine sch”ne Figur
 soll sie haben und ...'
'Moment' unterbricht ihn die junge Dame 'ersteinmal wie soll sie den sein, ein-
 oder zweispaltig? '
'Was so was gibts auch...'
===============================================================================
Trifft ein Lokomotivfuehrer einen Kumpel. Die beiden unterhalten sich. Nach ei-
ner  Weile sagt  der Lok-Fhrer: 'Boah ey, mir is' letzte  Woche ein  Ding pas-
siert, ey'. 'Wat denn ?' fragt sein Kumpel.
'Naja, ich tucker da so jemtlich  mit meiner Lok durch die Gegend und auf ein-
 mal liegt da ein nacktes M„del auf den Gleisen...'.
'Und dann ?'
'Na, ich hab' sofort  gebremst, bin raus  ausser Lok und hab sie genommen - von
 vorne, von hinten .... echt goil!'.
'Haste Dir auch einen blasen lassen ??'.
'Nee, dat ging nich, ich hab den Kopf nich mehr gefunden!'.
===============================================================================
Zwei total  ausgehungerte  M„nner kriechen schon seit Tagen durch den Wald, bis
sie pl”tzlich an ein kleines sehr altes Haus kommen.
Pl”tzlich steht  eine sehr alte, „uerst  h„liche Frau in der Tre und sagt zu
den Beiden: "Wer mich befriedigt bekommt ausreichend und gut zu essen."
Der Erste denkt "Lieber sterbe ich vor Hunger, bevor ichs dem alten Monster be-
sorgen muss".
Der Zweite dagegen "Naja bevor  ich verhungern mu, bei ich halt in den sauren
Apfel" und steckt sich noch vorsichtshalber einen abgenagten Maiskolben ein.
Im Schlafzimmer  angekommen entkleiden  sich beide  aus und die  Alte macht das
Licht aus.
Er holt den  Maiskolben raus und  befriedigt damit die Alte, bis sie genug hat.
Anschlieend wirft er das total  verschleimte Teil aus dem offenen Fenster. Als
er dann nach getaner Arbeit bei reichlichem Essen sitzt denkt er an seinen Kum-
pel,der immer noch im Freien hungern mute.
Er nimmt etwas zu  Essen und geht nach drauen, um es seinem Kumpel zu bringen.
Dieser sitzt aber bereits auf dem Boden  und wischt sich  den Mund ab. Sagt der
eine zu ihm "Ich hab dir was zu essen gebracht"
Darauf der andere "Danke, ist nicht  mehr n”tig. Vorhin kam  ein Maiskolben aus
dem Fenster geflogen mit sooooo dick Butter drauf..."
===============================================================================
Kommt ein Mann zu Backer: "Ich h„tte gerne drei Laib Brot!"
VerkauferIn: "Um Himmelswillen, davon wird ihnen ja die H„lfte hart!"
Mann:        "Oh, da geben sie mir lieber sechs Brote."
===============================================================================


                              Abteilung: PC SUCKS!!!!
                              -----------------------

===============================================================================
Bei Microsoft wird ein Findelkind entdeckt!Die Gerchtekche brodelt.Sogar Bill
Gates wird als m”glicher Vater ins Spiel gebracht.Dies veranlasste Microsoft zu
einer offiziellen Stellungnahme: "Ein Microsoft-Mitarbeiter  kann unm”glich der
Vater des  Kindes sein. Erstens: Bei MS wird NICHTS mit Lust und Liebe gemacht.
Zweitens: Bei MS wurde noch nie innerhalb  von neun Monaten etwas fertig. Drit-
tens:Bei MS ist noch nie etwas entstanden,was von Anfang an Hand und Fu hatte.
===============================================================================
Betriebsausflug bei Microsoft. Ziel: Irland. Nach einer Besichtigung der Ferti-
gungsst„tte fr die europ„ischen Handbcher unternehmen Bill Gates und die Ent-
wickler fr Windows NT mit dem Jeep (TM) eine  ausgedehnte Spazierfahrt. In ei-
ner Ebene versperrt eine Schafherde den Weg. Man  kommt mit dem Sch„fer ins Ge-
spr„ch. Hungrig geworden, bietet Gates ihm eine Wette an: Wenn er den Beruf des
Sch„fers errate (!!!!) msse er dem Team einen Lammbraten spendieren. Falls der
Sch„fer dann den Beruf der Reisenden errate, erhielte er den Wagen. Der Sch„fer
nimmt die Wette an.Bill Gates tippt auf Sch„fer,der Lammbraten wird zubereitet.
In der zweiten Runde ist der Sch„fer dran, und er tippt auf NT-Programmierer(!)
Total verblfft rckt Gates den Wagenschlssel heraus und fragt den Sch„fer,wie
um himmels Willen er denn habe richtig raten k”nnen. "Ganz einfach" erkl„rt der
Sch„fer, "Nur NT-Programmierer bringen es fertig, sich aus der ganzen Herde als
Lammbraten den Hund auszusuchen".
===============================================================================
Der Stolz der OS/2-User: "Mein Frosch kann WARP sagen".
===============================================================================
Wieviele Leute braucht man bei Intel, um eine Glhbirne zu wechseln?
-0,99999998546.
===============================================================================
Und bei Microsoft?
-Keine! Man definiert Dunkelheit als Industriestandard.
===============================================================================
Was soll der K„ufer unter dem Siegel "Intel Inside" verstehen?
-WARNSCHILD!!!
===============================================================================
INTEL! Fast 300 korrekte Instruktionen, hier fliet das Komma!
===============================================================================
DOSen? Klar! Immer in den gelben Wertstoffack damit!!!
===============================================================================
PC-Dialoge:   Found DOS! Delete?  (Y)es, (O)ui, (S)i, (J)a?
              Mouse not found! Click to continue.
              Windows Error 4262: User felt asleep while waiting!
===============================================================================
Warum heit die neue Windows-Version "Windows 95"?
-Der Liefertermin wurde schon 95 mal verschoben.
-„„„h, nee...Berichtigung...95 ist die Zahl der Diskwechsel beim installieren.
===============================================================================
Bonn.
 
Am gestrigen Tage  fand eine erneute  Zusammenkunft der  EG-Gesundheitsminister
statt. Es ging  darum Warnhinweise, wie  sie seit  langem schon auf Zigaretten-
schachteln  vorhanden  sein mssen, auch  auf andere Produkte  auszudehnen. Als
Vorbild wurde dabei ein amerikanischer Computerchip-Produzent genannt, der sei-
ne Produkte schon seit l„ngerem freiwillig mit  der Warnung "Intel inside" ver-
sieht.
===============================================================================
"Indem Sie die  Druckformatvorlage des Dokuments mit der Druckformatvorlage der
Dokumentvorlage verbinden, k”nnen  Sie die Druckformatvorlage  der Dokumentvor-
lage  aktualisieren. Wenn  Sie die  Druckformatvorlage  eines Dokuments mit der
Druckformatvorlage einer Dokumentvorlage verbinden, ersetzen die Druckformatde-
finitionen  des Dokuments  die gleichnamigen  Druckformatdefinitionen der Doku-
mentvorlage. S„mtliche  Druckformate in  der Druckformatvorlage  des Dokuments,
die nicht in der  Druckformatvorlage der Dokumentvorlage enthalten sind, werden
dieser hinzugefgt."
 
"Auszug aus dem "Benutzerhandbuch fr Microsoft Winword 3.1"
===============================================================================

 
                         Abteilung: Compjuta alljemein
                         -----------------------------

===============================================================================

Ein Dialog zum Thema "Kuenstliche Intelligenz"
----------------------------------------------
 
Computer: "Hotel International, guten Tag. Womit kann ich Ihnen dienen?"
Anrufer:  "Ja, aem, ich wollte wissen, ob Sie ein Doppelzimmer mit Bad haben."
Computer: "ja, wir haben 120 Doppelzimmer mit Bad."
Anrufer:  "Was, alle frei?"
Computer: "Nach freien Zimmern haben sie nicht gefragt."
Anrufer:  "Also, wieviele haben sie frei?"
Computer: "Heute haben wir nichts frei."
Anrufer:  "Ich komme ja auch erst bermorgen, nur eine Nacht."
Computer: "Ach so. šbermorgen haben wir noch fnf frei. Sie m”chten eins dieser
           herrlichen, preiswerten Zimmer, nicht wahr?  Bitte buchstabieren Sie
           Ihren Namen."
Anrufer:  "Em. š. El. El. E. Er."
Computer: "Danke, Herr Em el Eller. Ich best„tige  Ihre  Buchung: ein  ruhiges
           Doppelzimmer  mit Bad. šbermorgen  fr  eine  Nacht, zum  Preis  von
           450 DM. Wann bitte kommen Sie an?"
Anrufer:  "Das wei ich nicht... wo ist denn mein Flugschein?..."
Computer: "Das wei nur die Flugauskunft, ich verbinde."
Computer: "Flugauskunft, guten Tag."
Anrufer:  "...ach ja, hier. Flug LH 4523, wann kommt der?"
Computer: "Flug El Al 4523 ist nicht in der Datei."
Anrufer:  "Nicht El Al, El Ha, El Haaaaaaa, Haaaaaarghhh!"
Computer: "Zentralrechner  Bundesgesundheitsamt. Sie haben  behandlungsdrftige
           Erk„ltungssymptome. Zur weiteren Diagnose sagen sie bitte 'aahh'."
Anrufer:  "Aaaa. bin ich denn bescheuert? Ich wollte ein Zimmer buchen und kei-
           nen Arzt. Oh, h„tte ich doch blo noch einen guten alten Apple!"
Computer: (schweigt)
Anrufer:  "Hallo, sind Sie noch da?"
Computer: "Zentrallager. Entschuldigen  Sie  die  Verz”gerung. Ich  habe  einen
           Apple, Baujahr  1976  im 'Used Comp Shop', Castrop-Rauxel, zu  einem
           Preis von 1800 DM. M”chten Sie ihn haben?"
Anrufer:  "Nein. Vergi' es!
Computer: "Ihr Benutzercode erlaubt keine L”schung von Zentrallagerdaten."
Anrufer:  "Ich will ein Zimmer, Du Hirsch, Du damischer!!!"
Computer: "String  Recognition  Error  at Susra$('damischer'$$$Aswi42S): Syntax
           Check at 200DE Rec83749: Error Recovery in Progress. Please wait."
Anrufer:  "Herrje, verschwinde. Ich will zurck zum anderen Computer."
Computer: "Zentralrechner  Bundesgesundheitsamt. Zur  Beurteilung, ob  Sie  be-
           scheuert  sind, einige  Fragen zu  Ihrem  Gesundheitszustand. Gab es
           frher Probleme?"
Anrufer:  "Du verdammter $&#. Du kannst mich mal #$&%@."
Computer: "Achtung, Achtung, hier  spricht der  Polizeirechner. Ihnen wird eine
           Straftat nach Paragraph 1523StPO, Beleidigung zentraler Intelligenz-
           systeme, zur Last gelegt. Ihre  Personal-Chipkarte  wird eingezogen.
           Ich weise Sie auf Ihr Aussageverweigerungsrecht hin. Sie k”nnen aus-
           serdem einen Computer des Rechtsanwaltverbandes konsultieren."
Anrufer:  (bricht zusammen)
===============================================================================

Compu-Freaks erkennen
---------------------
 
Wie erkenne ich einen Computerfreak an seinem Verhalten?
 
Ein Leitfaden fr den ungebten Beobachter
 
Da w„re  als erstes der typische  Amiga-Besitzer: Nur er bringt es fertig, ber
70 KB Tondaten mit 300/300 Baud aus einer Mailbox zu saugen, damit sein selbst-
geschriebenes Terminalprogramm auch einen angemessenen CTRL-G Gong hat.
Einen Amigafreak kann man auch daran erkennen, da er seinen Rechner mit 1.5 MB
und 2 880 KB Floppys jetzt als "fr kleinere Assembler-Entwicklungen angemessen
ausgestattet" bezeichnet. Die Festplatte hat er natrlich schon fest eingeplant
("irgendwann im n„chsten Jahr"), selbstverst„ndlich "das 33MB Modell, damit ich
auch ein paar gr”ere Animationen erstellen kann."
 
Der 08/15-ST-Anwender  kann da  nicht ganz  mithalten, obwohl er in dieser Hin-
sicht, wie  auch  der IBM-Kunde, nicht  als ganz unschuldig  dargestellt werden
kann. ST-Freunde  zeichnen sich aber auch eher dadurch aus, da  sie mehr Text-
programme als Ballerspiele und mehr Terminalprogramme, Kalkulationen und Daten-
banken als Adventures haben.
 
IBM-Kunden sind - im Gegensatz zu den obengenannten beiden Freaks - sehr leicht
zu finden. Wenn sie nicht gerade zu Hause das 99%kompatible BIOS ihres Rechners
verfluchen, sind  sie bei  ihrem  ”rtlichen H„ndler, um  eine neue  Grafikkarte
("DER neue Standard") und auch gleich einen passenden Monitor zu erstehen. Die-
se Grafikkarte  hat denn  auch gleich  einen 80586 on Board  und der  paralelle
Druckerport ist gratis dabei ("funktional integriert").
 
Eine ganz spezielle Sorte von Kompatiblen sind die Schneider PC-K„ufer. Als be-
sonderes  Merkmal hat dieses seltsame V”lkchen entweder  eine verbrannte Frisur
("vielleicht sollte ich einen Rechner ohne Lfter doch nicht mit Manuals zudek-
ken") und/oder starke  Deformationen der rechten Hand ("NEU: jetzt auch fr an-
dere Rechner - die Schneider-Ergo-Maus").
 
Schneider CPC-Programmierer sind  dagegen nicht so h„ufig  beim Computerh„ndler
zu sehen. Der  typische CPC-Besitzer  ist n„mlich  pleite - er hat  gerade eine
Diskette gekauft.
 
Um aber noch einmal auf die IBM-Kompatiblen zurckzukommen: Hier  hebt sich aus
der Masse der Kompatibel-Konformen deutlich der individualistische Compaq Qunde
heraus. Sein Rechner  unterscheidet sich in Tastatur-und Geh„usedesign deutlich
von Industriestandards-Einerlei.
 
Die h„rtesten  von allen  sind jedoch, wie  k”nnte es anders sein, die Apple ][
Fanatiker. Sie sind auch am einfachsten von allen anderen Computerfreaks zu un-
terscheiden. Der  typische Apple ][ Fan ist  deutlich gekennzeichnet  durch die
Inschrift auf dem Stein 2 Meter ber ihm. Typischerweise ruht sein Computer ne-
ben ihm. In seiner  Umgebung liegen h„ufig auch  einige TRS-80 Enthusiasten und
„hnliche (PET 2001 usw.).
 
Genauso  gibt es den  Commodore 64 Besitzer nicht mehr  in der freien Wildbahn,
weder bei Reese noch bei Quelle ist er noch anzutreffen. Schuld daran ist unter
anderem die  Firma SUBLOGIC. Denn die Mehrzahl der C64er ist  beim Einladen des
bekannten Flight II Simulators (02:40 LOAD TIME) an Altersschw„che gestorben.
 
Den C128-K„ufer findet man dagegen h„ufig bei IBM-Besitzern. Dort kauft er dann
die alten CGA-Monitore, die dieser schon fast auf den Mll geworfen h„tte. Oder
er kopiert sich bei den CP/M-Knilchen (es soll noch immer welche geben!) einige
Programme  auf sein zugegebenermaen eigenwilliges Disketten-Format um, um sich
dann an  der gigantischen Arbeitsgeschwindigkeit des  mit 2 MHz betriebenen Z80
zu erg”tzen.
 
In diesem Zusammenhang  mu abschlieend dann nur noch der PLUS-4-Kunde erw„hnt
werden. Den  trifft man, wenn  man sich, die c't auf dem  Scho, eine Weile bei
Reese hinsetzt. Nach  einiger Zeit wird dann ein Mann/eine Frau auftauchen, die
ALDI-Tte noch unter dem  Arm, und den Verk„ufer  nach dem Spiel fr den PLUS-4
fragen. Dieser wird dann sichlich genervt entgegnen: "Welches Spiel  meinen Sie
denn? Es gibt zwei!"...
===============================================================================

 
                              Abteilung: SABOTAGE
                              -------------------

===============================================================================

Wie „rgere ich einen Sysop?
---------------------------
 
Am Besten zuerst  Boxen aussuchen, deren Sysops aus Volltrotteln oder Schulkin-
dern bestehen. Die eignen sich am Besten.
Dann Userantr„ge  stellen - einfach irgendwelche  Namen und Anschriften aus den
Telefonbchern heraussuchen, und sie als "Absender" angeben, mit  der h”flichen
Bitte, "um Eintragung".
Handelt es  sich um  eine  seri”se Box, kann  man damit den  Sysop zum Wahnsinn
treiben, da er  naturgem„ zurck ruft, und  sinnlos Zeit  und Geld fr falsche
Angaben investiert.
Ein k”stlicher Spa!
 
Handelt es sich um "Nullachtfuffzehn-Boxen", wird kein Rckruf erfolgen, und du
bist erfolgreich unter falschen Angaben eingetragener  User geworden. Aber dann
geht der Spass erst los!
Calle den Sysop bei m”glichst jedem Anruf. Stelle ihm Fragen, die  er unm”glich
beantworten  kann, zum  Beispiel: "Welches IC kann ich als Ersatz fuer das 3.IC
des Yakamicha-Computers verwenden?".
Der Sysop wird sich so vorkommen, wie er ist: strohdumm.
Da kommt Freude auf, das macht Laune!
 
Auch lustig ist es, Streitigkeiten  unter den  Usern anzuzetteln. Schreibe ein-
fach an einen User, der  dir durch seine forschen Texte  aufgefallen ist! Teile
ihm, "unter dem Siegel der  Verschwiegenheit", mit, da ein anderer User (nenne
den namentlich!) ihn beschimpft.
Du wirst erleben, binnen  krzester  Frist  ist der  sch”nste Streit  unter den
Usern ausgebrochen, den kein Sysop mehr schlichten kann.
Ein wirklich gelungener Gag!
 
Hilft alles nichts, gehts noch  gemeiner: Einfach  den St”rungsdienst  der Post
anrufen, und  schchtern  erkl„ren: "Hallo, wenn ich die Nummer yx anw„hle, er-
t”nt immer so ein seltsamer Pfeifton...".
Ergebnis: Die Box schliet  in Krze, da der Sysop lieben Besuch des Fernmelde-
amtes bekommt.
(Klappt leider nicht bei legalen Boxen...)
 
Zerst”re das Vertrauenverh„ltnis zwischen Usern  und dem Sysop! Schreibe in an-
deren Boxen User  aus deiner "Ziel-Box" an, teile  ihnen mit, da "unser Sysop"
ein paar "Gemeinheiten" ber andere  User verbreitet  hat (was  natrlich nicht
stimmt.)
Binnen  krzester Frist  sind s„mtliche  User „rgerlich  auf den  Sysop (v”llig
grundlos), der berhaupt nicht wei, weshalb man seine Box pl”tzlich meidet und
ihn nicht mehr mag.
 
Zwinge den  Sysop, pers”nlich  Stellung zu nehmen. Schreibe  politische Kommen-
tare, die hart an die Grenze des Zul„ssigen stoen.
Hast du Glck, und der Sysop ist nicht neutral, wird er entweder dich angreifen
oder deine Eintr„ge l”schen. Jetzt hast du einen Grund, dieser Box "Parteilich-
keit und Diktatur" vorzuwerfen.
(Klappt leider nicht in allen Boxen, der Sysop der "Chat Noir" zum Beispiel ist
in DIESEM Punkt mir berlegen...)
 
Mache dir einen  Spa damit, Files fr den C-64 in  die IBM-Rubrik  zu senden -
oder andere Files in falsche Rubriken. Der Sysop wird st„ndig damit besch„ftigt
sein, diesen Mll  zu l”schen, oder den  Usern Entschuldigungen anzubieten, da
bei ihm "solch eine Unordnung" herrscht. Ein prima Jux!
 
Trage dich  grunds„tzlich  in allen  m”glichen Boxen  unter mehreren  Namen ein
(Leider: klappt auch nur bei "unseri”sen" Boxen.)
P”bele grunds„tzlich  alle anderen User an, suche Streit, aber zuerst suche dir
Verbndete. Antworte auf "Hilfs-Schreiben", antworte Usern, die wegen irgendet-
was irgendeinen Rat brauchen. Diese User stehen dann in deiner Schuld, und wenn
du jetzt  den Sysop in  die Pfanne haust, kann  er es nicht wagen, dich zu "l”-
schen", da er dann auch bei den anderen Usern "unten durch" ist.
 
Schicke  anonym Kleinanzeigen  an diverse  Computerzeitschriften: "NEU! DIE XY-
BOX! NUMMER: .... JEDER USER ERHAELT 10 DISKETTEN GRATIS!"
Der Erfolg  ist verblffend: Eine  riesige Menge  leichtgl„ubiger  Idioten wird
dort anrufen, und  einige werden sicherlich gegen den Sysop  Anzeige erstatten,
weil sie anstatt  der 10 Disketten nur (verst„ndlicherweise) „rgerliche Kommen-
tare des Sysops zu h”ren bekommen. Zum Brllen komisch!
 
Viele Sysops sind anf„llig fr Schmeichelei und Schleimerei. Schreibe bei jeder
Gelegenheit in die ”ffentlichen Pinns, da du den Sysop "fr den cleversten und
tollsten Typen" h„lst.
šber kurz oder  lang wird der Sysop zur  Witzfigur, kein vernnftiger User wird
ihn mehr  ernst nehmen, und  denken, er h„tte  diese Schmeicheleien  selbst ge-
schrieben...
===============================================================================

Zehn Arten ein Terminal zu zerst”ren:
-------------------------------------
 
1. Kaffee, in  die Tastatur gegossen, vermasselt  erfolgreich  die Arbeit, aber
   statt Zucker  in den  Kaffee zu  tun, nimm  Salz, etwa  drei- bis fnfmal so
   viel, wie Du Zucker genommen h„ttest.
   Weit Du, Salzwasser ist n„mlich ein guter elektrischer Leiter  und auerdem
   zersetzend fr  die Leiterbahnen auf  der Platine. Es  wird die IC-Chips auf
   den Platinen kurzschlieen und alles durcheinanderbringen.
2. Wenn m”glich, nimm die Abdeckung vom Terminal. Dann versuche die Platine bei
   eingeschalteter Spannung herauszuziehen und dann wieder hineinzustecken. Das
   ist eine  sehr wirksame  Methode jedem Transistor und IC auf der Platine das
   Lebenslicht auszublasen. ICs und Transistoren k”nnen solche Behandlung nicht
   vertragen, und  sie werden immer draufgehen. (Ich bin sicher, ich hab's aus-
   probiert!)
   ACHTUNG! An der Bildr”hre liegt eine sehr hohe Spannung an, und wenn  Du sie
   berhrst, k”nntest  Du verdammt  schnell in die  ewigen Jagdgrnde eingehen.
   Vorsicht ist geboten.
3. Versuche die Stecker  der Verbindungskabel verkehrt herum reinzustecken. Das
   wird alles sch”n verdrehen.
4. Bring einen Nagelclip mit zur Arbeit und schneide ein paar Leiter im Verbin-
   dungskabel durch. Das wird endlose Probleme verursachen.
5. La' Broklammern, Heftklammern, Reibrettstifte, Schnipsel von Alufolie etc
   in die Lftungsschlitze  fallen. Wenn Du Glck hast, landen sie auf der Pla-
   tine und verursachen dort Kurzschlsse und andere h„liche Probleme.
6. Zigarettenrauch verursacht  Schwierigkeiten mit den Platinen. Er kondensiert
   und berzieht die Kontakte auf der gedruckten Schaltung, und dann werden sie
   nie wieder einen  Kontakt herstellen  wollen. Also blase soviel Rauch in das
   Terminal wie Du kannst.
7. Sei kreativ. Nimm' die ICs aus  der Fassung und steck sie falschherum wieder
   rein. Das wird ungeahnte Probleme und den Wartungstechniker zur Verzweiflung
   bringen.
8. Floppy-Disks sind  sehr empfindlich  gegenber  magnetischen Feldern. Einige
   Disketten tragen ihr Programmteil am „usseren Rand. Streich doch ein paarmal
   mit einem Magneten  kreuz und quer  darber. Das macht  das Leben fr Deinen
   Abteilungsleiter  und die anderen Vorgesetzten  aufregender, und  ein Magnet
   hinterl„t auch nicht so  deutliche Spuren wie ein  Kugelschreiber oder eine
   Broklammer, die zu sehr ins Auge fallen.
9. Auch eine  Tonkopfentmagnetisierdrossel, wie man sie in Tonbandgeraeten ver-
   wendet, kann  sehr effektive  Ergebnisse bei der Beseitigung l„stiger  Daten
   von der Diskette erzielen.
10.Bastel Dir einen  Kunststoffmagneten (dies ist das st„rkste Material) in ei-
   nen Ring, den Du am  Finger tragen kannst. Dort wird ihn keiner vermuten, es
   sei denn, Du ziehst Heftzwecken oder Broklammern von allen Tischen an. Hast
   Du dann eine  Diskette in  der Hand, streichle  sie ein  paar mal  sanft mit
   Deinem Ring...
===============================================================================
 

                            Abteilung: Mathematiker-Witze
                            -----------------------------
 
===============================================================================
Ein Fesselballon-Fahrer  kommt in eine Nebelbank und hat sich hoffnungslos ver-
irrt! Nachdem der  Nebel sich lichtet, sieht er, daá er sich ber einer UNI be-
findet. Er sieht einen Menschen mit Bleistift und Notizblock unter dem Arm.
Er fragt ihn : "Heeee, k”nnen Sie mir sagen wo ich mich befinde ?"
Der Typ nimmt  von dem einen Moment  auf den anderen seinen Bleistift und krit-
zelt eifrig auf  seinem Notizblock herum. Nach ungef„hr 3 und halb Minuten ant-
wortet er: "In einem Fesselballon!"
"Aha!", sagte der Ballonfahrer  und wuáte, daá er  es mit einem Mathematiker zu
tun haben muáte. Denn bezglich der Antwort eines Mathematikers weiá man:
Die Antwort l„át auf sich warten
Die Antwort ist pr„zize und unanfechtbar.
Die Antwort ist absolut nutzlos.
===============================================================================
Ein Arbeiter, ein Ingenieur  und ein Dipl. Mathematiker sollen eine Schafsherde
einz„unen...
 
Es sind beliebig viele Pfl”cke und sonstiges Zaunmaterial gegeben.
 
Der Arbeiter  f„ngt an und  z„unt die Schafe  so ein, wie sie gerade stehen. Er
l„uft jedem Schaf  nach und z„unt es  ein. Das Ergebnis ist ein hoher Verbrauch
an Zaunmaterial, Zeitaufwand und Platzvergeudung.
 
Der Ingenieur ist schlauer. Er stellt ein Wasser auf und wartet bis alle Schafe
zur "Tr„nke" gekommen waren und z„unt sie dort ein. Das Resultat ist ein gerin-
ger Zaun-, Zeit- und Platzaufwand.
 
Dies ist nicht zu schlagen; denkt IHR!
 
Der Mathematiker  nimmt seinen Bleistift  und sein Notizblock und kritzelt wild
drauf los. Nach  einiger Zeit  kommt er  zu einem  Ergebnis  und f„ngt  an sich
selbst mit drei Pfl”cken und Zaunmaterial einzuz„unen!
Er sagt : "ICH DEFINIERE : ICH BIN AUáERHALB!"
 
Man sieht wieder :
 
Die Antwort l„át auf sich warten
Die Antwort ist pr„zize und unanfechtbar.
Die Antwort ist absolut nutzlos.
===============================================================================
 

                              Abteilung: Logisch!
                              -------------------

===============================================================================
Schwimmt unser Kanzler wenn man ihn ins Meer wirft?
-Zuerst schon, weil er hohl ist. Nach einiger Zeit geht er aber doch unter,weil
 er nicht ganz dicht ist.
===============================================================================
Ameisen schleppen das 50fache Gewicht ihrer selbst. Was schlieen wir daraus?
-Da sie keine Gewerkschaft haben.
===============================================================================
Warum haben Fische keine Haare?
-Weil sie Schuppen haben.
Und warum haben sie Schuppen?
-Weil sie nicht wissen, was sie dagegen machen sollen.
===============================================================================
Morgengrauen, so nennt man das Grauen das uns bef„llt,wenn wir frh morgens zur
Arbeit mssen.
===============================================================================
Frage: Wieviele Einwohner hat die Hauptstadt Afghanistans?
-Eh...moment...mit oder ohne Russen?
===============================================================================
Beim Metzger:
A: Ich h„tte gern 40 Gramm Leberwurst. K”nnen Sie mir die nach Hause schicken?
B: Oh..Pech...tut mir leid - unser Tieflader ist gerade mit 'nem Brhwrfel un-
   terwegs.
===============================================================================
Ein Trabant f„hrt auf einen Tankstellenhof:
Der Fahrer steigt aus und geht zum Tankwart. "Isch h„dde gernn fr main Draban-
den zwey neuie Scheibnwischr".
Der Tankwart beguckt den Wagen und sagt: "Hm, joh, das iss'n faires Angebot".
===============================================================================
Spruch: Gemeinsam sind Bier stark!
===============================================================================
Spruch: When everything else fails, read the instructions.
===============================================================================
Spruch: Maik A. macht ein Wrstchen (ohne Pause lesen).
===============================================================================
Zur Nachbarin:
"Wir werden bald in einer sch”neren Gegend wohnen".
"Und wir in einer ruhigeren".
"Wieso, ziehen Sie denn auch um?".
"Nee, WIR bleiben".
===============================================================================
Sitzen 2 U-Boote im Keller und stricken Atomkraftwerke..
===============================================================================
Ein Mann im B„ckerladen : "Ich h„tte gerne 3 Br”tchen". Sagt der B„cker: "Warum
nehmen Sie nicht 4, dann haben Sie eins mehr". Sagt  eine  andere Kundin: "Oder
nehmen Sie nur 2! Dann haben Sie 40 Pfennig gespart, und k”nnen sich dafr noch
ein Br”tchen kaufen".
===============================================================================
Kommt ein Mann mit 'ner Katze  auf der Schulter inne Kneipe und bestellt 1 Bier
und 3 Frikadellen. Das Bier trinkt er langsam aus,und die Frikadellen frit die
Katze. Das geht 3, 4 Mal so. Da fragt der Wirt: "Hey, das gibt's doch nicht,die
Katze hat gerade die 12te Frikadelle gefressen,was ist denn das fr ein Viech?"
Der Mann antwortet:" Tjoh, also, ich bin da  so auf 'ner Parkbank gesessen, und
da kam 'ne sch”ne Fee vorbei und sagte ich h„tte 3 Wnsche frei. Tolle Sache...
mein erster Wunsch war ein Porsche. ZACK  hat's  gemacht, und der Porsche stand
neben mir. Mein 2ter Wunsch waren 5 Millionen. Wieder ZACK, und die 5 Mille la-
gen im Kofferraum. Ja, und mein dritter Wunsch war eine uners„ttliche Muschi...
Hmm...und seitdem laufe ich mit der ollen Katze auf'm Buckel 'rum..."
===============================================================================
Schwerer Zwischenfall im Sondermll-Depot. Die  Umweltschutz-Beh”rde ermittelt.
Zeuge Hansen wird vernommen: "Wie konnte das denn passieren?" Hansen: "Wir hat-
ten gerade  den Transporter  entladen. Da sagte Kollege Mller 'Komm, zur Feier
des Tages machen wir ein Fass auf!'"
===============================================================================
Gott und Jesus spielen Golf:
Gott  schl„gt, der Ball  fliegt weit  und landet im  Aus. Da schnappt sich eine
Maus  den Ball, eine Katze schnappt sich die Maus, ein Adler schanppt sich  die
Katze und  fliegt davon. Der  Adler l„át pl”tzlich  die Katze fallen, die Katze
die Maus, die Maus den Ball, der Ball fliegt und landet im Loch.
Da sagt Jesus: "Was soll das, Papa? Spielen wir Golf oder albern wir rum?"
===============================================================================
Es gab eine Verkehrsstockung, und der unvermeidliche Huper l„rmte, was das Zeug
hielt. Da beugte  sich eine junge  Dame neben ihm  aus dem Fenster ihres Wagens
und erkundigte sich teilnahmsvoll:
"Und was haben Sie sonst noch zu Weihnachten bekommen?"
===============================================================================
Die  Hausfrau  sagt zur  Hausgehilfin: "Minna, ich habe hier eine Klobrste ge-
kauft. Die h„ngen Sie sofort ins Klo!"
Nach  einiger  Zeit kommt  die Hausgehilfin  und sagt: "Gn„dige  Frau, die neue
Brste taugt aber nichts, die kratzt viel zu sehr! Papier w„re doch besser!"
===============================================================================
Gast: "Herr Ober, ich wollte eine  Serviette haben. Warum bringen sie  mir eine
       Rolle Klopapier ?"
Ober: "Fr den einen ist es eine Rolle  Klopapier, fr den anderen  die l„ngste
       Serviette der Welt."
Gast: "Endlich mal ein Ober mit Phantasie !"
===============================================================================
Geht die Coca Cola-Werbeagentur zum Papst.
Sie fragt ihn: "K”nnen sie den  Text 'Vater unser, unser t„gliches Brot gib uns
heute', nicht in 'Unsere t„gliche Coke gib uns heute' umwandeln?
Natrlich fr eine Million D-Mark."
Der Papst findet, daá eine Million zu wenig ist. Sie steigern  auf 10 Millionen
D-Mark.
Da ruft der Papst  seine erste Sekret„rin  und fragt: "Wie lange haben wir noch
den Vertrag mit der B„ckerinnung?"
===============================================================================
Physikprfung: Was ist schneller, Licht oder Schall?
1. Prfling: Das Licht, wenn ich das Radio anmache, kommt zuerst das Licht, und
   dann der Ton.
RAUSS!
2. Prfling: Schall, denn wenn  ich den Fernseher anmache, kommt zuerst der Ton
   und dann das Bild.
RAUSS!
Der Prfer entscheidet  sich dafr, alles  etwas einfacher zu machen, er stellt
die Frage anders: Sie stehen auf einen Berg und sehen jemanden Holz hacken. Zu-
erst SEHEN sie die Axt runterkommen, dann H™REN Sie BUMMM.
Warum???
3. Prfling: Vielleicht, weil die Augen weiter vorne als die Ohren sind?
===============================================================================
Verbinden Sie das Kopfphon zu Wagenwinde, um Musik zu genieáen.  [...]
Setzen Sie  das Stereo  Kopfphon in  Kopfphon Wagenwinde ein, die Macht ist an,
sonst die Macht ist ab.
(Aus der Gebrauchsanweisung fr ein Radio)
===============================================================================
Pfarrer und  Kellner spielen Tennis. Der Pfarrer hat Aufschlag, schl„gt daneben
und schreit: "Scheie, daneben !!!". Darauf der Kellner: "Na, Na, Na Herr Pfar-
rer!!! Ein Mann Gottes sollte nicht solche schmutzigen W”rter benutzen."
Der Pfarrer  entschuldigt sich  und beide spielen weiter. Eine Weile sp„ter hat
der Pfarrer wieder Aufschlag und schl„gt wieder daneben.
Er schreit wieder: "Scheie daneben!!!". Meint der Kellner: "Also Herr Pfarrer!
Beim n„chsten Mal wird sie Gott aber bestimmt verfluchen". Wie dem auch sei die
beiden spielen weiter und der Pfarrer  hat wieder Aufschlag. Er  schl„gt wieder
daneben und schreit wieder: "Scheie, daneben!!!".
Pl”tzlich braut sich ber den beiden ein Unwetter zusammen. Ein Blitz zuckt vom
Himmel und erschl„gt den Kellner ...
Von oben her ert”nt eine Stimme: "Scheie, daneben!!!" ...
===============================================================================
 

                                 Abteilung: Story!
                                 -----------------

===============================================================================
Frage: Wenn ich mir einer gaaanz genauen und empfindlichen Waage eine Festplat-
       te wiege, sagen wir mal 2 GB, und diese dann  vollschreibe, was passiert
       dann? Ver„ndert sich das Gewicht der HD oder bleibt's gleich???

Natrlich wird die Pladde durch die vielen Molekle der Elektronen schwerer.Was
noch wichtig ist: Unbedingt fr eine homogene Verteilung der Daten sorgen! Denn
wenn sie nicht homogen verteilt wurden,bekommt die HD eine Unwucht,die das Ach-
senlager mit der Zeit ausleiert. Zwar ist das Gewicht der Daten sehr gering,die
Wirkung darf man allerdings nicht untersch„tzen,da sehr moderne Pladden mit ca.
6000 Upm laufen! Die Zentrifugalkraft sorgt  dafr, da selbst kleine Unwuchten
groe Sch„den anrichten. Wegen der Datenunwuchten  machen viele  „ltere Platten
mit ausgeleierten Lagern auch so sirrende Ger„usche. Was schafft Abhilfe??? Ein
Programm,da A) in frei justierbaren Zeitabst„nden die Daten homogen auf der HD
                verteilt, und
             B) bei gr”eren Kopiervorg„ngen dann ein Warnfenster zeigt (optio-
                nal wird auch ein 20KHz MOD-Replay untersttzt) wenn  die Daten
                eine Unwucht hervorrufen k”nnten.

Da die Entwicklung in C geschieht, wird das Programm schnell fr fast alle Sys-
teme - inkl. dem PC - verfgbar sein.
===============================================================================


                         Abteilung: Huh...makaber!
                         -------------------------

===============================================================================
Was ist klein, rot, silbern und rennt dauernd schreiend gegen die Wand?
-Ein Baby mit Gabeln in den Augen. (Anm.v.VISOR: Hi ORK!!! ;-))
===============================================================================
Was ist fieser als ein totes Baby in einem Eimer?
-Ein totes Baby in zwei Eimern.
===============================================================================
Was macht ein Leprakranker am Strand?
-Er liegt auf der faulen Haut.
===============================================================================
Was macht ein leprakranker Raver auf dem Dancefloor?
-Er tanzt, bis die Fetzen fliegen.
===============================================================================
Was ist der Unterschied zwischen einem Totenhemd zu DM 80 und einem zu DM 120?
-Das zu DM 120 ist bgelfrei!
===============================================================================
Was hat 4 Beine und einen Arm und steht auf der grnen Wiese?
- Ein Dobermann auf dem Kinderspielplatz!
===============================================================================
Eine Frau kommt zur Entbindung ins Krankenhaus. Nachdem sie entbunden hat, will
man ihr das Kind nicht zeigen. Die rzte lassen sich letztendlich doch erwei-
chen und bringen eine Schssel mit einer roten Soe, auf der 2 Augen schwinnen,
herein. Die Frau schaut rein und sagt: "Es hat mich angeschaut!"
Darauf der Arzt: "Geht nicht, es ist blind..."
===============================================================================
Ein Fernsehteam  besucht ein  Altersheim um einen Bericht  ber den Tagesablauf
der dort lebenden Menschen zu drehen.
Beim alten Willi Schnedermann treffen sie auf einen vielversprechenden Kandida-
ten. Die Redakteurin l„át ihr Team aufbauen und beginnt das Interview:
R: Also Herr Schnedermann, wenn Sie morgens aufwachen, was machen sie denn dann
   als Erstes?
S: Wenn ich morgens aufwache. Als Erstes pisse ich.
R: Schnitt, schnitt. Herr Schnedermann, so geht  das nicht, sagen sie doch lie-
   ber 'ich lasse Wasser'. Nochmal  von vorn. Kamera ab, ton ab. Herr Schneder-
   mann, wenn die morgens aufwachen, was machen sie denn dann als Erstes?
S: Wenn ich morgens aufwache. Als erstes... lass ich Wasser.
R: Und dann?
S: Dann scheiá ich.
R: Schnitt, schnitt. Licht aus. Also Herr Schnedermann, so ist das ja peinlich,
   das k”nnen sie  so nicht sagen. Sagen sie doch lieber 'ich mache Stuhlgang'.
S: Ist gut.
R: Kamera ab, los geht's. Herr  Schnedermann, wenn  die morgens  aufwachen, was
   machen sie denn dann als Erstes?
S: Wenn ich  morgens aufwache. Als erstes ... lasse ich Wasser. Und  dann mache
   ich Stuhlgang.
R: Aha, und dann?
S: Dann stehe ich auf.
===============================================================================
Was ist ein Lepra-Kranker im Windkanal?
Eine Pusteblume...
===============================================================================
Zwei rzte beim Golf. Am neunten Loch bricht einer von ihnen zusammen - Herzan-
fall.
"Hilf mir!" st”hnt er.
"Tut mir  schrecklich leid", sagt der andere, "meine Versicherung gegen „rztli-
 che Kunstfehler deckt leider nur F„lle ab, die ich in meiner Praxis behandele.
 Aber ich hole Hilfe."
Nach fnf Minuten kehrt der Mediziner zurck und spiele seelenruhig weiter.
"Also  sag' mal, ich  lieg' hier  im Sterben, und  du  versuchst  einzulochen?"
 r”chelt sein Kollege.
"Keine Bange. Ich  habe am zweiten Loch  einen Ambulanzarzt fr Dich aufgetrie-
 ben."
"Am... zweiten Loch? Und wann... wird er... hier sein?"
"Ich habe doch gesagt, es ist  alles in Ordnung. Die anderen haben versprochen,
 ihn zgig durchspielen zu lassen."
===============================================================================

                            Various Artists
 
-------------------------------------------------------------------------------
                                            selected by VISOR and Drizzt of tnb
-------------------------------------------------------------------------------


   