                                 KLEINKRAM
                                =---------=
 
Oh Leute! Es sieht trÅbe aus in ST-Demo-Land! Ich habe aus Ermangelung an neuem
Stuff, in diesem Mag extra kleinere neuere und Ñltere Sachen, die man normaler-
weise wohl kaum vorstellen wÅrde, in  diesem Artikel hier zusammengefaût, da es
nicht gut  kommen wÅrde, fÅr  all diese kleinen Dinge hier extra  einen Artikel
anzureiûen, ich  aber somit wenigstens  noch ein  biûchen Zeug  hier vorstellen
kann und die Rubrik nicht gleich streichen muû...

-------------------------------------------------------------------------------

                               THE T2 VIDI SHOW
                               ----------------

Crew  : Effect
Art   : Digidemo
Disx  : 1

Dieses kleines Demo  habe ich auf  der "Industrially Save Demo Disk 6" (was fÅr
ein Name...) von eben der selben Crew aufgetan.
Was ist es? Nunja, es gibt ein nettes Intro mit einem hÅbschen Effect-Logo, dem
Creditz-Scroller  und  einer, ich glaube  Lotus, Chip-Mugge, die  schon aus dem
Mainmenu der Anomaly-Megademo von MJJ bekannt ist.
Danach folgt, wie sollte es  anders sein, eine kurze  Digi-Sequenz aus dem Film
Terminator 2. Der  Bildausschnitt ist klein, die  Digi-Sequenz ist nicht durch-
gehend (da fehlen Teile...), der Samplesound ist auch nicht  so steil und Åber-
haupt. Bislang hatte ich  ja gedacht, die  Zeit dieser  Digidemos  wÑre vorbei,
aber inzwischen freut man sich ja Åber jeden Ferz ST-Demo, den man kriegen kann
(auch wenn's simple Sachen sind).

-------------------------------------------------------------------------------

                                    TRISOMY RULES
                                    -------------
 
Crew   : Positivity
Art    : Screen

Naja, hier haben wir schon ein eigentlich nicht vorstellenswÅrdiges Demo. Alles
in diesem  Screen dreht  sich um einen  Effekt, geshadete  Sprites. Dazu gibt's
viel Text und ein  zappelndes  Positivity-Logo... Das wars. Sound gibt's nicht,
dafÅr kann man laut Aussage des Coder, Musik Åber irgendeinen Background-Player
abspielen, da das Demo Gem-kompatibel ist... aaargh...

-------------------------------------------------------------------------------

                             ANTICHRIST CHIPSOUND DEMO
                             -------------------------
 
Crew   : Sector One & DNT Crew
Art    : Sounddemo

Nicht ganz so mickerig ist dieses Teil hier. Antichrist ist der ziemlich fÑhige
Musiker von Sector One, der  hier 19 verschiedene  Megatizer-Musiken zum besten
gibt. Mit dabei sind natÅrlich auch  die Songs aus  dem "Oh No! More Froggies"-
Demo. Die meisten Sounds sind allerdings nur Durchschnitt. UnterstÅtzt wird die
ganze Chose mit einem netten Logo und Sound-Analyzern... Det woar's...

-------------------------------------------------------------------------------

                                   AIR WALK
                                   --------
 
by Genial G. / Canabis

Da ich dieses Demo hier nicht verreiûen will, verzichte  ich darauf, es genauer
vorzustellen. Der Macher  hinter dem Projekt ist  im CF zu finden. Das Demo ist
in Omikron-Basic gecodet und derart nehmen sich auch die "Effekte" aus. Es gibt
ein paar Sprites, raster und Scroller sowie eine Animation. Die Grafik ist ganz
nett (das eine Pic mit dem enthaupteten  Rapper gefÑllt  mir... :-). Sound gibt
es nicht... Mehr is' nich'... Die Leute wollen Åbrigens auf dem PC Demos machen
(Brechreiz... der ST hÑtte es nîtiger...)...

-------------------------------------------------------------------------------
                                                                 Moondog of tnb
-------------------------------------------------------------------------------
   