 
                                  LYNX-NEWS
                                 =---------=

Tja, auch um Atari's "Kleinen" ist es seit  der EinfÅhrung des Jaguars ziemlich
ruhig geworden. Da diese Konsole sich nie richtig  durchsetzen konnte, wird sie
wohl schon bald tief in der Versenkung  verschwunden sein, allen  Lorbeeren zum
trotz, schade drum. öbrigens gibt's beim  deutschen Jaguar-Distributor PAGEDOWN
jede Menge Lynx-Games zu  Ramschpreisen von 25 DM je  StÅck. Zwar  iss'es nicht
das neueste Zeug, aber immerhin... Und auch hier  muû ich mal wieder die regio-
nale Ecke beleuchten... Im SoftwarebÅro Heine in NMB gibt es auch wieder Lynx'e
zu kaufen, zum Preis von 139 DM und  Spiele um die 60 DM, naja, nicht unbedingt
die Dumping-Preise aber immerhin, es steht wieder was mit  dem Aufdruck "ATARI"
in einem GeschÑft (dem fÅhrenden in NMB) herum...

Aaah! Ganz  so schlimm  ist es doch  nicht, wird doch von  einer Umsetzung  des
Super-Knallers "ALIENS VS PREDATORS" fÅr's Lynx gemunkelt... Aaaah! Na  da darf
man wohl krÑftig gespannt sein...


 de