                     *********** INTERVIEW *************
           *********** mit Mike of STAX im Februar '95 ************

Hi Mike!

Hier sind  einige Fragen, die sicherlich  auch unsere geneigte  Leserschaft in-
teressieren drften und ich f„nd's nett, wenn Du mir ein paar Info's dazu geben
k”nntest!


Mit was fr einem Rechner werkelst Du zur Zeit herum  und seit wann bist Du auf
Atari's t„tig? Wie bist Du zu Stax gekommen?

- Ich bin  derzeit auf ST, Falcon und PC t„tig. Szenem„ig  nur mit dem ST bzw.
  ab und zu Falcon. Den ST habe ich schon seit Mitte '87, wobei ich anfangs na-
  trlich nur gezockt habe....
  Vor STAX war  ich in meiner eigenen  one-man Gruppe aktiv. Dux of STAX kannte
  ich schon l„ngere Zeit. Als ich dann ein Main-Menu fr ein DemoMaker-Demo ab-
  lieferte , an dem  auch Dux beteiligt war, sprach mich DUX kurz vor Weihnach-
  ten '91 an, ob ich nicht STAX  beitreten wollte. Mit dem  Sylvester 91/92 re-
  leasten New-Year-Screen gab ich dann meinen Einstand bei STAX ....


Wieviele Leute sind  denn noch in STAX  aktiv? Im Interview, welches Bod in der
ST-Format gegeben hat, war von 9 Leuten die Rede...

- Derzeit  sind  folgende  Jungs  in  STAX : Matt, Dux, Mike, Tyan, Tarzan Boy,
  Pitcher, Bod und Sally aus England sowie Exterminator und Solo  aus Finnland.
  Somit sind  wir zehn  Leute. Leider  sieht es  mit der Aktivit„t etwas anders
  aus ... Auch bedingt durch teilweises splitting in Falcon/ST Lager.

 
Matt hatte mal gesagt, da Ihr  nach dem Auseinandergehen der United Forces nie
wieder in einen  Verbund gehen wrdet. Wie kommt Ihr "alleine" so zurecht? Darf
man fragen, wie Ihr so zu der Independent steht?

- Ja, das  stimmt. Wir gehen  in keine  Alliance mehr rein. Die INDEPENDENT hat
  sicher ihre Berechtigung. Wir  stehen dem etwas distanziert gegenber.
  Gerade auf dem  Falcon mssen die  letzten Freaks aber  schon zusammenhalten.
  Trotzdem, wir bleiben really independent ... und fahren auch gut damit.


Was habt Ihr noch so  an Projekten laufen? Bringt Ihr noch eure CD's raus, oder
habt Ihr die inzwischen, wie viele andere Gruppen, auch eingestellt?

- Matt beliefert  den CD-Markt immer  noch fleiig, wenn  er new stuff zusammen
  hat, was sicherlich einen wichtigen Beitrag zur doch etwas angeschlagenen ST-
  Szene darstellt. Auerdem hat der STAX-ltestenrat  beschlossen, da wir auch
  noch ein ST-Demo releasen wollen. Fr  den Falcon l„uft dann  noch unser Top-
  Secret-Projekt : Pyjama (hat wohl was mit Doom zu tun .....).
  Damit ist  eigentlich fast  alles abgedeckt - šberraschungen  sind  natrlich
  immer m”glich ...


Wie steht Ihr zum Falcon? Ihr  seid ja eine der  letzten Gruppen, die  noch auf
dem ST aktiv sind. Habt Ihr vor, auch auf den 030er zu wechseln  oder wollt Ihr
der alten Maschine auch weiterhin treu  bleiben? Seht Ihr noch eine Zukunft fr
den ST, oder seid Ihr inzwischen auch der Meinung, da der Rechner am Ende ist?

- Viele in unserer Gruppe haben einen Falcon. Offiziell sind wir nicht voll auf
  den 030er  umgestiegen. Das hat  verschiedene Grnde. Vielleicht haben wir da
  einfach was verschlafen. Ich selbst mag die Kiste eigentlich schon.
  Doch wir wollen auf jeden Fall noch  etwas fr den ST auf die  Beine stellen.
  Was danach kommt, wei ich nicht.
  Eine groe  Zukunft fr  den ST  gibt es  bestimmt nicht, das  ist eigentlich
  klar. Der Markt ist seit langem zusammengebrochen. Es ist eben ein Hobby noch
  auf der alten Maschine herumzuhacken - und solange noch ein paar Verrckte in
  der Szene herumgeistern macht es doch noch Spa.


Wenn Du den ST verlassen mtest und auch der Falcon tot w„re, auf welches Sys-
tem wrdest Du dann wechseln wollen?

- Wechseln wollen? Ich glaube, da man  heute doch gar keine Wahl mehr hat sich
  das System  auszusuchen. Der  PC hat alles  fest in der  Hand. Ich pers”nlich
  wrde mir wnschen, da die Power-PC-Architektur etwas mehr  Einflu gewinnt.
  Vielleicht hole ich mir mal so eine Kiste ...
  Ich sehe in diesem Zusammenhang noch eine andere Frage : Gibt es  abseits von
  Atari/Commodore noch unser  liebgewonnenes  Szene-Leben? So wie  es war, wird
  es nirgends mehr  sein. Vielleicht  ist  es  auch  nicht  mehr  gefragt? Weil
  unbekannt ...


Was h„ltst  Du ganz pers”nlich  vom Jaguar und Atari? Hoffst  Du noch auf einen
neuen Rechner von Atari oder glaubst Du, da der Zug abgefahren ist?

- Der Jaguar ist geil. Besonders Iron Soldier (preview) fand ich toll. Doch man
  hat hier bei ATARI viel  verschenkt bzw. verschlafen. Das Marketing von ATARI
  ist eine echte Katastrophe. Wie im Computermarkt hat man  es nicht geschafft,
  sein Produkt zu  platzieren, und sei es noch so berlegen wie der Jaguar. Und
  so schl„ft man vor  sich hin, bis einem  die Konkurrenz  wie Nintendo mit dem
  ULTRA 64 den Markt wegschnappt.
  Freilich hat  ATARI Erfolge  mit seinem  Jaguar  eingefahren, aber  gerade in
  Deutschland h„tte man die Konsole mehr pushen sollen.
  Fr den Jag hat man die Computerabteilung ja  str„flich vernachl„ssigt. Ob da
  noch was kommt, bezweifle ich schwer. Ob  Komplettsysteme  wie Amiga/ST heute
  berhaupt noch eine Chance haben, sei dahingestellt.
  Es scheint, der Zug ist wirklich abgefahren. Selbst den letzten Freaks bleibt
  ja nichts anderes brig, als das System  zu verlassen - bei dieser Unterstt-
  zung seitens ATARI ...


Wie sch„tzt Du denn den Untergang von Commodore ein?

- hnlich wie bei ATARI hat man zu viele Fehler gemacht und Entwicklungen nicht
  oder viel zu sp„t erkannt. Produktpolitische Katastrophen wie CDTV, Amiga 600
  oder der verzweifelte Versuch das CD32 zu etablieren, sprechen fr sich.
  Wer dann noch Maschinen verkaufen will mit 020er  Prozessoren mit 14Mhz, w„h-
  rend die Konkurrenz mit 486er Bolliden aufwartet, ist selber schuld. Man hat-
  te einen groen Markt mit treuen Amiga-Freaks, doch verschenkte alles .....
  Leider lassen sich bei dieser Geschichte viele Parallelen zu ATARI ziehen ...


Und nun die  letzte und wichtigste  Frage, wie  findest Du Undercover (schleim,
schleim :-)?

- Ich habe noch nicht  allzu viele Ausgaben Eueres  MAGS gesehen, finde es aber
  ganz gut. Ihr solltet Euch vielleicht bei der Main Menu - Gestaltung noch et-
  was mehr von der Konkurrenz abheben. Ansonsten kann  man froh sein, das sowas
  noch voller Elan fr den ST durchgezogen wird in diesen Zeiten.


Um diese Sache hier erstmal zum Abschlu  zu bringen, hast Du noch eine Message
fr unsere Leser?

- Ich m”chte mich bei denen  bedanken, die noch etwas  fr den ST auf die Beine
  stellen und ihre Kiste ab und zu noch einschalten.
 
                Michael.
  				     (Mike of STAX)
  				
Ok, thanx erstmal und einen Gru an alle anderen STAXer!

-------------------------------------------------------------------------------
                                  Mike wurde "ausgefragte" durch Moondog of tnb
-------------------------------------------------------------------------------





















 
e g