                            Erfahrungen mit MinT
                            --------------------

     (Dieser Text wird geschrieben, wÑhrend parallel der LHARC-Archiver
                      einige Dateien komprimiert.)
 
Es wunderte  mich, daû so gut  wie niemand  MinT benutzt,  obwohl dies doch der
einzige Gratis-Multitasking-Aufsatz fÅr den Atari ST ist. Meine  Version stammt
aus dem dahingeschiedenen  ST-FORMAT-Magazin  und ist wohl  auch nicht mehr ak-
tuell (0.95 b). Aber einem geschenkten Gaul schaut man ja bekanntlich nicht ins
Maul.
Als ich mit MinT anfing, verstand ich gar nicht, was man damit anfangen sollte:
Nur TOS-Progamme laufen parallel? TOS-Programme, jene  Relikte aus der Rechner-
steinzeit, wie sie auf den DOSen Standard waren, als unsereiner schon mit einer
benutzerfreundlichen OberflÑche verwîhnt wurde? Und dazu  jene  "Manuals",  die
von merkwÅrdigen Dingen wie Device-Laufwerken und Prozeû-IDs sprachen...
TatsÑchlich ist  das alles gar nicht so kompliziert. Eigentlich braucht man nur
MINT.PRG in  den AUTO-Ordner  und TOSWIN.ACC in das Wurzelverzeichnis zu packen
und  irgendwo (auf der HD) die  MINTSHEL.TTP  sowie  mîglichst  viele  TTPs  zu
lagern. Nach dem Booten aktiviert man TOSWIN und macht ein ALT_WINDOW auf.
Jetzt per Fileselektor die MINTSHELL aktivieren und los geht's.
Im Prinzip  jedenfalls. Wie immer kann man alles mîgliche und unmîgliche konfi-
gurieren  und einstellen, aber  das kann jeder selbst herausfinden. Das Problem
ist eher, daû es eigentlich nur wenige Dinge gibt, die man mit TTPs  bewÑltigen
kann. TTPs sind  nun mal so  unflexibel wie ein Backstein, daher fallen mir ei-
gentlich nur ein: Texte  in irgendeiner  Form manipulieren (formatieren, zusam-
menfÅgen etc.), wofÅr  es  reichlich  TTPs in der  LINGUIX-Sammlung gibt, Daten
archivieren (inzwischen ist  LHARC  fertig und hat die 3 Texte von ca. 1 MB auf
ca. 350 KB  reduziert, wobei  von H: auf  die  Ramdisk  geschrieben  wurde) und
selbstentpackende TOS-Dateien dekomprimieren. Das geht wirklich  prima: Erst in
der Shell den  Standardpfad  auf die  Zieldisk  setzen (z. B. "CD m:") und dann
das TOS-File starten.
Auûerdem  kann  man mit  MinT mal  ein wenig  in UNIX 'reinschnuppern, denn die
ganze MinT-Struktur samt Tastaturhackerei stammt nun mal da her.
Am Anfang  hatte mich  die Sache  mit dem  MinT-TTP "bg" etwas verwirrt. BG.TTP
verlegt  Prozesse  in den  Hintergrund. TatsÑchlich  braucht man BG nicht, wenn
man, wie  hier angegeben, "nur" ein TTP (LHARC) im  Fenster  sowie ein GEM-Pro-
gramm, nÑmlich den Editor, starten will (dazu natÅrlich  noch ACCs!). Dann kann
man zudem dem Fortschritt des Datenpackers zusehen.
Da man im Leben  nichts umsonst kriegt, bezahlt man auch fÅr den MinT-Gebrauch:
Und zwar mit Speicherplatz und vor allem mit Performance. Ein solchen Text ein-
tippen geht  noch auf einem hundsgewîhnlichen 8 MHz-ST, obwohl selbst meine be-
scheidenen TippkÅnste  schneller sind als der Cursor. Anspruchsvollere Arbeiten
sollte man lieber ohne Multitasking bewÑltigen. Zudem ist MinT ohne  Festplatte
und grîûeren Speicher wohl auch nicht mîglich bzw. anzuraten.
Die Sicherheit  von Multitaskingsystemen  ist ebenfalls ein eher dÅsteres Kapi-
tel, daher empfiehlt auch Eric Smith selbst, hÑufig Backups zu machen.

Alle Tips wie immer ohne GewÑhr.

-------------------------------------------------------------------------------
                                                                          Gnort
-------------------------------------------------------------------------------
--