                                SHAREWARE-GAMES
                                ---------------
 
Yo! Hier findet  ihr eine Reihe von  speziellen STE-Shareware-Games zusammenge-
fat, die ich hier rumliegen hatte und daher mal schnell mit angetestet habe.

                                                    Moondog of tnb / UC - Redax

-------------------------------------------------------------------------------

                               NO LIMIT 2 V. 1.07
                               ------------------
 
Hersteller  : / Deutschland
Genre       : Flipper
Spieler     : 1-4
System      : STE / Falcon, Color, 1 MB RAM, Festplatte empfehlenswert
Status      : Shareware
Preis       : 20 DM fr Registrierung, 5 DM fr Updates

Oh Leute! Auf  den Atari's  ist nun scheinbar  nach langem  neidvollem Hinber-
schauen zu den  mit Pinball-Games nur so eingedeckten Amiga-Besitzern, auch die
Flipper-Mania ausgebrochen. Nach  einigen  mehr oder minder verunglckten  Ver-
suchen, einige  Flipper fr den ST  herauszubringen  (siehe  Oldie-Rubrik), war
lange Zeit  so ziemliche Ruhe, bis der Knaller "Obsession" auf dem  STE und 030
die Userschaft  wieder  wachrttelte, der etwas  merkwrdige, aber dennoch gute
"Starball" auf dem ST einschlug und mit "Pinball Dreams" dem Falcon endlich mal
eine Umsetzung vom Amiga her spendiert wurde.
Ganz unbemerkt  davon blieb  dieser Flipper  hier. Die erste  Version lief auch
noch auf den alten ST's, doch nun wollen die Leute wohl auch auf den ins Rollen
gekommenen STE und Falcon-Zug aufspringen.
Tja, wenn man das Teil startet, erscheint erst die Frage nach der Rigistrierung
(welche ihr aber aus unten n„her erw„hnten Grnden) mal nicht beantworten soll-
tet...
Dann geht's weiter. Auf dem  Falcon scrollt nun ein  Pic in 256 Farben, welches
aber nicht umwerfend ist, herein. Naja, vielleicht wird's ja noch besser, denkt
man sich nun.
Als n„chstes kommt man in den Options-Screen, auf dem man diverse Einstellungen
vornehmen kann, wie  die Zahl der  Spieler festlegen, die  Highscores anschauen
und auf dem Falcon die Bildschirmaufl”sung w„hlen und Musik an und ausschalten.
Natrlich strzen wir uns gleich ins Getmmel und  drcken F1, obwohl der etwas
h„liche Options-Screen schon schlimmes vermuten l„t.
Es gibt nur einen Tisch  zu spielen, welcher  grafisch extrem  spartanisch aus-
sieht. Davon wollen wir uns aber  nicht unbedingt  beeinflussen lassen. Im Hin-
tergrund h”rt man Samplesound, der aber  nicht sonderlich abwechslungsreich ist
und sich dauernd  ziemlich schnell wiederholt. Wir schieen  die Kugel ins Feld
und merken zuerst, da es kaum FX gibt! Hin  und wieder mal ein Klack und sonst
ist Ruhe, wenn man die Musik abgeschaltet hat. Was als n„chstes unangenehm auf-
f„llt, ist die "Physik"! Die Kuller schwebt manchmal  mehr ber den Screen. Man
hat sie zudem  auch nicht sonderlich unter Kontrolle, sie schnippt  mal so, mal
so, auch wenn die  Voraussetzungen  die  selben sind, unter  denen  man sie ab-
schiet. Das das Teil aber auch noch durch die  Schl„ger durchfallen  kann, ist
schon extrem schwach... Ich jeden Falls habe gleich ESC gedrckt und mir meinen
Tag mit anderen Games verst!
Leute! Spart die 20 DM Registriergebhr und holt euch lieber Obsession, da habt
ihr echt mehr davon! Selbst eingefleischte Flipper-Leute, die nach jedem  Tisch
lechzen, sollten  Abstand nehmen, oder ihr werdet es bereuen... Wenn nicht, ich
habe euch gewarnt.

Bewertung
=========

Allgemein:
----------
Positiv : auf Falcon in Overscan, 4 Spieler, Highscore

Negativ : simple farbarme Grafik, eint”niger Sound und wenig FX, Physik!!!

Gesamt:
-------
Grafik         :  45 %
Sound          :  60 %
Steuerung      :  75 %
Motivation     :  35 %
Preis/Leistung :  20 %
----------------------
Gesamt         :  47 %
======================

-------------------------------------------------------------------------------
                                                                 Moondog of tnb
-------------------------------------------------------------------------------

                             PACMAN ON E'S
                             -------------
 
Hersteller : Digital Dreams / England
Art        : Pacman-Clone
Spieler    : 1
System     : STE, Color, 1 MB RAM, Joystick (Falcon nur „uerst bedingt...)
Status     : Shareware
Preis      : Registrierung 5 Pfund

Ha! Wer kennt's nicht, das gute  alte Pacmania-Spiel?! Tausende  Clones treiben
sich auf allen m”glichen Rechner-Systemen herum und nun wurde auch  der STE mit
einer speziellen Version bedacht. Momentan habe  ich hier nur Version eins lie-
gen, auf welche sich auch dieser Test bezieht.
Im Intro kriegt man von einem Typen erstmal einen Smiley ins Gesicht gedonnert.
Alsdann ert”nt der erste Tracker-Sound und es gibt einige Info's zum Spiel, mit
netten Grafiken untermalt.
Dann geht's schon ab ins Spiel.
Wie das abl„uft wei  wohl hoffentlicht  jeder, nein?! Grmbl... Nunja, ihr mt
einen Smiley durch  ein Labyrinth  steuern, alles  einsammeln, was rumliegt und
dabei dann euren Gegnern, die in  Form von  Geistern und in  Scharen auftreten,
ausweichen. Eine Kollision mit eben jenen fhrt zur  Verabschiedung eines Bild-
schirmlebens... Dazu gibt es  noch Extra-Boni und  Punkte, deren einsammeln die
Geister kurz paralysiert und eurem Fresack hoffnungslos ausliefern.
Die Grafiken sind Knallbunt, ohne  dabei h„lich  auszusehen. Die Animation der
Sprites ist ausreichend, der Sound kommt  Stereo einfach toll rber. Es gibt in
jedem Level eine andere recht  flotte Melodie. Die Steuerung funzt auch und so-
mit kann man diesen Clone wohl mit zu  den besten erh„ltlichen rechnen, von dem
Crapman in der Synergy-Demo mal abgesehen...
Wer dieses Game immernoch  bis zum Excess  spielen will und alle anderen Clones
schon durch hat, sollte also  ruhig mal  diesen Genossen hier anspielen, zumin-
dest, wenn man im Besitz  eines STE ist. Das Teil l„uft zwar auch auf dem F030,
doch wird einem da der Sound verg„llt (kratzt und scharrt...).

Bewertung
=========

Allgemein:
----------
Positiv : nette GFX, toller Sound, Steuerung ist ok...

Negativ : ?!

Gesamt:
-------
Grafik         :  65 %
Sound          :  80 %
Steuerung      :  80 %
Motivation     :  75 %
Preis/Leistung :  80 %
----------------------
Gesamt         :  76 %
======================

-------------------------------------------------------------------------------
                                                                 Moondog of tnb
-------------------------------------------------------------------------------
 
                                 ULTIMATE ARENA V. 1.3
                                 ---------------------
 
Hersteller  : STeam Shareware / Frankreich
Genre       : Beat'em Up
Spieler     : 1
System      : STE, Falcon, 1 MB, RGB/VGA, Festplatte m”glich, Joystick
Status      : Shareware
Preis       : Registrierung 99 FF (etwa 25 DM)

Wow! Da soll nochmal einer sagen, es  w„ren keine Spiele wie  Mortal Kombat auf
unseren Maschinen machbar! Dieses  Teil hier beweit das  ganze Gegenteil, denn
es ist ein lupen-reiner Clone dieses Games!
Ihr tretet dabei in einer Arena, die nach rechts und links scrollt, gegen einen
Typen an und prgelt euch mit ihm, da  das Blut nur  so spritzt! Also  erstmal
drfte  dieses Game  hier auf den  Atari's neue  Mast„be in Sachen  Brutalit„t
setzen. Desweiteren  ist die  Grafik  sehr gut  gelungen, sind die Spielfiguren
doch ganz  ansehnlich animiert  und vor allem  digitalisiert. Soundm„ig ist in
dem auch einiges los. Die Dresch- und St”hn-FX klingen nicht schlecht.
Weiter. Im  Hintergrund dieser  Szenerie gibt  es einen Vulkan zu sehen und das
Ziel besteht  darin, den Gegner in die  Lava zu  kicken oder aber auch so breit
zu schlagen. Die Steuerung ist  dabei etwas  hakelig, doch  fr die Vollversion
wird eine bessere Steuerung angepriesen, und nicht nur das.
Die Vollversion enth„lt  einen 2-Spieler-Modus, 7 verschiedene K„mpfer zur Aus-
wahl, 5 verschiedene Szenarien, eine  Option zum An- und  Ausschalten der Gore-
Szenen  und  Special-Moves. Dazu soll  jede Figur  ber 3 individuelle Special-
Moves verfgen... In  dieser Probe-Version  k„mpft man leider  gegen einen sehr
starken Gegner, der einen, sollte  man ihn  tats„chlich mal  ziemlich zusammen-
geprgelt haben, pl”tzlich schnurstracks in den Abgrund buxiert...
Tja, was soll ich sagen. Diese Demo hier macht  unheimlich was her und ich kann
mich wohl fast schon zu den Interessenten der Vollversion rechnen...
Alle, die mal wieder neue Prgelkost brauchen, einen STE oder Falcon haben, fr
letzteren ist brigens eine eigene Version  in Arbeit oder schon fertig..., und
kein Geld fr 'nen Jaguar haben, sind mit "Ultimate Arena" sehr gut bedient!!!

Bewertung
=========

Allgemein:
----------
Positiv : digitalisierte Grafiken  und  Bewegungsabl„ufe, Special-Moves, in der
          Vollversion viele Features, gutes Preis/Leistungsverh„ltnis
Negativ : in dieser  Version hakelige  Steuerung und  fr jngere  Zocker nicht
          ganz unbedenklich (Goreszenen...)
 
Gesamt:
-------
Grafik         :  90 %
Sound          :  75 %
Steuerung      :  60 %
Motivation     :  70 %
Preis/Leistung :  85 %
----------------------
Gesamt         :  76 %
======================

-------------------------------------------------------------------------------
                                                                 Moondog of tnb
-------------------------------------------------------------------------------

                                UTOPOS 1.61
                               -===========-

Hersteller    : Aggression / Finnland
Genre         : Thrust-Clone - Ballerspiel
Spieler       : 2
System        ; STE, Falcon, 1 MB, RGB, Joystick, Festplatte m”glich
Registrierung : 20 DM

Utopos wird seit dem Tod von Chronicle von Aggression  weiter supportet und die
hier  vorliegende  Version ist  die  neueste (M„rz '95) und  auch  bug-freieste
Version des Games.
Zum Spiel-Inhalt. Zwei Spieler k”nnen hier ran und sich  auf einem Spielfeld im
Splitscreen  simultan vom  Himmel holen. Dazu  fliegt ihr in Thrust-Manier, da
heit es  gibt keine  Schwerelosigkeit und  ihr mt euch durch steuern und be-
st„ndiges Gas geben immer in der Luft halten, in 8 verschiedenen Warzonen herum
und mt versuchen, euren Gegenspieler wegzupusten.
Dazu stehen  euch diverse  Bordkanonen und  Spezial-Waffen  zur  Verfgung, mit
deren Hilfe ihr  eurem Gegner zu Leibe rcken k”nnt. Um dies nicht allzu leicht
zu gestalten, wurde  eine „uerst kleinliche  Kollisions-Abfrage eingebaut, die
euch bei jedem  Anecken an die  Felsen im Game  explodieren l„t. Ihr k”nnt nur
auf dem Wasser oder  euren eigenen Sttzpunkten landen. Auf letzteren k”nnt ihr
auch  eure  Schiffe wieder  aufmunitionieren, reparieren  und neu bewaffnen und
erneut gegen euren Gegner ins Gefecht ziehen.
Technisch ist  das Game recht gut. Es l„uft nun auch auf dem Falcon in Overscan
(natrlich auch auf  dem STE, in 280 Zeilen vertikal), was das Spielfeld natr-
lich erheblich vergr”ert. Die  Grafik sieht recht ansprechend aus und ist voll
zweckm„ig. Soundm„ig wird leider  nur in Intro  und Men ein gutes Techno-MOD
geboten. Im  Spiel  selbst gibt  es recht  wenige, aber  gute Soundeffekte. Die
Steuerung ist  sehr gew”hnungsbedrftig. Man  kann auch ber  Tastatur spielen.
Anf„nger werden sicherlich erstmal  eine Weile  brauchen, bis sie ihren Fighter
anst„ndig unter Kontrolle haben  und so w„re es ratsam erstmal alleine zu ben,
bevor man  sich mit einem in  ein Combat-Game ein  l„t. Eine Einspieler-Option
gibt es (leider) nicht, doch der Computer-Gegner w„re sicherlich berm„chtig...
Die Steuerung  wird insofern  immer  schwieriger, je  mehr man  sein Schiff mit
Waffen  und Sprit aufgeladen  hat, was  bewirkt, da  man unheimlich  zu wrgen
hat, um sein nun erheblich schwereres Schiff unter Kontrolle zu halten...
Im groen und  ganzen kann  man davon  ausgehen, da sich  zwei gebte  Spieler
sicherlich lange  beballern k”nnen  und fr ausreichende  Abwechslung ist  dank
der verschiedenen Warzonen und Waffen sicherlich auch gesorgt...
Wer einen Kumpel  hat und gegen  diesen zu Felde  ziehen will, kann  sich ruhig
mal nach dem Teil umsehen...

Bewertung
---------

Allgemein:
----------
Positiv : sch”ne Grafik, gute Intro-Musik und nette FX, Waffen-Auswahl

Negativ ; kein Ein-Spieler-Modus, sehr gew”hnungsbedrftige Steuerung

Gesamt:
-------
Grafik         :  70 %
Sound          :  75 %
Steuerung      :  70 %
Motivation     :  80 %
Preis/Leistung :  75 %
----------------------
Gesamt         :  74 %
======================

-------------------------------------------------------------------------------
                                                                 Moondog of tnb
-------------------------------------------------------------------------------
.