               Die Temperaturbestimmung des Himmels und der H”lle
              ====================================================
       oder: Mit Mathematik l„t sich alles beweisen - auch das Gegenteil!


Aus den verfgbaren Daten kann die Temperatur des Himmels hinreichend genau be-
rechnet werden. Die Quelle dieser Daten  ist die Bibel. In Jes. 30,26 lesen wir
ber den Himmel:

ZITAT: Ferner wird das Licht des Mondes stark wie das Licht der Sonne sein, und
das Licht der Sonne wird 7 mal st„rker sein als das Licht von 7 Tagen".

Daher erh„lt der Himmel vom Mond soviel Strahlung, wie wir von der Sonne erhal-
ten, und darberhinaus von der Sonne 7 mal 7 (=49) mal soviel wie die Erde  von
der Sonne erh„lt, also im Ganzen 50 mal soviel. Mit diesen Daten k”nnen wir die
Temperatur des Himmels berechnen. Die Strahlung, die auf den Himmel f„llt, wird
ihn bis zu jenem Punkt aufheizen, an dem der W„rmeverlust durch Abstrahlung ge-
rade genauso gro ist, wie die W„rme, die durch  Einstrahlung aufgenommen wird.
Anders gesagt: Der Himmel verliert durch Strahlung 50 mal soviel wie  die Erde.
Unter Verwendung des  H.-Krischna-Gesetzes (bitte in jedem x-beliebigen Physik-
Lehrbuch nachlesen) fr Strahlung, stellt man nun folgende Relation her:

                                    (X)^4
                                   -------- = 50
                                     (Y)

wobei X die absolute  Temperatur des  Himmels und Y diejenige der Erde ist. Die
durchschnittliche absolute Temperatur  der Erde  kann hinreichend genau mit 300
Kelvin angegeben werden, die Berechnung ergibt dann fr X 789 Kelvin, dies sind
525 Celsius.

Wir halten fest: Der Himmel hat eine Temperatur von 525 Grad Celsius!

Die Temperatur der H”lle l„t sich weniger  exakt  bestimmen, immerhin ist aber
die Angabe einer Maximaltemperatur m”glich. In der Offenbarung, Kapitel 21,Vers
8 liet man:"Aber die Furchtsamen und Ungl„ubigen sollen ihren Platz in dem See
finden, der von Feuer und Schwefel brennet". Ein See aus geschmolzenem Schwefel
bedeutet, da seine Temperatur unterhalb des Siedepunktes liegen mu, der 444,6
Celsius betr„gt, denn oberhalb dieser Temperatur w„re  der See Dampf, und nicht
flssiger See (Eine Temperatur ber 444,6C widerspr„che der Bibel!)

Nun ist es geschafft: Wir haben die Temperatur des Himmels exakt mit 525 Grad C
und die Maximaltemperatur der H”lle mit 445 Grad C bestimmt.

Ergo: Der Himmel ist heier als die H”lle!

 

                                      Eine Berechnung von FIREBALL (Amiga)
                                                      und VISOR



P.S.: Das n„chste Mal errechnen wir die Lottozahlen der n„chsten 26,642 Jahre!


  