           Warum so viele West-Hunde so schrecklich deprimiert sind
           --------------------------------------------------------

Nun ist eindeutig bewiesen: Die Gewalt  nimmt nicht nur bei Menchen zu, sondern
auch bei Hunden. Die  Gesundheitsverwaltung des  Berliner Senates hat eine Bi-
statistik vorgelegt, aus der  hervorgeht, da 1992 in der Hauptstadt exakt 1792
Hunde zugebissen haben. In 1409 F„llen was ein Mensch das Opfer, in den anderen
F„llen fielen unsere lieben vierbeinigen Freude ber eigene Artgenossen her. Im
Vergleich zum Vorjahr weist die Statistik einen Anstieg von 4,5 Prozent aus.

Ein  Psychologenteam  hat  versucht, eine  Erkl„rung fr  diese  Entwicklung zu
geben.

Das Verhalten  der Hunde, so  heit es, h„nge  zusammen mit der  hohen Arbeits-
losenquote in Deutschland. Vor  allem Tiere in den neuen  Bundesl„ndern fhlten
sich nach der  politischen Einheit des Landes  entwurzelt  und wrden einer fr
sie ungewissen Zukunft entgegensehen.

Schlimmer dran  als die  Ost-Hunde sind  jedoch die  West-Hunde. Jahrzehntelang
lebten sie unbekmmert und genossen ihren Wohlstand.

Jetzt, in einer  Zeit der wirtschaftlichen  Rezession, h„tten die alten Verhal-
tensmuster keinen  Bestand mehr. Gelangweilt  und motivationslos schlendern sie
mit Herrchen oder Frauchen durch die Parkanlagen.

Der dadurch entstehende Aggressionsstau k”nne sich schon mal bei geringem Anla
entladen, etwa beim  Auftauchen von kleinen Kindern oder Joggern, sagen die Ex-
perten. Beim Senat wird daher aus Sicherheitsgrnden die Abschaffung aller Kin-
der erwogen sowie ein Park- und Waldverbot fr Jogger.

An ein Verbot zur  Haltung eines Hundes ist  nicht gedacht. Der Tierfuttermarkt
sei eine fr die Wirtschaft zu bedeutende Branche, heit es in Senatskreisen.

In Berlin, der Hunde-verrcktesten Stadt Deutschlands, leben zirka 130 000 Hun-
de. Sie bescheren der Metropole eine Wurst-Decke von 20 Tonnen t„glich.
Denn wenn sie nicht beien, dann .... sie.

-------------------------------------------------------------------------------
                                                                     Laserdance
-------------------------------------------------------------------------------
----------------------------------------------------------------------------
  