                               JAGUAR CD ROM
                               -------------
 
Hier schnell mal die Daten des Jaguar CD ROM (aus ST Magazine 86):

- Double Speed Laufwerk
- liest auch Audio-CD's
- 790 MB Speicherkapazit„t
- Daten-šbertragungsrate 352,8 KB pro Sekunde
- Preis 199,95 US-Dollar

Jede Menge Spiele sind in Entwicklung (schaut mal in die Jaguar-Liste!).

                                                    Moondog of tnb / 20.08.1994
