                          SPIELE-TIPS FöR'S ATARI LYNX
                          ----------------------------
 
Um mal dieser  Rubi etwas Leben einzuhauchen, habe ich mal ein paar Spiele-Tips
aus diversen Zeitschriften  zusammengetragen. Ich konnte sie  mangels Lynx aber
nicht ausprobieren. Mal sehen, vielleicht lassen  wir die Tips stÑndig drin und
erweitern die Liste entsprechend, so wie die Demo-Cheats-Liste fÅr die Compi's.

                                                    Moondog of tnb / 15.08.1994
-------------------------------------------------------------------------------

BLUE LIGHTNING
--------------
Levelcodes:

AAAA, PLAN, ALFA, BELL, NINE, LOCK, HAND, FLEA, LIFE

DINOLYMPICS
-----------

Levelcodes:

KRIS,

VIKING CHILD
------------
Level Codes:

OMEGAMAN, PATRICIA, REDDWARE, DEWSBURY

-------------------------------------------------------------------------------

Tja, viel isses noch nicht. Wenn ich mehr Zeit habe, sacke ich auch mal Tips zu
Spielen aus alten CF's raus.
