 
                                  DFö News...
                                  -----------

Neues vom Modem-Markt:

CTK in  Bergisch Gladbach  hat den Vertrieb der  neuen V.34-Modems von MOTOROLA
freigegeben! Das zugelassene  TischgerÑt  326XFAST ( ca. 2875 DM ) wird ergÑnzt
durch das  326XFAST-SDC Modell (ca. 3390 DM), daû  zusÑtzlich eine  Kompression
synchroner Daten ermîglicht.
Die bereits  auf der CeBIT'94 vorgestellten Telejet 28800 Modems  sind nun lie-
ferbar. Mit fÅnf Jahren Garantie bringt die  Hamburger Firma MMS das  Sportster
28800 auf den deutschen Markt. Das V.34 Modem  von US.Robotics  beherrscht auch
V.FC und ist mit ca. 600,- recht gÅnstig ;-).
DR.Neuhaus senkt die Preise (!)... das Smarty 14.4 TI kostet nun nur noch 390,-
und das  um Voice  erweiterte Smarty 19.2 TI/Voice  kostet z.Z. ca. 580,- inkl.
Software-Paket (leider nur PeeCee :-( !).
Bei einer  Fahndungsaktion nach  nicht zugelassennen  Modems ;-) "beeindruckte"
die Beamten das BZT-Zeichen auf den zugelassenen ELSA-Modems nur wenig. Die Be-
sitzer muûten  die entsprechenden Zulassungsurkunden von ELSA anfordern, um die
GesetzeshÅter zu beruhigen!
HAYES, die vor  kurzem den  Connect Service Riedlbauer in ihr  Ditributionsnetz
aufnahmen, wird KÑufern  des Optima V.FC-Modems  fÅr ca. 170,- ein  Upgrade auf
den endgÅltigen V.34-Standart  anbieten. Teilnehmer  des  Hayes-Sysop-Programms
erhalten ein kostenloses Upgrade!!!
PSP aus  HahnstÑtten hat eine  14400'er PSMCIA Typ-II  Fax-Modem-Karte  von IBM
(buh) in sein  Angebot aufgenommen. Die Karte ist in allen europÑischen LÑndern
zugelassen  und soll  inkl. Fax- u. DFö-Software (leider auch  nur PeeCee!) ca.
550,- kosten!
SUPRA zeigt auf der diesjÑhrigen MacWorld V.fast Modems fÅr den  Apple Mac! Die
externe Version SupraFAXModem 288 wird ca. 650,- kosten, intern ca. 750,-!

-------------------------------------------------------------------------------
                                                     aus irgendeiner Mailbox...
-------------------------------------------------------------------------------
