-------------------------------------------------------------------------------
                               Gerchte, Gerchte
                          Ob das tut wohl stimmen tun?
-------------------------------------------------------------------------------

Jaja, gerade mal  wieder im Internet  rumgeschnffelt, und  siehe da, es halten
sich doch  recht hartn„ckige Gerchte ber  einen neuen  Tratari-Compi, welcher
sich dereinst Milan nennen tun soll.
Ich  bin  mal  so  frei, das  hier  einfach  reportierenderweise dem freundlich
offenen Publikum darzutun, behalte mir jedoch groáe Zweifel vor, was im šbrigen
auch die Meinung im Netz zu sein scheint.
Tragen wir doch mal zusammen:

Pro:

- in irgendeinem franz”sischem Mag soll demn„chst ein  lustiger kleiner Artikel
  zu dem Computer erscheinen tun - na, mal sehen

- die Informationen  sollen von  seitens ATARI/Dtl. auf  geheimnisvolle, sicher
  bernatrliche Art und Weise stammen, denn ...( siehe unten )

Contra:

- naja, die  Message aus Dtl. máte  wohl ein  Medium empfangen  haben, da Tote
  gew”hnlich  sich  Normalsterblichen  nicht  zu offenbaren  pflegen, schon gar
  keine geschlossenen Firmenabteilungen

- wenn die  allseits bekannte  Firma schon was  neues tut bauen  tun, so sicher
  eher den Jag II, mit  dem man vielleicht noch Geld verdienen kann, und sei es
  nur, indem man das Chipset an die Japaner verkauft :-)

- die Zeit ist nicht rum. Atari baut nur aller 4 Jahre neue Computer ( 85 - ST,
  89 - TT, 93 - F030, 97 - ? ) Noch l„nger pflegen brigen die  Zeitabst„nde zu
  sein, die Atari  braucht, um Updates ihres allseits bekannten und gesch„tzten
  Betriebssystem mit der Trivialbezeichnung TOS zu produzieren.

- der Compi soll auf der CeBit 95 dem staunenden Fach- und Consumerpublikum vor
  die plattgedrckten  Nasen gesetzt werden. Nun waren die  Jungs aus Sunnyvale
  schon anno domini 94 nicht auf der CeBit, und mir sind noch keine Gerchte zu
  Ohren gekommen, daá Atari seinen alten Stand wieder angemietet h„tte.

Fazit:

Glauben tu' ichs nicht, aber - mal ganz  ehrlich - wnschen t„t  ichs mir schon
tun, nech !

-------------------------------------------------------------------------------
                                                                      Lot / tnb
-------------------------------------------------------------------------------

