                                 EDITORIAL
                                 ---------
 
Hallo alle zusammen!

Willkommen zu einer  neuen Ausgabe des wohl einzigen deutschsprachigen Diskmags
dieser Art auf ST und Falcon.
Heute (27.10.1994), wo ich anfange, dieses Editorial zu verfassen, habe ich mir
viele Gedanken gemacht,ber die Zukunft des Atari ST und Falcon sowie der dazu-
geh”rigen Userschaft.
Dunkle Wolken sind ber Atari-Land aufgezogen und werden  immer dichter. Es hat
inzwischen keinen  Zweck mehr, zu versuchen, die Dinge, die rundherum um unsere
Rechner passieren, sch”nzuf„rben oder zu vertuschen.
Wir sehen uns  mit dem unmittelbaren Tot des ST und der  kompletten Szene  dazu
konfrontiert. Zwar zappelt hier und da noch jemand, der noch nicht auf den 030-
Zug aufgesprungen ist, aber die geh”ren zumindest in Deutschland zu einer klei-
nen best„ndig schrumpfenden Minderheit  ohne Zukunft. In den  anderen Bastionen
des ST sind die Lichter noch nicht so weit ausgedreht wie hier und insbesondere
in Frankreich scheinen  sich viele  noch nicht damit  abgefunden zu haben ( Ein
groes Hallo an Sink / Hemoroids ) und versuchen best„ndig unserem Geburtstags-
kind neues Leben einzuhauchen...
Ebenfalls  schwer im Magen liegt  die Tatsache, da der  Falcon immer noch kein
Bein auf den Boden bekommen hat und diese Aussichten  von Tag zu Tag schwinden.
Zwar hat sich die Demoszene auf dem 030 endgltig etabliert, aber ansonsten ist
tote Hose auf dem Raubvogel.
šber den Jaguar und die anderen Atari-Konsolen spreche ich hier nicht,da sie im
Prinzip nix mit  unseren Rechnern zu tun haben. Allein von Konsolen kann dieses
Mag nicht leben...
Schon im Jahre '93 war mir etwas flau im Magen als der Falcon in die Reihen der
ST-Freax einfiel. Doch damals kamen  noch Massen von Spielen und viele gute De-
mos fr den guten alten ST heraus. Ich dachte damals immernoch, da der ST ohne
Probleme seinen 10. Geburtstag schafft, doch ich hatte mich fast geirrt.
In vielen Demo's hie es "...see ya on the new falcon 030..." und als dann Ende
des Jahres die sonst recht umfangreiche Demo-Flut abebbte,begann ich mir sorgen
zu machen.
Der Spiele-Markt  schien von  der ganzen Sache  v”llig  unbeeindruckt. Es kamen
immer wieder neue und immer bessere Spiele heraus. Fr mich  war dies ein  Zei-
chen,da der ST noch nicht am Ende war...
Doch dann kam Anfang 1994 der Einbruch. Fast ber  Nacht wurden dem ST beinahe
alle nur m”glichen Software-H„hne abgedreht.
(Von den Anwender-Seite rede ich  hier mit Absicht nicht, da davon keiner leben
kann,oder?!...)
Auf der Fried Bits 2 hatte  ich dann  schlielich die Gewiheit. Auch die Demo-
Szene hat sich vom ST abgekoppelt und distanziert. WARUM?!
Nur sehr wenige bekanntere Gruppen haben noch nicht das Handtuch geworfen, doch
wie lange noch... Die groen Namen sind l„ngst  ausgestorben. Dafr machen sich
jetzt einige kleinere  Gruppen breit, die nur Mll  verzapfen und nix  mehr mit
einer anst„ndigen Szene zu tun haben. Leute! Der ST braucht ein paar Demos, und
zwar Gute, um im Gespr„ch und damit am Leben zu bleiben!
Die wenigen verbliebenen  Cracker knacken  die letzten  erscheinenden Titel fr
den ST und strzen  sich gleich  rudelweise auf  die paar Neuerscheinungen, die
noch hin und wieder in die Stille des ST-Marktes platzen. In ihren Crack-Intros
labern die dann  von totem System usw. Mensch, haben die's noch immer nicht ka-
piert?! Sind die wirklich zu doof, um zu begreifen, da sie Mitschuld am Unter-
gang des ST haben?! Lediglich eine Cracker-Formation, die eigentlich noch recht
jung auf dem ST war, TRSI, haben bereits Ende letzten Jahres angemerkt, da man
doch lieber etwas Zeit verstreichen  lassen solle, zwischen dem Erstverkauf der
Games und dem Cracken, da es  oftmals vor kam, da  die Games, bevor sie in die
L„den  kamen, schon in  gecrackter  Version  berall  rumgeisterten. TRSI haben
meines Wissens inzwischen die Crackerei  als TRSI eingestellt und  arbeiten nun
v”llig unter  dem Namen  Vectronix, allerdings  ohne den  neuen ST-Spielen eine
Gnadenfrist zu gew„hren. Auch eine Art Doppelmoral...
Der ST ist an verschiedenen Dingen zu  Grunde gegangen und die Cracker sind mit
von der Party, wenn es  ums einsargen  geht. Die anderen  Totengr„ber  sind der
Falcon  und der  PC/Konsolen-Markt. Zu  guter  letzt hat  auch Atari  noch eine
Schippe mit in der Hand!!! Wenn  sich hier  jemand wundert, da  ich den  Amiga
nicht mit erw„hne,dann liegt das ganz einfach daran, da die meisten User nicht
zum Ami abgewandert sind, sondern in Richtung PC und  Falcon verschwunden sind.
Die Leute, die zum Falcon  abgewandert sind, fhlen sich  unheimlich elit„r und
schauen von oben auf den ST herab. Was ist denn noch von der  frher vielgelob-
ten Freundschaft zwischen den Atari-Usern brig?!
Doch zurck zum ST,auf dem in diesem Editorial das Hauptaugenmerk liegt.
Diese Ausgabe kann nocheinmal die groen L”cher im ST-Soft-Sack verdecken, aber
ich wei bereits  jetzt beim besten  Willen nicht, wie wir die  ST-spezifischen
Rubriken im n„chsten Mag vollkriegen sollen.
Dies ist unheimlich paradox, denn ausgerechnet die Rubriken, die sicherlich das
meiste Interesse finden,werden unheimlich mickerig ausfallen. Die Falcon-Rubi's
sind davon sogut wie gar nicht  betroffen, da auf dem 030er genug Stoff heraus-
kommt, den man im Mag erw„hnen kann. Dies t„uscht  allerdings ber  die pr„kere
Lage auf dem Falcon hinweg, denn der  030 ist wohl  einer der  seltensten Home-
Compis mit meines Wissens keinen 100.000 verkauften Stck weltweit...
Und jetzt komme  ich zu dem Punkt, an dem ich euch, unsere Leser anspreche! Wir
sind im Gegensatz zum Anfang unseres Mag's nicht  mehr dazu in der Lage, allein
genug Stoff zusammenzusammeln (wenn das Erscheinen  des UC-Mags in einigermaen
annehmbaren Abst„nden erfolgen soll) um die Rubriken zu fllen!
Wir wollen aber nicht dem Stil vom "Maggie" verfallen und euch nur mit ein oder
zwei Software-Vorstellungen abspeisen. Dazu mssen  wir improvisieren  und auch
mal hin und wieder ein nicht mehr  ganz so neues Spiel vorstellen, doch mit ein
wenig Hilfe von euch k”nnen wir nicht nur die Quantit„t sondern auch die Quali-
t„t unseres Mag-Inhaltes erhalten.
Also! Wenn irgendwer von euch sich  ein neues Spiel zulegt, dann w„ren wir sehr
froh darber, wenn derjenige einen Artikel darber schreiben wrde... Bedingung
ist dabei, da die Spiele nicht allzu alt  sind. Fr Spielen-Vorstellungen, die
wirklich voll up to date sind, werden wir uns  noch was einfallen  lassen. Mehr
kann ich im Moment nicht dazu sagen.
Da auch die ST-Demo-Ecke m„chtig ins Wanken geraten ist, brauchen wir auch hier
dringend eure Hilfe! Wir k”nnen  leider nicht soviele  Kontakte halten um wirk-
lich alles an neuer  Demo-Soft zu erfassen, zudem die  meisten tnb-ler  sowieso
damit besch„ftigt sind,nur noch den Falcon mit Soft zu fttern.
Wenn ihr also eine  neuere Demo habt, die noch nicht im  Mag vorgestellt wurde,
so k”nnt ihr das machen, oder falls ihr euch  nicht traut, ber diese Sachen zu
urteilen, k”nnt ihr sie uns schicken! Dafr bekommt ihr das Mag dann umso eher!
Apropos. Wir werden versuchen, uns in Zukunft etwa alle 4 Monate eine neue Aus-
gabe unter's Volk zu werfen...
Wenn ihr uns ein wenig unter die Arme greift, dann wird Undercover das 10. Jahr
des Atari ST mit Wrde durchlaufen und  nicht so vor sich  hindmpeln wie manch
anderes Mag!
Solltet ihr aber nach wie  vor so faul sein wie bisher, dann sehen wir schwarz!
Denkt mal drber nach!!!

Heute, am 1.12.1994, m”chte ich mich nochmal kurz ins bereits fertige Editorial
einklinken. Inzwischen  sind  bei einigen  -tnb-lern, die noch  vor kurzem voll
hinter dem  Mag gestanden  haben, die  ersten Zweifel  aufgekommen. Nachdem ich
mehrere Leute von uns  konsultiert habe, mute ich  feststellen, das Undercover
kaum noch Rckhalt bei einigen, dieser Leute findet, was auch zu verstehen ist,
wenn man sich tagein tagaus die Beine rausreit, ohne da es fr n”tig gehalten
wird, wenigstens mal zu eine Karte  mit der seiner  Meinung zum Mag  oder einer
kleinen Aufmunterung zu schicken. An dieser Stelle sende ich nochmal einen Gru
an Sink / Hemoroids schicken, der der erste  aus dem Ausland  war, der sich auf
unser Mag hin gemeldet und uns Mut gemacht hat!
Die Meinung sieht inzwischen so  aus (ich teile sie NOCH nicht), da wir Under-
cover, sollte  es auch auf die 4. Ausgabe  nicht gengend  Resonanz geben, doch
nach der 5. Ausgabe einstellen werden, die noch definitv erscheinen soll.
Desweiteren wurde nochmal  die Idee mit der  Umsetzung von  Undercover ins Eng-
lische aufgenommen. Es war allerdings  keine Split-Issue mehr im Gespr„ch, son-
dern wenn, dann komplett in  Englisch. Da aber der erste Versuch  bereits kl„g-
lich gescheitert war, stehe ich diesem Anliegen „uerst skeptisch gegenber.
Ausgabe 5 wird ebenfalls in Deutsch gehalten sein.
šber die Zukunft nach Ausgabe 5  wird derzeit nur spekuliert. Zum einen kam die
Idee, Undercover  auf den  Amiga auszuweiten. Die  andere M”glichkeit  ist noch
rein spekulativ und wird  vorerst noch nicht  weiter zur Sprache  gebracht. Wie
und was nun geschehen wird, werdet ihr in Ausgabe 5 erfahren.
Grund des Ganzen  ist, da -tnb- durch Undercover  nahezu  handlungsunf„hig ge-
worden ist. Anstatt  die ganzen  anderen Projekte ( Demos und Spiele ) mehr ins
Visir zu nehmen, ist unsere  ganze Substanz in  der Erstellung des UC-Mags auf-
gebraucht worden. Irgendwo stimmen die Relationen nicht mehr. Ich bin zwar auch
als Redax  t„tig, aber ich bin  auch Grafiker  und da allein  in dieser Ausgabe
ann„hrend 300 KB Text allein von mir stammen, k”nnt ihr euch sicherlich denken,
was ich in letzter Zeit  groartig gemalt  habe... Ich bin  die Redax und nicht
der Autor vom Mag! Ich will mir nicht die Finger wundtippen, nur da ein Haufen
stinkendfauler Atari-User was zu lesen hat... Das mute ich mal rauslassen!
Derzeit haben wir nur noch einen aktiven Coder, der unser  wichtigstes Projekt,
unser Demo, erstmal  zur Seite stecken  mute, um das  Mag zu coden. Eigentlich
war fr diese Ausgabe ein  Coder-Wechsel  vorgesehen. Da  aber der  Rechner des
neuen Coders (Kyne) seit nahezu anderthalb  Monaten defekt und in der Werkstatt
ist, war dies nicht  m”glich. So  muten auch  eine  Reihe neuer  Ideen erstmal
drauen  bleiben. Vielleicht  kommen  diese ja  auch schon  zu sp„t. Der andere
Coder ( Apache ), der ebenfalls am Mag  mitcoden wollte, ist derzeit nicht mehr
dazu in  der Lage, da er wie's  aussieht unter  die Kommerz-Coder  geht und  in
Zukunft mehr Zeit in das Entwickeln von Tools stecken wird. Mehr dazu in Nr. 5.
šbrig ist nur  noch Drizzt, der  nicht mehr  wei, wo ihm  der Kopf  steht. Mir
geht es ebenso. Zum einen  wird uns  vorgeworfen, wir  w„ren unaktuell  und zum
anderen verlassen uns Schreiber, die vielleicht was aktuelles h„tten einbringen
k”nnen... Derzeit  sind  nur noch  6 Fremd-Schreiber  brig (die anderen 3 sind
vom Amiga!) und  das reicht  ganz einfach nicht!
Einen ganz groen Dank sende ich hiermit brigens an GNORT, der der einzige von
den Fremd-Schreibern  ist, der  wirklich  von Anfang an mitgewirkt hat.
Sorry an die wenigen, die aktiv mitgewirkt haben und sich fr Undercover einge-
setzt haben, aber es geht halt nicht anders...

šbrigens findet ihr in dieser  Ausgabe auch eine Reihe  von Texten, die aus ir-
gendwelchen Boxen gezogen worden sind. Wir  denken, da diese Sachen von allge-
meinem Interesse sind und m”chten sie hiermit auch den Leuten zug„nglich machen
die kein Modem oder dergleich haben...
Einige recht witzige Files mute ich leider  rauslassen (wie beispielsweise das
komplette  Text-File  zu "Life Of Brian"...), den wir  hatten keinen Platz mehr
auf der Disk (sowas soll's auch noch geben...)...

-------------------------------------------------------------------------------
                                              Moondog of tnb / Undercover Redax
------------------------------------------------------------------------------- 
