 
                                   HOLOCAUST
                                   ---------
 
Hersteller     : Dattrax Software
Art            : Shot'em Up
Disx           : 1
Steuerung      : Joystick
Spieler        : 1
System         : ST/STE (kein TOS 2.06!), Farb-Monitor/TV, 1 MB RAM
Status         : Shareware
Preis ca.      : Registrierung - 5 Pfund (ca. 12 DM)

So, nachdem der komerzielle  ST-Spiele-Markt so gut  wie zusammengebrochen ist,
kommen immer  mehr solche, als Low-Budget-Games konzipierte, aber technisch gar
nicht mal so Åble,Spiele heraus. Warum also soll ich sie nicht testen?

Egal. Jedenfalls handelt es sich hierbei um die ST-Format-Version,die angeblich
noch etwas abgespeckt daher kommt.

Im Intro war ich einerseits  angenehm von dem netten  Titel-Bild Åberrascht und
andererseits  von dem Mad-Max-Sound  weniger begeistert. Naja, wenigstens kommt
nicht nur unqualifiziertes Gequietsche aus den Lautsprechern.

Im Spiel selbst  hat man die Wahl  zwischen Mad-Max-Chipsound  und Chip-FX. Ich
empfehle allen,die MM schon nicht mehr hîren kînnen, die FX, die noch recht an-
stÑndig rÅber kommen.

Nachdem man dann  eine Reihe von Optionen  einstellen kann (Sound, Sprache...),
kommt man ins Spiel,welches von der Handlung her 0815 ist aber auch nix anderes
als eine stupide  Ballerorgie sein soll. Zu Beginn kriegt man eine ganz ansehn-
liche 3D-Animation  mit einem  startenden Gleiter  zu sehen. Die  Sprachausgabe
labert irgendwas zusammen und es geht schon los.

Die Game-Grafik selber ist weniger toll aber durchaus akzeptabel. Was sehr ent-
tÑuscht ist die  Hintergrund-Grafik. Die Sprites  selbst sind  relativ gut aus-
sehend und sind sehr schnell. Das Scrolling ist  ebenfalls ziemlich schnell und
absolut ruckelfrei.

Es gibt jede Menge  verschiedener Gegner, die  unterschiedlich  stark gepanzert
sind und daher nicht alle gleich aus der Welt zu schaffen sind.
NatÅrlich dÅrfen auch Extra-Waffen nicht fehlen. Es gibt Drohnen, Raketen,RÅck-
wÑrts-Kanonen und Power-Beams,um nur einige zu nennen.

Hier fÑllt  sehr stark auf, daû sich der Programmierer  an "Wings of Death" und
"Lethal Excess" orientiert hat.
Nach einiger Zeit begegnet man  einem Obermotz (ich habe erst den von LVL (?) 1
zu Gesicht bekommen).

Was mir nicht so gefÑllt ist, daû man keinerlei  Status-Anzeigen auf dem Screen
hat. Auûerdem ist es doof, daû man nur  ein Leben hat. Ist dieses  ausgehaucht,
verabschiedet  sich das  Game mit einer  weiteren 3D-Animation  und man hat die
Mîglichkeit sich in die Highscore-Liste einzutragen.

Was soll ich  groû sagen. Nicht unbedingt  der öberhammer  aber nicht Åbel  fÅr
Low-Cost-Soft. Werde mir bei  Gelegenheit  wohl doch  mal die  Komplett-Version
aus England bestellen...

Bewertung
=========

Allgemein:
----------
Positiv : schînes Intro und Extro, schîn gezeichnete Sprites, Highscore

Negativ : nur ein Leben, die Sprachausgabe nervt, keine Status-Anzeigen auf dem
          Screen

Gesamt:
-------

Grafik         :  65 %
Sound          :  65 %
Steuerung      :  75 %
Motivation     :  75 %
Preis/Leistung :  90 %
----------------------
Gesamt         :  74 %
 
                                                    Moondog of tnb / 18.04.1994
