                                  MAGNO-BALL
                                  ----------
 
Hersteller  : Valenti
Art         : Geschicklichkeit
Disx        : ca. 280 KB
Steuerung   : Joystick
Spieler     : 1-2
System      : ST/STE, Farb-Monitor/TV, 1 MB RAM
Status      : Shareware
Preis       : Registrierung - 5 US-Dollar (ca. 8 DM)

So, der Untertitel dieses Spieles ist quasi  mit Magnetischer Fuball recht gut
umschrieben. Ihr flitzt in diesem Spiel  mit einer Art Ball ber den Screen und
mt versuchen, einen noch kleineren Ball in eines der 6 (?) Tore auf der Seite
des Gegners schieen.

Dieser versucht natrlich das selbe und  versucht durch Rammen eures Balles die
kleine Nlle in seinen Besitz zu bringen. Der Haken ist n„mlich, da der kleine
Ball an  eurem Sprite  festkleben  bleibt und mittels  Feuerknopf wieder in die
Arena geschossen wird.

Da es einen Zweispieler-Modus gibt, ist das Feld gesplittet. šber einen kleinen
Radar-Bilschirm  unten kann  man verfolgen, wo der Gegner sich gerade befindet.
Die Steuerung ist  etwas schwer, da die Sprites  in Schwingung  gebracht werden
mssen und ein Zielen dabei doch etwas sehr viel šbung erfordert.

Das ganze  Teil ist mit  zweckm„iger Grafik  ausgerstet und wird  von Sample-
Sound im Spiel untersttzt, der sich  allerdings auf wenige  Sachen beschr„nkt.
Aufgewertet wurde  das Game zudem durch einen  einstellbaren Schwierigkeitsgrad
(nur in der Single-Player-Option) und die  M”glichkeit Festlegung der Dauer der
Spielrunde in einem gewissen Rahmen.

Alles in allem kann man sagen, da es sich bei diesem Spiel nur um ein Game fr
Fans handelt, da der Spielablauf h”chstens im Zweispieler-Modus etwas mehr Lust
macht und sonst eher ”de ist.

Bewertung
=========

Allgemein:
----------
Positiv : annehmbare Grafix,recht unverbrauchtes Spiele-Genre,Optionen,ein paar
          gute Samples

Negativ : Steuerung sehr gew”hnungsbedrftig,auf Dauer eint”nig

Gesamt:
-------

Grafik         :  60 %
Sound          :  55 %
Steuerung      :  45 %
Motivation     :  60 %
Preis/Leistung :  70 %
----------------------
Gesamt         :  60 %

                                                    Moondog of tnb / 20.08.1994

 
