*******************************************************************************
 
           "Hallo, is da noch jemand ?" oder "Der Tot einer Demoszene"
 
*******************************************************************************
 
 
Was war es nicht fr eine sch”ne Zeit, damals, im Herbst 1990. Der ST-Demofreak
wurde mit  neuen Demos  berschttet und ein  Ende war nicht in Sicht. THE LOST
BOYS hatten  gerade ihr "Life's a bitch"-Demo rausgebracht  und bereiteten  ihr
Hammerdemo "Ooh crickey wot a scorcher" vor, die Leute  von  DELTA FORCE  gaben
ihrem "Syntax Terror" den  letzen Schliff, THE CAREBEARS ruhten sich auf ihren,
mit dem  Syncscrolling  geernteten  Lorbeeren  aus und  TEX wagte  den  Schritt
in Richtung kommerzielle Spielesoftware, indem sie die Firma Thalion grndeten.
"Achja" h”re ich  manche von euch seufzen  und sich gerne an diese Zeit zurck-
erinnern.
 
Wer heute  noch einen  ST besitzt, ist wirklich  arm dran. Er schaut  sozusagen
"In die R”hre". Halbj„hrlich  kommt mal  ein  neues  Demo, wenn  das  berhaupt
reicht. Das ist dann meistens recht lustlos gemacht, da die Schaffer denken,daž
es sowieso niemanden interessiert. Die ST-Besitzer regen sich dann darber auf,
daž niemand  mehr etwas auf ihrem Rechner macht. Das war aber ganz klar voraus-
zusehen.

Wieso voraussehbar? Nun, dazu  will ich etwas  weiter ausholen... Als der ST im
Jahre 1985 das  Licht der Welt erblickte, war er, obgleich der ehrenvollen Wr-
digung  durch  die  internationale  Fachpresse (Computer des Jahres 1985/1988),
nicht gerade die Innovativmaschine.
Davon zeugten  die 16 Farben aus einer Gesamtpalette von 512 und ein Soundchip,
mit  dem  man  so  interessante  Ger„usche  wie "brrrr", "zisch" oder "krrrkkk"
machen konnte, aber leider keine vernnftige Musik.
Als sich dann im Jahre 1987 die ersten Cracker der vorsichtigen Demoprogrammie-
rung zuwendeten, sahen diese schnell ein, daž mit dieser Maschine  nur ber 100
Ecken einige  ansehnliche  Effekte zu  erreichen seien. Man saž also n„chtelang
vor seinen  Maschinen und entdeckte, daž  der ST auch seine  512 Farben gleich-
zeitig darstellen konnte (siehe hierzu das LCD-Demo von TEX), daž man nette Ef-
fekte mit dem ™ffnen des unteren Randes erzielte (siehe BIG-Demo), und daž der,
als  Kchenh„xler verschriehene  Soundchip auch ganz  vernnftige T”ne von sich
geben konnte (nochmals BIG-Demo).

Durch diese  mutigen Recken wurde  viele andere Leute angesteckt, mit ihrem As-
sembler und NeoChrome (damals noch in der Version 1.0) oder Degas bewaffnet,den
Deutschen  nachzueifern. Es entstanden viele neue Crews; besonders in Skandina-
vien fanden viele zum ST. Da dort die Tage bekanntlich besonders kurz und die
N„chte verdammt lang sind...

(Redax: Gar nicht  war! Im Winter vielleicht, aber nur ziemlich  weit droben im
        Norden! Im Sommer hatten die  teilweise gar keine Nacht - kennst Du den
        Begriff Mitsommernacht nicht?!...)
 
(d.h. mehr Zeit fr den Computer ;), kamen auch bald die  besseren Demos von da
oben. Es muž in irgendeiner kalt-verschneiten schwedischen Winternacht des Jah-
res 1990 gewesen sein, als Nick von TCB das Prinzip des Syncscrollings entdeck-
te. Er schaffte, was selbst  die Atari-Entwickler nie fr m”glich gehalten hat-
ten: er scrollte den kompletten Screen in  alle Richtungen. Aber auch hier galt
wieder das  Prinzip des "auf  Umwegen Codens". Diese ganzen  Effekte wurden von
nun an in fast  jedem guten Demo  ausgebraten und es gab da und dort mal wieder
einen sch”nen  neuen Effekt (so  beispielsweise  den  Plasma-Fullscreen  in der
mittleren  Aufl”sung von Flix/DF oder den  Protracker ST von zwei  couragierten
Skandinaviern) aber  alles wurde auf  Umwegen programmiert. Saubere Programmie-
rung war hier bei der Demoprogrammierung fehl am Platze. Es wurde getrickst und
gekittet wo man nur konnte.

Doch lange  konnte das so  nicht weitergehen: Sp„testens nach solchen Top-Demos
wie "Ohh Crickey..." oder "Punish your machine" war  jedem klar, daž nicht mehr
viel Neues machbar  war. Natrlich h„tte man noch viel am Design feilen k”nnen,
aber irgendwie merkte jeder, daž das Ende bald erreicht ist. Die Oktoberausgabe
des Jahres '91 der  Zeitschrift TOS beinhaltete einen einseitigen  Artikel ber
die I.C.C. 2, die gr”žte Demoparty  auf dem ST berhaupt. Der Artikel endet mit
einer  Vermutung, deren Wahrheitsgehalt  heute 100% zugestimmt  werden kann. Da
heižt es: "Ob >TEX<, >The Lost Boys< oder >The Replicants< - die  Programmierer
sind sich einig: Die F„higkeiten bezglich Grafik und Sound scheinen  endgltig
ausgesch”pft. Was  bleibt, sind noch schnellere  Routinen oder der  Umstieg auf
Mega STE und TT."

Zweifelsohne h„tte man bei den aufgez„hlten Maschinen auch den Falcon hinzuz„h-
len k”nnen, aber  der wurde zu  dieser Zeit noch  vom Muttervogel in  Sunnyvale
ausgebrtet. In dem, einem Democoder eigenen Streben nach immer  h”heren Zielen
zu greifen, war klar, daž eine neue Maschine her mužte, ein Rechner,auf dem man
ohne Tricks  sich an der Hardware  austoben konnte. Der Falcon  schien hier die
ideale L”sung: mit ber  65000 Farben, 16 Mhz, Blitter, 16 Bit-Stereosound, re-
lativ kompatibel zum ST und zu einem ganz guten Preis. Und die ersten Demos be-
wiesen: die Szene hatte  richtig gehandelt. Zumindest  was den Umstieg  auf den
Falcon ging. Nicht  richtig war  die vollkommene  Vernachl„ssigung des ST. Wenn
man allerdings  ganz genau  hinschaut konnten  die meisten Leute  ihr Potential
erst richtig am Falcon zeigen ,so z.B. Bitmaster mit seinem genialen DSP-Player
oder die Lazer-Crew. Die ganz produktiven ST-Leute haben mittlerweile Wichtige-
res zu tun, als am  Computer zu sitzen (siehe  die TEX-Leute). Und  viele Leute
der heutigen  Falconszene hatten damals, zu Anfang des ST's, noch gar nicht den
Draht zu Computern, da sie damals gerade mal 10 bis 12 Jahre alt waren und lie-
ber auf dem Hof rumrobbten als im Zimmer am Rechner zu h„ngen.
 
Klar, es kamen  auf dem ST anschliežend noch ein paar sehr gute Demos raus, die
teilweise auch neue  Effekte hatten (FLIPO/DD+OXG), aber diese entstanden meist
nur als Echo der Falcondemos, indem die Effekte des  Falcons einfach auf den ST
"runterkonvertiert" wurden.

Das waren meine eigenen Gedanken zu diesem Thema, Eure eigenen k”nnen ruhig an-
ders sein;aber es mužte doch mal gesagt sein,da es doch ziemlich schade ist....
 
-------------------------------------------------------------------------------
                                         				               m.O.d. of tnb
-------------------------------------------------------------------------------
